### ISSUE TITLE
"Latest" tag does not point at latest release

### ISSUE THREAD

**Issue by jeffwidman** [gevent/gevent#1014]
title says it all: https://github.com/gevent/gevent/releases

**Comment by jamadden** [comment]
Thanks. The latest release can be found at https://pypi.python.org/pypi/gevent I quit trying to keep the github page in sync because it was a lot of extra work.

**Comment by thedrow** [comment]
You can make Travis do this automatically. See https://docs.travis-ci.com/user/deployment/releases/

**Comment by jeffwidman** [comment]
@thedrow I just tried to put together a PR for this; however, I must be dense because I'm not understanding from those docs how to make travis do this... can you clarify or point to an example of another repo's `.travis.yml` file that does this?

**Comment by jamadden** [comment]
I'm not really on board with the whole travis-calling-back-to-github-to-automatically-change-things idea. I don't think I would be inclined to accept a PR that adds that unless it's overwhelmingly important to the community, especially since what can be done automatically doesn't seem to add much value (it's just another place to host a tarball).

**Comment by jeffwidman** [comment]
It's not important to me. I was thinking less about a tarball and more that travis would just realize when a new release was tagged and move the `Latest` pointer. If it's more complicated than that, then agreed it's not worth it.

**Comment by thedrow** [comment]
It's important because people check the releases page when they want to discover new releases or review the progress of the project.
I don't think I've seen another repo that does this.

**Comment by jamadden** [comment]
ISTM, the PyPI page (which even offers an RSS feed) is the canonical way to discover new releases (tagging something in github may happen well before artifacts are actually available on PyPI, given how long it takes to build artifacts). Checking the progress of the project is done by looking at the commit history or looking at tags.

I don't think I've seen any project that *does* automatically do anything with github releases. In fact, of the ~60 projects I have PyPI rights for, I'm not aware of any of them that do. Mostly they automate releases with 'zest.releaser', which doesn't do anything with github releases. (Granted those projects are only across a small number of organizations.) Those that do automate wheel production for PyPI (BTrees, zope.index, persistent, etc) do not also automate anything with github releases.

It actually seems gevent is the odd one out here, with that big green "latest release" link. Of projects I spot-checked, I was only able to find one other project that has that: gunicorn does; pip, BTrees, ZODB, RelStorage, wheel, packaging, persistent, and setuptools all do not. They also  automatically show latest tags on the "releases" page, they just don't have that big green link beside them. It seems that only happens when something adds specific release notes/uses the github-specific API. 

So I think the way for gevent to be consistent with other projects is to figure out how to remove that big green distracting link 😄
