### ISSUE TITLE
Gevent monkey patch child process only

### ISSUE THREAD

**Issue by maingoh** [gevent/gevent#1018]
I had an issue [here](https://github.com/shazow/urllib3/issues/1268) and we agreed that this is probably not an urllib3 problem. So I was wondering if it is possible to fork a process and monkey patch the child ONLY (probably need to unload or reload some modules).

**Comment by jamadden** [comment]
Because the forked process shares the module state with the parent process, that effectively counts as "late monkey-patching" which we explicitly do not support. If you are extremely careful about what you import in the parent process (E.g., do not import anything that uses anything that will be monkey-patched) it can be made to work. Or as you say, you might be able to unload and reload modules---but the specific modules would be application dependent and fragile. You'd just have to try; my intuition says it's probably possible, but painful. A less painful option may be to just create a whole fresh interpreter as a subprocess instead of forking.

**Comment by maingoh** [comment]
This is what I finally did, but this is less convenient to pass args to the subprocess and you cannot use some communications features like Pipe/Queues (I am not in this case, I use pyzmq) from gipc/multiprocessing. 

I was just wondering if it was possible for gevent to handle the unload/reload of the modules automatically when forking (I didn't manage to find the modules to remove).

**Comment by jamadden** [comment]
> I was just wondering if it was possible for gevent to handle the unload/reload of the modules automatically when forking

In general, no, it's not, at least I don't see how. If *any* user module has been imported that does `from socket import socket` or `from selectors import DefaultSelector` or any number of other things, they would have to be reloaded. How is gevent supposed to know about them? I don't think it's feasible for gevent to inspect *every* module in `sys.modules` and look at their `__dict__` and try to see if they have imported by name any of the (many, many) objects that gevent replaces and then try to reload them, all without introducing any ordering dependencies among modules that may define classes and subclasses, etc.

**Comment by maingoh** [comment]
Alright it sounds indeed quite complicated!

**Comment by jamadden** [comment]
Thanks for your report. I'm sorry I don't have a better solution to offer you, but I will try to keep this use-case in mind.
