### ISSUE TITLE
time.sleep(0.000001, False) => 'This operation would block forever'

### ISSUE THREAD

**Issue by arcivanov** [gevent/gevent#1068]
* gevent version: 1.2.2
* Python version: PyEnv Python 3.6.4 (default, Dec 19 2017, 17:09:19) [GCC 7.2.1 20170915 (Red Hat 7.2.1-2)] on linux
* Operating System: Fedora 27  4.14.11-300.fc27.x86_64 #1 SMP Wed Jan 3 13:52:28 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

### Description:

Given: a multi-threaded application that spawns couple of servers (nginx and nghttpx) via Popen with stdout and stderr piped, spawns threads to read said pipes and flush them into asynchronous Fluent logger (which spawns another thread that feeds from a queue of log messages being sent to it). 

The entire application is monkey-patched first thing in `__main__` as follows so all threads are greenlets:

```
if __name__ == '__main__':
    from gevent import monkey
    monkey.patch_all(Event=True)

    import time

    _sleep = time.sleep

    def sleep(seconds):
        return _sleep(seconds, False)

    time.sleep = sleep
```  

The application on `m4.large`  (2 CPUs) seems to fail to send messages to FluentD (it's been verified they are entering the Fluent thread queue) and on `r4.2xlarge` (8 CPUs) the messages are delayed. 

One theory I have is that the FluentD logger thread is starved by other threads. So I added a `thread.sleep(0.000001)` in the main thread after FluentD initialization to allow FluentD thread to be scheduled.

Alas, what I got was:

```
File "/usr/local/lib/python3.6/site-packages/<snip>/manager.py", line 526, in init_logging
time.sleep(0.000001) # Gevent
File "/<main.py>", line 14, in sleep
return _sleep(seconds, False)
File "/usr/local/lib/python3.6/site-packages/gevent/hub.py", line 169, in sleep
hub.wait(loop.timer(seconds, ref=ref))
File "/usr/local/lib/python3.6/site-packages/gevent/hub.py", line 651, in wait
result = waiter.get()
File "/usr/local/lib/python3.6/site-packages/gevent/hub.py", line 898, in get
return self.hub.switch()
File "/usr/local/lib/python3.6/site-packages/gevent/hub.py", line 630, in switch
return RawGreenlet.switch(self)
gevent.hub.LoopExit: ('This operation would block forever', <Hub at 0x7f68a973df20 epoll default pending=0 ref=0 fileno=3 resolver=<gevent.resolver_thread.Resolver at 0x7f68a6fab0f0 pool=<ThreadPool at 0x7f68a6fab160 0/1/10>> threadpool=<ThreadPool at 0x7f68a6fab160 0/1/10>>)
```

Under what circumstances **ever** would a 1 usec sleep block forever?! 
Did I forget to patch something?

**Comment by jamadden** [comment]
> The entire application is monkey-patched first thing in __main__ as follows so all threads are greenlets:
> ```python
> if __name__ == '__main__':
>    from gevent import monkey
>    monkey.patch_all(Event=True)
> ```

That doesn't *necessarily* follow.  If there are any imports that happen above that, they may not necessarily be monkey-patched at all (depending on how they are written). Consider `a.py`:
```python
from threading import Thread

def target():
   print("I'm in a thread")

def serve_forever():
   t = Thread(target=target)
   t.start()
   t.join()
```

Now consider `main.py`:
```python
from a import serve_forever

if __name__ == '__main__':
    from gevent import monkey
    monkey.patch_all()

    serve_forever()
```
   
A command like `python -m main` will *not* result in `serve_forever` using greenlets. The original `threading.Thread` had already been imported before monkey-patching took place, and so it was too late to change it. The same thing applies for sockets, ssl, etc.

This is why monkey-patching is usually recommended to be the first thing that happens in the main module, *including* before any imports. There are a few ways to arrange that (I like to have a separate module that does nothing but monkey-patches and then imports and calls the entry point) but it's critical.

A `LoopExit` is raised when there is no other greenlet to switch to, so the above (not monkey-patching all threads/imports) is certainly the first possibility that I would consider, based on what you've shown here.

As an aside, note that a 0.000001s sleep time may or may not do what one what expect in terms of the event loop, depending on timer resolution and internal implementation details of libev and the OS. 1e-6 is a common clock resolution for kernel timers, and attempting to sleep for that amount of time may immediately return without allowing any IO to be serviced. In virtualized/container environments, anecdotally, clock resolution tends to be worse. Also, the overhead of the loop itself tends to be higher than that, so a greenlet trying to sleep for that low should expect to sleep for much longer (in one test system, about 9 times longer---nearly an order of magnitude---even when the loop was otherwise idle; of course some of that is python measuring overhead too, so take with a grain of salt).

(Also, just an FYI, libuv tries to bypass that by limiting timer resolution to 1ms---0.001---at the application level. The upcoming optional (!) libuv backend for gevent has no choice at that point, but it does print a warning. Perhaps we need a better idiom for "please try to cycle the IO loop.")

**Comment by arcivanov** [comment]
There are no imports above that, that's the problem. 

The entire file looks like this:

```
#!/usr/bin/env python

if __name__ == '__main__':
    from gevent import monkey
    monkey.patch_all(Event=True)

    import time

    _sleep = time.sleep

    def sleep(seconds):
        return _sleep(seconds, False)

    time.sleep = sleep

    from module_core import main

    main()
```

**Comment by arcivanov** [comment]
> As an aside, note that a 0.000001s sleep time may or may not do what one what expect in terms of the event loop, depending on timer resolution and internal implementation details of libev and the OS. 1e-6 is a common clock resolution for kernel timers, and attempting to sleep for that amount of time may immediately return without allowing any IO to be serviced.

Well, I was actually following documentation and my goal was to yield to other greenlets, not to sleep any amount of time but rather to get to the bottom of iteration loop. I was going by (emphasis added):

```
In the current implementation, a value of 0 (the default) means to yield execution to any other runnable greenlets, but this greenlet may be scheduled again before the event loop cycles (in an extreme case, a greenlet that repeatedly sleeps with 0 can prevent greenlets that are ready to do I/O from being scheduled for some (small) period of time); ***a value greater than 0, on the other hand, will delay running this greenlet until the next iteration of the loop***.
```

**Comment by jamadden** [comment]
> Well, I was actually following documentation and my goal was to yield to other greenlets, not to sleep any amount of time but rather to get to the bottom of iteration loop. I was going by (emphasis added):
>> a value greater than 0, on the other hand, will delay running this greenlet until the next iteration of the loop.

And that's all true, but it doesn't tell the whole picture. A value greater than zero asks not to run this greenlet until the event loop cycles, but whether the event loop can do any useful work or not (detect any IO readiness) is dependent on the value and the system. Choosing too small a value *may* functionally be the same as a tight loop.

**Comment by arcivanov** [comment]
> Choosing too small a value may functionally be the same as a tight loop.

Ah. I think it's feasible to hide the underlying loop implementation detail though. If we follow the doc in the stated behavior, even if we don't know what the time resolution is, is it possible to just "yield" if time is less than 1ms (or 100us or any other number). 

Is there an idiom in gevent-proper for "get back in line to iterate"?

**Comment by jamadden** [comment]
> Is there an idiom in gevent-proper for "get back in line to iterate"?

`sleep` is currently the recommended way, and it provides the control over yielding to the event loop (non-zero) (and approximately how long) or not (0). The problem of choosing "too small" a value to sleep on is (a) system dependent, (b) expected to be unusual, (c) also seen with `Timeout` or any of the other places that a timeout value is accepted and (d) requires some understanding of event loops to describe. Perhaps the documentation could give more guidance about choosing an appropriate value, but I don't want it to bog down in details. I'd also rather not override the user's decisions; they know more about their system than gevent does.

If one wants to yield to the IO loop and *doesn't care how long*, the `prepare` (and `check`) watchers are available. These are scantily documented though (and because of their position within the event loop, may have some limitations).

So there are really three (or four) supported use cases: 

1. yield to other greenlets in the current loop iteration if there are any: `sleep(0)`
2. yield for at least X long and at least 1 loop iteration: `sleep(non-zero)`
3. yield until the next loop iteration: `prepare`
4. yield until after the current loop iteration: `check`

Perhaps these could be combined, but I'm not sure the overall API would be simpler. Using `prepare` and `check` could be simpler, probably, but it would take some thought to consider if those should be widely encouraged). 

An (untested) proper use of `prepare` would look something like this currently:
```python
def some_greenlet():

   prepare = gevent.get_hub().loop.prepare()
   gevent.get_hub().wait(prepare)
   prepare.close() # 1.3 only, not finalized
  # queue us within this loop iteration, but let the loop run previously scheduled callbacks first
   gevent.sleep(0) 

   # Do the stuff we wanted to do
```

**Comment by jamadden** [comment]
> There are no imports above that, that's the problem.

OK, so if we rule out non-monkey-patched threads, then we're back to the original root: there is no other runnable greenlet to switch to. Assuming you have spawned and are running other greenlets, one way to get "no runnable greenlets to switch to" is a deadlock. For example, this produces it:
```python
import gevent
import gevent.lock

l = gevent.lock.Semaphore(1)

def g1():
    l.acquire()

def g2():
    l.acquire()

glets = [gevent.spawn(x) for x in (g1,g2)]

gevent.joinall(glets)
```

If I were debugging this, my next step might be to dump the stacks of all the threads and greenlets before the call to sleep(). 

I use a function like this:
```python
def dump_stacks():
    """
    Request information about the running threads of the current process.

    :return: A sequence of text lines detailing the stacks of running
            threads and greenlets. (One greenlet will duplicate one thread,
            the current thread and greenlet.)
    """
    dump = []

    # threads
    import threading  # Late import this stuff because it may get monkey-patched
    import sys
    import traceback
    try:
        from greenlet import greenlet
        import gc   
    except ImportError:
        greenlet = None

    threads = {th.ident: th.name for th in threading.enumerate()}

    for thread, frame in sys._current_frames().items():
        dump.append('Thread 0x%x (%s)\n' % (thread, threads.get(thread)))
        dump.append(''.join(traceback.format_stack(frame)))
        dump.append('\n')

    # greenlets

    # if greenlet is present, let's dump each greenlet stack
    # Use the gc module to inspect all objects to find the greenlets
    # since there isn't a global registry
    for ob in gc.get_objects():
        if not isinstance(ob, greenlet):
            continue
        if not ob:
            continue  # not running anymore or not started
        dump.append('Greenlet %s\n' % ob)
        dump.append(''.join(traceback.format_stack(ob.gr_frame)))
        dump.append('\n')

    return dump
```

**Comment by arcivanov** [comment]
> If one wants to yield to the IO loop and doesn't care how long, the prepare (and check) watchers are available. These are scantily documented though (and because of their position within the event loop, may have some limitations).

Thanks for this. However, this requires the use of gevent-specific API and I'm trying to stay away from it beyond monkey-patching and write pure Python API code.

**Comment by jamadden** [comment]
> Thanks for this. However, this requires the use of gevent-specific API and I'm trying to stay away from it beyond monkey-patching and write pure Python API code.

And that's a big unstated part of the problem with #1070. The standard library alone does not have the ability to express the possibilities and represent all the options necessary, and gevent is not all-knowing. monkey-patching above and beyond all else must be *safe* or no one will do it.

> What about leaving gevent.sleep() alone but adding sleep-duration specific logic in the monkey to actually always ensure that there is a reschedule?

It's not clear what you mean. A non-zero duration *does* always trigger a "reschedule", if by "reschedule" you mean "cycles the event loop." Whether the event loop is able to *accomplish* anything or not is unknown, and cannot be derived just from the duration.

But this is off the point.
