### ISSUE TITLE
greenlet using time.sleep seems starving

### ISSUE THREAD

**Issue by antocuni** [gevent/gevent#1071]
* gevent version: 1.2.2
* Python version: CPython, 2.7.14, Ubuntu 17.10 package
* Operating System: Ubuntu 17.10 (Linux 4.13.0-21-generic #24-Ubuntu SMP Mon Dec 18 17:29:16 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux)

### Description:

Consider this example: it is the smallest possible example which reproduce an issue which I found on a real system; at its core, there are two greenlets:

1. `reader`: it `recv()` a chunk of bytes from a socket, then simulates a CPU-intensive processing. Every ~0.0005 seconds, it `time.sleep(0)` to yield control to other greenlets. Every ~1 second, it does a `recv()`.

2. `heartbeat`: endless loop which prints a message and does `time.sleep(0.1)`

```python
import sys
import time
import socket

HUB = sys.argv[1]
assert HUB in ('eventlet', 'gevent')

if HUB == 'eventlet':
	import eventlet
	from eventlet import spawn
	eventlet.sleep()
	eventlet.monkey_patch()
else:
	import gevent.monkey
	from gevent import spawn
	gevent.monkey.patch_all()


def reader():
	chunksize = 1024 * 100
	conn = socket.create_connection(('localhost', 3997))
	while True:
		print
		print 'Reading from socket...'
		chunk = conn.recv(chunksize)
		# simulate a CPU-intensive processing of incoming data
		for i in range(2000):
			busy_loop(0.0005)
			time.sleep(0)


def busy_loop(t):
	start = time.time()
	end = start + t
	while time.time() < end:
		pass


def heartbeat():
	while True:
		a = time.time()
		time.sleep(0.1)
		b = time.time()
		print 'heartbeat [waited for %.4f secs]' % (b-a)


def main():
	greenthread = spawn(reader)
	spawn(heartbeat)
	if HUB == 'gevent':
		greenthread.join()
	else:
		greenthread.wait()

if __name__ == '__main__':
	main()
```

### What I've run:

To simulate a fast server, I ran `nc` on localhost:

```
$ cat /dev/urandom | nc -l 3997
```

I would expect to see approximately 10 `heartbeat` for every `Reading from socket...`.
If I run it with `eventlet`, it seems to work as I expect:

```
$ python starve.py eventlet

Reading from socket...
heartbeat [waited for 0.1000 secs]
heartbeat [waited for 0.1001 secs]
heartbeat [waited for 0.1003 secs]
heartbeat [waited for 0.1004 secs]
heartbeat [waited for 0.1000 secs]
heartbeat [waited for 0.1003 secs]
heartbeat [waited for 0.1002 secs]
heartbeat [waited for 0.1003 secs]
heartbeat [waited for 0.1002 secs]
heartbeat [waited for 0.1001 secs]

Reading from socket...
heartbeat [waited for 0.1002 secs]
heartbeat [waited for 0.1002 secs]
heartbeat [waited for 0.1002 secs]
heartbeat [waited for 0.1001 secs]
heartbeat [waited for 0.1003 secs]
heartbeat [waited for 0.1001 secs]
heartbeat [waited for 0.1002 secs]
heartbeat [waited for 0.1005 secs]
heartbeat [waited for 0.1000 secs]
heartbeat [waited for 0.1004 secs]
```

However, if I try it with `gevent`, I see this weird behavior:
```
$ python starve.py gevent

Reading from socket...
heartbeat [waited for 0.5114 secs]

Reading from socket...
heartbeat [waited for 0.5094 secs]
heartbeat [waited for 0.5089 secs]

Reading from socket...
heartbeat [waited for 0.5087 secs]
heartbeat [waited for 0.5086 secs]

Reading from socket...
heartbeat [waited for 0.5085 secs]
heartbeat [waited for 0.5085 secs]

Reading from socket...
heartbeat [waited for 0.5087 secs]
heartbeat [waited for 0.5084 secs]
```

So, `heartbeat` is scheduled much less frequently than it should. I don't know if this is the intended behavior or a bug, but it certainly looks weird to me.

**Comment by jamadden** [comment]
What you're seeing is the behaviour described [here](http://www.gevent.org/gevent.html#sleeping):

> In the current implementation, a value of 0 (the default) means to yield execution to any other runnable greenlets, but this greenlet may be scheduled again before the event loop cycles (in an extreme case, a greenlet that repeatedly sleeps with 0 can prevent greenlets that are ready to do I/O from being scheduled for some (small) period of time); a value greater than 0, on the other hand, will delay running this greenlet until the next iteration of the loop.

The call to `time.sleep(0)` in `reader` only yields *within one iteration* of the event loop. If there are other greenlets that were ready to do IO (e.g., sockets to read or write from) or had their timers come up for that iteration of the loop, they would get a chance to run. This allows a truly CPU intensive, time critical, task to operate for a longer consecutive period of time without being arbitrarily rescheduled for a subsequent event loop iteration, while also allowing other ready IO to have a chance to process. 

The `heartbeat` process is waiting for a subsequent iteration of the event loop, when its timer fires, to run. When that happens and it is scheduled, the `sleep(0)` yields to it.

The ~0.5 second timing is explained by the fact that gevent will only allow the event loop to be blocked from iterating a set *count* of times; that count happens to be [1000](https://github.com/gevent/gevent/blob/master/src/gevent/_ffi/loop.py#L384), and `1000 x 0.0005 = 0.5`. The `reader` is highly deterministic in its behaviour and each time it blocks the event loop it blocks it for a set time. That's not often the case so the numbers don't usually add up like that. (Presumably the reason for a count instead of a timer is to minimize overhead; `time.time` or `time.get_clock` make operating system calls, and those are relatively expensive. Still, there may be some hybrid solution possible.)

If you change that `0` to something greater than `0`, the event loop will get a chance to cycle and you'll see something much like the output from eventlet. This adds overhead, of course, so the effective work done by `reader` for any given block of time would go down, but of course other newly-ready greenlets would get a chance to run more frequently.

These two modes are offered so that the programmer can tune the behaviour of the system for their own application. Sometimes you want to allow the event loop to cycle, sometimes you don't, and when the event loop cycles, you have no guarantee where in the scheduling order you'll be placed so a `time.sleep(0.0001)` could potentially turn out to be much longer. Could `sleep`  be even smarter? Possibly. But there's a balance to maintain between something that's easily explained and understandable, overhead, and fairness.🤷‍♂️ 

See also some of the comments in #1068 .

**Comment by antocuni** [comment]
Thank you for the fast response. I did read the documentation about `sleep`, but I didn't understand the exact implications: in particular, it was not clear (and maybe it isn't yet) what "one iteration of the event loop" means. Maybe expanding the documentation with an example could help to understand the implications.
So, if I understand it correctly: if I have a greenlet which repeatedly calls `time.sleep(0)`, such as in this case, the other greenlets will be scheduled only after 1000 calls. Is this correct?

> That's not often the case so the numbers don't usually add up like that. (Presumably the reason for a count instead of a timer is to minimize overhead; time.time or time.get_clock make operating system calls, and those are relatively expensive. Still, there may be some hybrid solution possible.)

the real-world example I started from is enough deterministic to cause this to be a problem. Basically what it does is:
1. read a large chunk of bytes
2. parse them into a (long) list of "lines"
3. every 100 parsed lines, `time.sleep(0)`

Since the parsing takes a while, this behavior causes a big latency in other greenlets. An obvious workaround would be to read smaller chunks of bytes, but this is suboptimal for other reasons of course.

> If you change that 0 to something greater than 0, the event loop will get a chance to cycle and you'll see something much like the output from eventlet. This adds overhead, of course, so the effective work done by reader for any given block of time would go down, but of course other newly-ready greenlets would get a chance to run more frequently.

I tried to put `time.sleep(0.0000000001)`, and now I get **another** weird behavior:
```
Reading from socket...
heartbeat [waited for 0.1006 secs]
heartbeat [waited for 0.1012 secs]
heartbeat [waited for 0.1015 secs]
heartbeat [waited for 0.1012 secs]
heartbeat [waited for 0.1016 secs]
heartbeat [waited for 0.1006 secs]
heartbeat [waited for 0.1006 secs]
heartbeat [waited for 0.1017 secs]
heartbeat [waited for 0.1009 secs]
heartbeat [waited for 0.1015 secs]
heartbeat [waited for 0.1012 secs]
heartbeat [waited for 0.1010 secs]
heartbeat [waited for 0.1016 secs]
heartbeat [waited for 0.1010 secs]
heartbeat [waited for 0.1014 secs]
heartbeat [waited for 0.1011 secs]
heartbeat [waited for 0.1017 secs]
heartbeat [waited for 0.1013 secs]
heartbeat [waited for 0.1015 secs]
heartbeat [waited for 0.1014 secs]
heartbeat [waited for 0.1017 secs]
heartbeat [waited for 0.1010 secs]
heartbeat [waited for 0.1015 secs]
heartbeat [waited for 0.1008 secs]
heartbeat [waited for 0.1009 secs]
heartbeat [waited for 0.1015 secs]
heartbeat [waited for 0.1005 secs]
heartbeat [waited for 0.1008 secs]
heartbeat [waited for 0.1012 secs]
heartbeat [waited for 0.1015 secs]
heartbeat [waited for 0.1013 secs]
heartbeat [waited for 0.1014 secs]
heartbeat [waited for 0.1013 secs]

Reading from socket...
...
```

Between one `recv()` and the next, it takes 30 heartbeats, i.e. ~3 seconds; 1 second is spent inside the busy loop, but where are the other 2 seconds spent? Is it possible that the overhead of going through the event loop is **so** high (~1 ms)?

**Comment by jamadden** [comment]
> So, if I understand it correctly: if I have a greenlet which repeatedly calls time.sleep(0), such as in this case, the other greenlets will be scheduled only after 1000 calls. Is this correct?

No. The event loop will be allowed to run---poll for IO and timers and thus wakeup blocked greenlets---only after 1000 calls. If there are already other greenlets ready to run (they signaled they were ready for IO or had a timer expire) `time.sleep(0)` would yield to them. In this example there are no other greenlets doing IO that are ready at the same time as `reader`, and `heartbeat` has a timer expire only every 0.1s.

> I tried to put time.sleep(0.0000000001), and now I get another weird behavior:

Yeah, that's part of what the discussion in #1068 is about. The operating system and the underlying libev library has a limit on how fine grained the timers it supports are.  On my Mac, the timer resolution (the limit of how low I can sleep in this example) appears to be around 1e-5s, but on my Raspbian Raspberry Pi, the limit is much higher at 1e-3 and I see the same strange behaviour you posted. If those limits are exceeded, the behaviour will seem strange.

You didn't say if you installed gevent from source, used a PyPI wheel, or installed the ubuntu package. If memory serves, some linux packagers build libev and gevent in a way that results in reduced timer resolution (and even the pypi wheel may have that problem because it's built on an old system). You might see if you get different results building gevent from source (`pip install --no-binary=gevent gevent` IIRC).

**Comment by antocuni** [comment]
> No. The event loop will be allowed to run---poll for IO and timers and thus wakeup blocked greenlets---only after 1000 calls. If there are already other greenlets ready to run (they signaled they were ready for IO or had a timer expire) time.sleep(0) would yield to them. In this example there are no other greenlets doing IO that are ready at the same time as reader, and heartbeat has a timer expire only every 0.1s.

you say that if a greenlet "had a timer expire" it would be allowed to run. But `heartbeat` **has** an expired timer, only it is scheduled much later.
In another example: if I had an external process which sends a byte over a socket every 0.1 seconds, and `heartbeat` doing `recv(1)` on that socket: would it be scheduled or not? Is "having a timer" the same as "waiting for I/O", or there is some subtle difference?

Originally, I installed gevent using pip, so I assume I was using the binary wheel; now I reinstalled it from source, but the behavior is the same

**Comment by jamadden** [comment]
> you say that if a greenlet "had a timer expire" it would be allowed to run. But heartbeat has an expired timer, only it is scheduled much later.

`heartbeat` did not have an expired timer when `reader` began running. In principle the timer expires at some point while `reader` is running, but that won't be noticed until the event loop is allowed to run. `reader` is blocking the event loop, although it is not blocking other ready greenlets. gevent only notices that greenlets become ready (stop blocking on IO or have a timer expire) when the event loop is allowed to run. So long as `reader` is preventing the loop from running, timers that elapse won't be noticed. After 1000  times, gevent forces the event loop to run, which is when the `heartbeat` timer is noticed.

> In another example: if I had an external process which sends a byte over a socket every 0.1 seconds, and heartbeat doing recv(1) on that socket: would it be scheduled or not? Is "having a timer" the same as "waiting for I/O", or there is some subtle difference?

For purposes of this example, it's the same. Both need the event loop to cycle to notice that anything has changed.

**Comment by antocuni** [comment]
> heartbeat did not have an expired timer when reader began running. In principle the timer expires at some point while reader is running, but that won't be noticed until the event loop is allowed to run. 

oh, I see. Basically, the from a high level point of view, we have two nested loops:

```python
while True: # outer loop
    ready_tasks = get_ready_tasks()
    for task in ready_tasks: # inner loop
        execute(task)
```
`time.sleep(0)` forces us to stay inside the inner loop (unless count==1000), while `time.sleep(0.000001)` breaks the inner loop and does a full cycle of the outer loop. If I understood it correctly, then now it's pretty clear what's going on.

Then I have two questions:
1. is there any way to "break the inner loop" **without** sleeping even a tiny amount of time? It sounds like a useful feature to me

2. from what you wrote above, it seems that `time.sleep(0)` takes a shortcut for performance reasons. While I understand that in some cases it is desirable, from some point of view it seems to trade correctness* for speed: wouldn't it be better to do the "right" thing by default and the "fast path" only when requested? Or, in case now it's too late to change the default behavior, it would be nice at least to have a way to configure `count` (and by setting `count=0`, we would basically get the behavior I describe).

*I agree that "correct" is an arbitrary definition here; but "keeping my greenlet waiting even if others are trying to yield control" does not look completely correct to me.

**Comment by arcivanov** [comment]
>  while time.sleep(0.000001) breaks the inner loop and does a full cycle of the outer loop

Except it doesn't if `0.000001` is smaller than loop/kernel time slice, which is loop-implementation dependent (libev vs libuv). As @jamadden said, libuv has a time slice of 1ms, which means the callback goes straight in.

I would reiterate my position that every loop implementation that is asked to wait for a shorter period of time than it knows is its minimally viable tick but still greater than zero, then it simply acts as if the user requested to wait for a single tick of the loop. This distinguishes zero from non-zero wait and produces a desired effect whether the wait is 0.001s or 0.000000001s.

**Comment by jamadden** [comment]
> Except it doesn't if 0.000001 is smaller than loop/kernel time slice, which is loop-implementation dependent (libev vs libuv).

Much more than loop implementation dependent, it's highly system dependent, not just operating system and its configuration but also hardware.

> I would reiterate my position that every loop implementation that is asked to wait for a shorter period of time than it knows is its minimally viable tick but still greater than zero, then it simply acts as if the user requested to wait for a single tick of the loop.

The only loop implementation that "knows" that is libuv, and that's exactly what it does. libev *doesn't* know that and it varies *highly* from system to system (and maybe run to run).

gevent has always just "passed the buck" to libev when it comes to timing. That allows experienced programmers to get the most out of their particular configuration. Introducing libuv changes that, at least for libuv.

**Comment by jamadden** [comment]
> time.sleep(0) forces us to stay inside the inner loop (unless count==1000), while time.sleep(0.000001) breaks the inner loop and does a full cycle of the outer loop. If I understood it correctly, then now it's pretty clear what's going on.

*In this example* that's how it appears to work because there's only one greenlet that's ready to run. If there were other ready greenlets, `time.sleep(non-zero)` would simply deschedule the calling greenlet and continue with the others. It doesn't "break" the loop...that would be awful, very little forward progress would even be made. This inner loop of running callbacks is how much of gevent works, including things like locks and queues and events that don't involve any IO or (necessarily) timers.

**Comment by arcivanov** [comment]
> The only loop implementation that "knows" that is libuv, and that's exactly what it does. libev doesn't know that and it varies highly from system to system (and maybe run to run).

I meant the gevent's implementation of the loop abstraction. Even if libev-proper doesn't know time resolution, gevent's libev loop shim may figure out/set minimal tick value and adjust wait times to be minimally viable before passing the value to libev itself. If libuv is using 1ms (which I think is waaaay too large, frankly, 0.1ms sounds much more appropriate) then libev-based implementation might have to normalize to that value regardless to provide consistency.

**Comment by antocuni** [comment]
> In this example that's how it appears to work because there's only one greenlet that's ready to run. If there were other ready greenlets, time.sleep(non-zero) would simply deschedule the calling greenlet and continue with the others. It doesn't "break" the loop...that would be awful, very little forward progress would even be made. This inner loop of running callbacks is how much of gevent works, including things like locks and queues and events that don't involve any IO or (necessarily) timers.

ok, got it, thanks. But my question remains: how do I force gevent to go to the outer loop **without** waiting?

**Comment by jamadden** [comment]
> ok, got it, thanks. But my question remains: how do I force gevent to go to the outer loop without waiting?

In general, you don't. Why would you want to stop all the other ready greenlets from running? (This is where we ask the thought-experiment ["what if everyone did that?"](https://blogs.msdn.microsoft.com/oldnewthing/20050607-00/?p=35413))

If you mean, "how do I yield this greenlet *to the next iteration of the event loop* without actually requesting a delay?" then the answer is "there is no way to do so using just monkey-patched standard library"; these are not concepts the standard library has. You can use the gevent API to accomplish that (specifically prepare or check watchers and even simply `run_callback`) but that requires an understanding of how event loops work and they have some limitations due to how the event loops work. Furthermore, you can *still* wind up blocking the event loop if you do that and "starve" other greenlets. 

It seems like you're searching for a way to implement preemptive multi-tasking with some sort of fairness guarantees. gevent can't do that because (aside from being cooperative in nature) gevent doesn't have a scheduler (#1072 is a baby-step in that direction but only barely) or a notion of priorities or deadlines. You could probably build some sort of special purpose scheduler for your particular algorithm that calculates acceptable delay values based on load, etc, or you could do what most people do: pick a number that feels right and adjust it based on experience 😄 Or, you might be better off putting your CPU intensive work into a separate thread on the threadpool, where the operating system *can* enforce fairness and priorities (or similar with subprocesses or an external work queue).

**Comment by antocuni** [comment]
> In general, you don't. Why would you want to stop all the other ready greenlets from running? (This is where we ask the thought-experiment "what if everyone did that?")
If you mean, "how do I yield this greenlet to the next iteration of the event loop without actually requesting a delay?" 

Yes, that's what I actually meant, sorry for having worded it badly.

> then the answer is "there is no way to do so using just monkey-patched standard library";

ok, then this becomes a feature request 😅. Since `time.sleep(0)` is a generally accepted pattern for saying "please yield control to other greenlets", it would be nice if the user would somehow be able to tweak the default behavior. I think that having the possibility to change `count = 1000` would be enough (you could set it to 0 and get the behavior I want, I suppose).

For more context: we have a number of systems: a couple of them are using `gevent`, but most are using `eventlet` and we are considering whether to switch. We have many common libraries which are shared between projects, and all of them use `time.sleep(0)` to yield control in a library-independent manner. So, using gevent-specific API is not directly possible.

I suppose I can workaround by writing something like this:
```python
	def mysleep(seconds=0):
		hub = gevent.get_hub()
		loop = hub.loop
		hub.wait(loop.timer(seconds))
```
and then possibly monkey-patch `time.sleep` by hand. Not very ideal, but it should work.
That's why I was looking for a more official solution 😊.
