### ISSUE TITLE
Gitter/Slack chatroom?

### ISSUE THREAD

**Issue by arcivanov** [gevent/gevent#1161]
Does it make sense to create/have one for quick Q&A?

**Comment by arcivanov** [comment]
I personally find Gitter is easier to deal with for low-intensity stuff.

**Comment by jamadden** [comment]
I would not use either. I'm occasionally in the IRC room that already exists, but I don't find any of those to be decent forums.

**Comment by arcivanov** [comment]
Any proposal for decent forums or just not a fan in general?

**Comment by jamadden** [comment]
I personally do not find "real time" communication channels well suited to reporting bugs or asking questions about using libraries. One line of text is not enough. Spend the time to formulate a complete question with supporting details, please, and I'll try to do likewise in my responses. It may not be immediate, but it's not expected to be.

Not to mention that I personally don't need the pressure of trying to keep up with Yet Another place where my time and attention are called on, especially if it's supposed to be real time. I already answer email when I wake up in the middle of the night too often as it is :)

There are philosophical arguments against the walled garden of something like Slack.

The one project I contribute to that tried to get gitter off the ground gave up because no one wanted to use it.

**Comment by arcivanov** [comment]
Understood, thanks! :)
