### ISSUE TITLE
From source build failing on Windows 32bit for Python 2.7, binary wheel missing

### ISSUE THREAD

**Issue by pkittenis** [gevent/gevent#1225]
* gevent version: 1.3.2.post0
* Python version: Python 2.7.15
* Operating System: Windows 2008 32bit, Visual Studio 9

### Description:

Binary wheel for Windows, Python 2.7, 32bit is missing. 

Installing from source fails with missing `sys/socket.h` on compiling c-ares.

Note that 32bit wheels for versions other than 2.7 do exist.

```
       Creating library build\temp.win32-2.7\Release\src/gevent/libev\corecext.lib and object build\temp.win32-2.7\Release\src/gevent/libev\corecext.exp
    building 'gevent.resolver.cares' extension
    creating build\temp.win32-2.7\Release\src\gevent\resolver
    creating build\temp.win32-2.7\Release\deps
    creating build\temp.win32-2.7\Release\deps\c-ares
    C:\Users\appveyor\AppData\Local\Programs\Common\Microsoft\Visual C++ for Python\9.0\VC\Bin\cl.exe /c /nologo /Ox /MD /W3 /GS- /DNDEBUG -DFD_SETSIZE=1024 -D_WIN32=1 -DCARES_STATICLIB= -DCARES_EMBED=1 -Ibuild\temp.win32-2.7\Release\c-ares -Isrc/gevent/resolver -Ic:\users\appveyor\appdata\local\temp\1\pip-install-ltwa9i\gevent\deps\c-ares -Ic:\python27\include -Ic:\python27\PC /Tcsrc/gevent/resolver/cares.c /Fobuild\temp.win32-2.7\Release\src/gevent/resolver/cares.obj
    cares.c
    c:\users\appveyor\appdata\local\temp\1\pip-install-ltwa9i\gevent\deps\c-ares\ares_build.h(86) : fatal error C1083: Cannot open include file: 'sys/socket.h': No such file or directory
    error: command 'C:\\Users\\appveyor\\AppData\\Local\\Programs\\Common\\Microsoft\\Visual C++ for Python\\9.0\\VC\\Bin\\cl.exe' failed with exit status 2
```

### What I've run:

```pip install -U gevent```

**Comment by jamadden** [comment]
Thanks for your report. The 2.7 32bit wheel *just* finished building and I uploaded it probably while you were creating this issue.

It's not clear to me why c-ares failed to build for you, it does build on our [Appveyor CI](https://ci.appveyor.com/project/denik/gevent/build/job/38fmrurnbli6fuj7#L625).

The c-ares extension is also optional, and the build is [supposed to continue without it if it fails](https://github.com/gevent/gevent/blob/master/setup.py#L418).

**Comment by pkittenis** [comment]
:) Was wondering if that was the case. Regarding the build failure, your builds are regenerating cython files on windows. sys/socket.h does not exist on windows and cython has define checks on windows to handle it but that requires running cythonize or similar on windows so it picks up the platform check. 

While my build also has cython installed, the gevent source distribution does not contain the cython source files so the C files were not re-generated.

I seem to recall something about multi-platform C files not being generated anymore. Does that mean the distributed C files were built on posix? That would explain the failure on windows.

**Comment by jamadden** [comment]
Cython shouldn't have anything to do with `sys/socket.h`. That's included by c-ares itself, not the Python extension code. 

The erroring file, `c-ares\ares_build.h` includes `sys/socket.h` when a certain define is set. On POSIX platforms, that file is generated by running the configure script. But on Windows, where the configure script doesn't run, that file is *supposed* [to be replaced](https://github.com/gevent/gevent/blob/master/_setupares.py#L60) with a generic file that sets up some guesses based on compiler builtin defines. For some reason that didn't happen here.

All of the sources necessary for `cythonize` to run are shipped in the gevent tarball. But nothing had changed since the .c files were generated, so nothing would be done by `cythonize` even if it was installed. 

It's true that we previously ran our own CPP-like processor over gevent's cython sources and then attempted to combine the results into a single .c file. This was needed because our cython sources used CPP macros. But that broke badly with newer versions of Cython. The solution was to remove all use of CPP macros from our cython sources. (Anything where we still needed macros was moved to generic .c files.)

**Comment by pkittenis** [comment]
I see, thank you. `cythonize` being run was the only difference I saw in the two builds so it stood out. 

And the optional c-ares build does not seem to be optional at least for pip installs - your build used setup.py directly. Those are different issues though, will see if they can be replicated separately.

Thank you for your help.

**Comment by jamadden** [comment]
pip simply runs `setup.py bdist_wheel` when given a source distribution (and if that fails it runs `setup.py install` IIRC). But you're right, the optional handling is not a tested code path, something could have broken in it.
