### ISSUE TITLE
Having a problem understanding how to use monkey patching.

### ISSUE THREAD

**Issue by DemGiran** [gevent/gevent#1249]
I have a few questions regarding monkey patching:

1) are there any downfalls for monkey patching your whole program?
2) Say I have a function that uses the socket module. Should I first type "import socket" and then
 " from gevent import monkey; monkey.patch_socket(); monkey.patch_dns()" or is the correct order the other way around?
3) If I call the function from another module, should I monkeypatch the parent module or the child module?
4) if instead of "import socket" I do "from gevent import socket" do I need to monkey patch at all?
5) how do I know if my monkey patching works? My program is working without monkey patching.. which makes me wonder how to check the effects of monkey patching when applied to socket.
6) If a module gets patched from one file and then gets repatched again from another file, would that introduce any potential problems?
7) Why in this example https://github.com/gevent/gevent/blob/master/examples/unixsocket_client.py monkey patching is not used at all?

**Comment by jamadden** [comment]
1. It depends on the program and libraries it uses. There are some rare compatibility issues especially with native extensions. You'll have to try.
2. It is clearly documented in multiple places that monkey patching should be done *first*. The very first executed lines of your program should be `from gevent import monkey; monkey.patch_all()`. (Generally avoid the individual patching functions.). Arrange for this to be at the top of the `__main__.py` or file containing the `if __name__ == '__main__':` block.
3. See (2)
4. It depends on the program. If you are in complete control of all the code and always and only use the gevent APIs and no third-party dependencies that import from the standard library, then no, you don't need to patch.
5. Under load, you will observe that you are only servicing one greenlet at a time---blocking operations will block instead of being cooperative. cf this series https://dev.nextthought.com/blog/2018/06/gevent-blocking-greenlets.html
6. If two calls to 'monkey.patch_all()' are made, the second call is a no-op. If the calls pass different keyword arguments you'll get a warning. Patching is cumulative.
7. I have no idea.
