### ISSUE TITLE
Question about NotImplementedError vs socket.gaierror usage within the dnspython resolver

### ISSUE THREAD

**Issue by corbinbs** [gevent/gevent#1258]
* gevent version:  1.3.4
* Python version: PyPy2 6.0.0 downloaded from https://bitbucket.org/pypy/pypy/downloads/pypy2-v6.0.0-linux64.tar.bz2
* Operating System: `ubuntu:16.04` Docker image

### Description:

Hello,

Thank you for the work to support `dnspython` as a gevent resolver option.
This is likely more of a question rather than an issue with the library.

I recently evaluated the dnspython resolver option for possible performance improvements in some systems that run with PyPy and gevent.   It did allow those projects to end up handling more transactions per second with just the change to the DNS resolver.  Some of those transactions include interactions with redis, elasticsearch, raw sockets, and other https requests (using `requests`).   All of that passed the fairly large test suite for the projects along with performance testing over a long period of run time.  The only thing preventing a production roll out of it for me is an error that popped up for a small bit of code that interacts with an LDAP system via `ldap3` ( https://github.com/cannatag/ldap3/ )
When that code fired, it resulted in this traceback when `GEVENT_RESOLVER="dnspython"` was set: 
```
  File "/usr/local/site-packages/ldap3/strategy/base.py", line 118, in open
    for candidate_address in self.connection.server.candidate_addresses():
  File "/usr/local/site-packages/ldap3/core/server.py", line 519, in candidate_addresses
    addresses = self.address_info[:]  # copy to avoid refreshing while searching candidates
  File "/usr/local/site-packages/ldap3/core/server.py", line 239, in address_info
    addresses = socket.getaddrinfo(self.host, self.port, socket.AF_UNSPEC, socket.SOCK_STREAM, socket.IPPROTO_TCP, socket.AI_ADDRCONFIG | socket.AI_V4MAPPED)
  File "/usr/local/site-packages/gevent/_socketcommon.py", line 196, in getaddrinfo
    return get_hub().resolver.getaddrinfo(host, port, family, socktype, proto, flags)
  File "/usr/local/site-packages/gevent/resolver/dnspython.py", line 628, in getaddrinfo
    return _getaddrinfo(host, port, family, socktype, proto, flags)
  File "/usr/local/site-packages/gevent/resolver/dnspython.py", line 135, in _getaddrinfo
    raise NotImplementedError
NotImplementedError
```

it looks like the `ldap3` library is expecting the possibility of hard times with DNS resolution here:
https://github.com/cannatag/ldap3/blob/85a3ce01a1c994b1742dd5de6c8fd8c883088c77/ldap3/core/server.py#L248
and then attempts to retry that later on at https://github.com/cannatag/ldap3/blob/85a3ce01a1c994b1742dd5de6c8fd8c883088c77/ldap3/core/server.py#L253 without any `flags`

since that code doesn't consider the possibility of a `NotImplementedError`, the retry bit never happened.    

it looks like other DNS resolvers/systems might end up raising up this trouble with flags as a `socket.gaierror`

My question is:   Should the dnspython resolver raise up this https://github.com/gevent/gevent/blob/master/src/gevent/resolver/dnspython.py#L134 as a `socket.gaierror` type similar to what happens down at https://github.com/gevent/gevent/blob/master/src/gevent/resolver/dnspython.py#L137 ?

Of course, this could also be resolved via a patch back to that block of code in `ldap3` using `socket.getaddrinfo` calls.   I just opted to start here in case other folks would like to use/try the dnspython resolver option and end up hitting a similar scenario with other libraries that may be in use for them.  

Thanks again

**Comment by corbinbs** [comment]
this could also end up linking back to https://github.com/rthalley/dnspython/pull/300
since there was a need to incorporate that without the bare except

**Comment by jamadden** [comment]
Thanks for the feedback about the dnspython resolver, it's much appreciated.

> Should the dnspython resolver raise up this https://github.com/gevent/gevent/blob/master/src/gevent/resolver/dnspython.py#L134 as a socket.gaierror type similar to what happens down at https://github.com/gevent/gevent/blob/master/src/gevent/resolver/dnspython.py#L137 ?

That's a good question. As you know from https://github.com/rthalley/dnspython/pull/300 , the main reason gevent even *has* `_getaddrinfo` is because of that bare except. As the gevent version is essentially a copy, I can't claim to be fully aware of all the choices behind the implementation of that function. It looks like [it's been raising NotImplementedError since its inception in 2011](https://github.com/rthalley/dnspython/commit/37884a38dd59f643862262df386c8971aeb0f70f). I couldn't [find any bugs or PRs](https://github.com/rthalley/dnspython/issues?utf8=✓&q=NotImplementedError) that have touched on it.

It could be that passing those flags is rare (hence the lack of reports---I would tend to guess that's the case, but I haven't checked), so a change here won't affect many uses. 

If it does raise `gaierror` the question to answer is "with what errno value"? The ldap code you pointed to doesn't check the errno, but possibly other code does. My system defines ` EAI_BADFLAGS`, which seems great but may be misleading. If such code was passing that combo of flags *and* checking for a particular errno, if we provide something unexpected...unexpected things might happen. Again, though, that seems rare. 

I wouldn't be averse to making a change here to raising an appropriate `gaierror`. Even if upstream never accepted such a change (but did fix the bare except) gevent could easily catch `NotImplementedError`, check the flags, and re-raise a `gaierror`.

I would suggest, though, first opening an issue with dnspython. Maybe someone there can speak with more authority about the effects of a change. After all, dnspython does provide its own monkey-patch API (`override_system_resolver`), so this does affect anyone that uses stock dnspython.

If there's no response there, then we can come back to making a change here.

**Comment by corbinbs** [comment]
thanks @jamadden !
I'll work on opening up an issue / question with dnspython to see if there are some other reasons for the use of `NotImplementedError`
