### ISSUE TITLE
gevent makes files in text mode ignore the text mode

### ISSUE THREAD

**Issue by wiggin15** [gevent/gevent#1282]
* gevent version: 1.3.6
* Python version: Python 2.7
* Operating System: Windows Server (tried multiple versions)

### Description:

With gevent 1.3.6, using gevent.monkey.patch_sys makes files that are opened in "text" mode behave like they are not actually in text mode. i.e. using open with "w" mode (not "wb") and writing "\n" should print "\r\n" in Windows, but instead prints "\n" when sys module is patched.

### What I've run:

Here is the test code:

```python
import gevent
print gevent.__version__
import gevent.monkey
gevent.monkey.patch_sys()

with open("test", "w") as f:
    f.write("\n")
with open("test", "rb") as f:
    print repr(f.read())
```

Since the file is first open in "text" mode, "\n" should translate to "\r\n" which we should see when re-opening the file in binary mode.
Without the gevent patching, I see "\r\n".
Here is the output with an *old* gevent (correct):
```
1.2.1
'\r\n'
```
And here is the output with latest gevent (bad):
```
1.3.6
'\n'
```

**Comment by jamadden** [comment]
`patch_sys()`  does only one thing: replace `sys.stdin`, `sys.stdout` and `sys.stderr` with `FileObjectThread` wrappers. I don't see how that can possibly have any impact on the results of `open`. 

Since you're using `sys.stdout` when you `print`, I wonder  if you're seeing a difference in the modes of `FileObjectThread` vs the native `sys.stdin`.

Note that `patch_sys` is considered dangerous and not recommended for most uses, and does nothing on Python 3.

**Comment by wiggin15** [comment]
It's not because of the print to stdout - "hexdump" on the resulting file "test" shows "0a0d" for the file without gevent and "0d" for the file with gevent monkey patching.
We got it somehow deep in our tests even without `patch_sys` and I couldn't figure out why - `patch_sys` was the smallest code sample I could come up with to demonstrate this. Digging deeper now I see that it is even stranger - apparently it happens with just instantiating "FileObjectThread": this has the same effect:

```python
from gevent.fileobject import FileObjectThread
with open("unrelated", "w") as f1:
     FileObjectThread(f1)

with open("test", "w") as f:
    f.write("\n")
with open("test", "rb") as f:
    print repr(f.read())
```
I'll try to dig deeper later. It is very strange.

**Comment by jamadden** [comment]
That *is* very strange! `FileObjectThread` does do some copying of methods around, but I can't see anywhere it would have an effect outside of itself and the object its wrapping. It never does anything with the types, for example. Between 1.2.1 and 1.3.6, I think `FileObjectThread` really only moved between files, I'm not remembering any substantial changes.

Do you see the same results with a newer Python?

I'll be very interested in what you come up with.

**Comment by wiggin15** [comment]
It's much simpler than I made it. This also reproduces the issue:

```python
from gevent.hub import get_hub
get_hub()

with open("test", "w") as f:
    f.write("\n")
with open("test", "rb") as f:
    print repr(f.read())
```

Using git bisect, the commit that caused this is this e9af901a7bf3fea365932728789921e99c51aac5 :/ so it goes pretty deep.

**Comment by wiggin15** [comment]
Could be related to https://github.com/libuv/libuv/issues/840?

**Comment by jamadden** [comment]
Good catch! That does look to be the problem.

**Comment by jamadden** [comment]
I checked out https://github.com/saghul/pyuv and https://github.com/MagicStack/uvloop looking for precedents for solving this. I didn't find anything in pyuv, and uvloop doesn't run on Windows, so this appears to be the first time it's come up.

Since we ship our own copy of libuv and don't support linking to an external copy, especially not on Windows, our simplest option may be to just patch the source.

**Comment by wiggin15** [comment]
Thank you @jamadden ! Your responses and resolutions are much appreciated.
