### ISSUE TITLE
Enabling monitor thread causes SystemError in tuple construction (Python bug 15108)

### ISSUE THREAD

**Issue by ulope** [gevent/gevent#1302]
* gevent version: `1.3.7`
* Python version: `Python 3.6.6` (CPython from python.org built through `pythonz` with `--framework` option enabled)
* Operating System: `macOS 10.14.1`

### Description:

When running with the monitor thread enabled constructing tuples in long blocking greenlets is likely to cause: 
```
SystemError: Objects/tupleobject.c:851: bad argument to internal function
```

This seems to be a manifestation of [Python bug 15108](https://bugs.python.org/issue15108).

In our application I've so far seen this being triggered by sqlite and deepcopy.

### What I've run:

Minimum example and traceback:
https://gist.github.com/ulope/db811b6cf853ff267f27e4295bc4739e

**Comment by jamadden** [comment]
Thanks for the report! Using your example I can produce the exception in 2.7 and 3.7, so I assume it spans all versions.

**Comment by jamadden** [comment]
The easy fix for this example is to move the loop over `gc.get_objects()` into code compiled by Cython. This works because unlike the interpreter, Cython doesn't drop the GIL during the loop, so no other code can run and see the inconsistent tuple state. (The tuple gains an extra reference during the loop, but it loses it once the loop completes.)

I don't think that's quite a general fix---according to the Python bug, sqlite drops the GIL while it's manipulating this tuple, so there's still the potential for it to escape and be visible to the Cython code. However, the Cython loop is more than 3 times faster than the non-compiled version, so at least the window gets very much narrower. Maybe that's good enough, practically speaking.
