### ISSUE TITLE
Monkey patching of existing RLock is broken under CPython3

### ISSUE THREAD

**Issue by olliemath** [gevent/gevent#1354]
* gevent version: 1.4.0
* Python version: CPython 3.7.0
* Operating System: Ubuntu 18.04

### Description:

This recently raised issue for Eventlet also applies to Gevent's monkey patching code: https://github.com/eventlet/eventlet/issues/546 That is, under Python3, this code https://github.com/gevent/gevent/blob/master/src/gevent/monkey.py#L485 fails to find and patch existing RLocks.

Here's an example of this:
```python
from __future__ import print_function
import threading
import gevent
from gevent import monkey

lock = threading.RLock()

monkey.patch_all()


def actor(name):
    have_lock = False
    while not have_lock:
        print(name + " trying to get lock")
        have_lock = lock.acquire(blocking=False)
        gevent.sleep()

    print(name + "1")
    gevent.sleep()
    lock.release()

    print(name + "2")


def main():
    ga = gevent.spawn(actor, "A")
    gb = gevent.spawn(actor, "B")
    gevent.sleep()
    ga.join()
    gb.join()

main()
```

Under python2.7 this works as expected with actor B waiting for the lock:
```
A trying to get lock
B trying to get lock
A1
B trying to get lock
A2
B trying to get lock
B1
B2
```
however under python3.7 it does not:
```
A trying to get lock
B trying to get lock
A1
B1
A2
B2
```

The python 3 behaviour is equivalent to the python 2 behaviour without monkey patching.

**Comment by drpoggi** [comment]
I'm not sure what the difference between 2 and 3 is that's causing it to work on one but not the other, but you need to do monkey patching as soon as possible. Try:
```
from __future__ import print_function
from gevent import monkey
monkey.patch_all()
import threading
import gevent

lock = threading.RLock()
```
That works in 3.7.

**Comment by drpoggi** [comment]
Monkey patching an existing RLock isn't supported. The documentation is clear that monkey patching needs to be done first, and if it isn't then unexpected things could happen. The fact that this worked on 2.7 was probably just luck.

**Comment by jamadden** [comment]
There *is* an attempt to find and adjust existing locks at monkey-patch time. Under Python 2, the main motivation for this had to do with the `logging` module; under Python 3, the main motivation is the locks taken during import; since monkey-patching is usually done at import time, this is important. Those have a different implementation and I believe that still works.

We are aware that the `CRLock` doesn't work with monkey-patching and can't be "fixed"; one of the things that monkey-patching does [is switch back to the pure-Python implementation](https://github.com/gevent/gevent/blob/master/src/gevent/threading.py#L211). But we have no way to do anything about pre-existing CRLock objects. That's one of the reasons we continue to stress the importance of monkey-patching ASAP.

I would understand if there is some documentation that needs clarified further.

**Comment by olliemath** [comment]
@drpoggi Yes monkey patching before any locks exist works (and I'd recommend that to callers that can do so). However, the bug remains: code which is intended to patch existing locks does not work.

The Py2/3 difference is explained in the linked Eventlet issue. In Py3, any existing RLock objects are not returned by `gc.get_objects()`.

One way forward is just to drop support for patching existing RLock objects. In which case I guess you'd want to remove the `_patch_existing_locks` function from monkey.py and state that it is no longer supported.

My guess is that it has been broken in Py3 for some time, so the number of people relying upon it is low.
