### ISSUE TITLE
Invalid switch into Greenlet

### ISSUE THREAD

**Issue by yucejun** [gevent/gevent#1384]
* gevent version: 1.4.0
* Python version: Python 3.7.0 (default, Nov 20 2018, 15:41:25)
* Operating System: centos-release-7-5.1804.5.el7.centos.x86_64
* sqlalchemy version: 1.3.2
* pymysql version: 0.9.3
* MariaDB version: 5.5.60
### Description:

I'm write a tcp server, which use gevent to handler client data, and use sqlalchemy+pymysql to deal with database mysql. There may thousands of client connects, my server obtain some data and then write to database. But my server report some exceptions and after run about one day, it stop works.

It report exception like this:
```
Apr 05 11:13:50  python3[2684]: ERROR file:pool.py [line:718] : Exception during reset or similar
Apr 05 11:13:50  python3[2684]: Traceback (most recent call last):
Apr 05 11:13:50  python3[2684]: File "/usr/local/lib/python3.7/site-packages/sqlalchemy/pool.py", line 709, in _finalize_fairy
Apr 05 11:13:50  python3[2684]: fairy._reset(pool)
Apr 05 11:13:50  python3[2684]: File "/usr/local/lib/python3.7/site-packages/sqlalchemy/pool.py", line 880, in _reset
Apr 05 11:13:50  python3[2684]: pool._dialect.do_rollback(self)
Apr 05 11:13:50  python3[2684]: File "/usr/local/lib/python3.7/site-packages/sqlalchemy/dialects/mysql/base.py", line 1805, in do_rollback
Apr 05 11:13:50  python3[2684]: dbapi_connection.rollback()
Apr 05 11:13:50  python3[2684]: File "/usr/local/lib/python3.7/site-packages/pymysql/connections.py", line 432, in rollback
Apr 05 11:13:50  python3[2684]: self._read_ok_packet()
Apr 05 11:13:50  python3[2684]: File "/usr/local/lib/python3.7/site-packages/pymysql/connections.py", line 396, in _read_ok_packet
Apr 05 11:13:50  python3[2684]: pkt = self._read_packet()
Apr 05 11:13:50  python3[2684]: File "/usr/local/lib/python3.7/site-packages/pymysql/connections.py", line 656, in _read_packet
Apr 05 11:13:50  python3[2684]: packet_header = self._read_bytes(4)
Apr 05 11:13:50  python3[2684]: File "/usr/local/lib/python3.7/site-packages/pymysql/connections.py", line 690, in _read_bytes
Apr 05 11:13:50  python3[2684]: data = self._rfile.read(num_bytes)
Apr 05 11:13:50  python3[2684]: File "/usr/local/lib/python3.7/socket.py", line 589, in readinto
Apr 05 11:13:50  python3[2684]: return self._sock.recv_into(b)
Apr 05 11:13:50  python3[2684]: File "/usr/local/lib/python3.7/site-packages/gevent/_socket3.py", line 433, in recv_into
Apr 05 11:13:50  python3[2684]: self._wait(self._read_event)
Apr 05 11:13:50  python3[2684]: File "src/gevent/_hub_primitives.py", line 265, in gevent.__hub_primitives.wait_on_socket
Apr 05 11:13:50  python3[2684]: File "src/gevent/_hub_primitives.py", line 266, in gevent.__hub_primitives.wait_on_socket
Apr 05 11:13:50  python3[2684]: File "src/gevent/_hub_primitives.py", line 252, in gevent.__hub_primitives._primitive_wait
Apr 05 11:13:50  python3[2684]: File "src/gevent/_hub_primitives.py", line 46, in gevent.__hub_primitives.WaitOperationsGreenlet.wait
Apr 05 11:13:50  python3[2684]: File "src/gevent/_hub_primitives.py", line 46, in gevent.__hub_primitives.WaitOperationsGreenlet.wait
Apr 05 11:13:50  python3[2684]: File "src/gevent/_hub_primitives.py", line 57, in gevent.__hub_primitives.WaitOperationsGreenlet.wait
Apr 05 11:13:50  python3[2684]: gevent.exceptions.InvalidSwitchError: Invalid switch into <Greenlet "Greenlet-0" at 0x7f5fa85959d8: <bound method CloudServer.RecvHandler of <__main__.CloudServer object at 0x7f5fa93df630>>(<gevent._socket3.socket object, fd=187, family=2, , ('39.153.178.203', 53047), <cloud.common.Cache.Cache object at 0x7f5fa93df668)>: <gevent._event.Event object at 0x7f5fa3275200> (expected <gevent.__waiter.Waiter object at 0x7f5fa33f8d68>)
```

My python code just like this:
```python
import gevent
from gevent import socket,monkey
monkey.patch_all()

def TcpServer(host='', port=gPort, dataHandler=None):
    sock = socket.socket(socket.AF_INET,socket.SOCK_STREAM)
    sock.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)
    sock.bind((host, port))

    sock.listen(ClientNum)
    while True:
        try:
            fd, addr = sock.accept()
            logging.info('addr %s, fd %s' % (str(addr), str(fd)))
            gevent.spawn(dataHandler, fd, addr)
        except Exception as e:
            fd.close()

mEngine = create_engine(
    "mysql+pymysql://%s:%s@%s:3306/%s?charset=utf8" % (gDbAccount, gDbPassword, ipAddr, dbName),
    poolclass=NullPool
)

def dataHandler(fd, addr):
    data = fd.recv()
    writeDb(data)
```

**Comment by edibusl** [comment]
It happens also to me.
Will be glad if someone knows how to resolve that.

- gevent: 1.3.7
- pymsql: 0.9.2
- sqlalchemy: 1.2.14
- python: 3.5

```2019-07-10 18:45:49,734 - sqlalchemy.pool.QueuePool - ERROR - Exception during reset or similar
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/geventhttpclient/connectionpool.py", line 133, in get_socket
    return self._socket_queue.get(block=False)
  File "src/gevent/queue.py", line 329, in gevent._queue.Queue.get
  File "src/gevent/queue.py", line 344, in gevent._queue.Queue.get
  File "src/gevent/queue.py", line 313, in gevent._queue.Queue.__get_or_peek
queue.Empty

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/sqlalchemy/pool.py", line 709, in _finalize_fairy
    fairy._reset(pool)
  File "/usr/local/lib/python3.5/site-packages/sqlalchemy/pool.py", line 880, in _reset
    pool._dialect.do_rollback(self)
  File "/usr/local/lib/python3.5/site-packages/sqlalchemy/dialects/mysql/base.py", line 1805, in do_rollback
    dbapi_connection.rollback()
  File "/usr/local/lib/python3.5/site-packages/pymysql/connections.py", line 432, in rollback
    self._read_ok_packet()
  File "/usr/local/lib/python3.5/site-packages/pymysql/connections.py", line 396, in _read_ok_packet
    pkt = self._read_packet()
  File "/usr/local/lib/python3.5/site-packages/pymysql/connections.py", line 656, in _read_packet
    packet_header = self._read_bytes(4)
  File "/usr/local/lib/python3.5/site-packages/pymysql/connections.py", line 690, in _read_bytes
    data = self._rfile.read(num_bytes)
  File "/usr/local/lib/python3.5/socket.py", line 576, in readinto
    return self._sock.recv_into(b)
  File "/usr/local/lib/python3.5/site-packages/gevent/_socket3.py", line 433, in recv_into
    self._wait(self._read_event)
  File "src/gevent/_hub_primitives.py", line 265, in gevent.__hub_primitives.wait_on_socket
  File "src/gevent/_hub_primitives.py", line 266, in gevent.__hub_primitives.wait_on_socket
  File "src/gevent/_hub_primitives.py", line 252, in gevent.__hub_primitives._primitive_wait
  File "src/gevent/_hub_primitives.py", line 46, in gevent.__hub_primitives.WaitOperationsGreenlet.wait
  File "src/gevent/_hub_primitives.py", line 46, in gevent.__hub_primitives.WaitOperationsGreenlet.wait
  File "src/gevent/_hub_primitives.py", line 57, in gevent.__hub_primitives.WaitOperationsGreenlet.wait
gevent.exceptions.InvalidSwitchError: Invalid switch into <greenlet.greenlet object at 0x7f6ade4f0340>: <gevent._event.AsyncResult object at 0x7f6ab44bd250> (expected <gevent.__waiter.Waiter object at 0x7f6ab4494408>)
```

**Comment by stephan-hof** [comment]
One possible reason (sorry this is just a thought, I'm not certain about it) could be the way how sqlalchemy connection pool works. They are using [weakref](https://docs.python.org/3/library/weakref.html).

As far as I know it is hard to predict when a weakref callback is called. The cyclic garbage collector could kick in at any point in time. 

So it could happen that cyclic garbage collection code is called by the 'hub greenlet'.
In that case the hub greenlet calls this `_finalize_fairy` which probably won't work.

**Comment by jamadden** [comment]
Apologies for the delayed response.

> One possible reason (sorry this is just a thought, I'm not certain about it) could be the way how sqlalchemy connection pool works. They are using weakref.

> As far as I know it is hard to predict when a weakref callback is called. The cyclic garbage collector could kick in at any point in time.

Yes, I think that's basically it. weakrefs are deterministic in CPython if there are no cycles involved, but as soon as you get a cycle going, they become far less deterministic, happening according to the allocation thresholds defined by [`gc.set_threshold`](https://docs.python.org/3/library/gc.html#gc.set_threshold).

The scenario that would lead to this is as follows:

Greenlet A is doing something — anything — that causes it to need to wait. It registers `getcurrent().switch` with some object (an Event or AsyncEvent in these two examples) and hands control over to the hub. But before the switch is complete...

At that time, the GC kicks in, frees a cycle, and invokes `_finalize_fairy`. This happens in the context of the current greenlet A, so when the socket being collected goes to wait, it *also* registers `Greenlet A.switch` as the resume point. There are now two switches back into the same greenlet registered, each expecting a different return value: `A <- Event; A <- socket`, but *the current stack of the greenlet* was captured running the socket finalizer during the GC.

Control eventually gets back to the hub, which goes around waking up ready objects. The `Event` or `AsyncEvent` object is ready, so it executes `Greenlet A.switch(Event)` and wakes up the *socket*'s stack, which gets a bad return value. Chaos ensues.

What to do about this? SQLAlchemy pools destroy this weakref when a pooled connection is returned, so it looks like this only happens if a connection was being leaked. That's bad for other reasons too, so the most important thing would be to audit the code base and be sure to always checkin connections and not allow them to leak.

A second thing to watch out for is cycles. Avoid them, or destroy them deterministically. That would make the weakref cleanup deterministic too, so the current greenlet wouldn't be in a strange state.

I hope this helps.

There hasn't been any other activity on this issue in quite a while, so I'm closing it. Feel free to re-open if there is additional information to add.
