### ISSUE TITLE
why gevent.idle() cause the execution sequence in reverse order

### ISSUE THREAD

**Issue by kaka19ace** [gevent/gevent#1421]
* gevent version:  1.3.5
* Python version: cPython 2.7.9 downloaded from python.org
* Operating System: Debian Linux 8.11 Linux 4.4.0-33 amd64"

### Description:
run same function at multi greenlet, 
each function has gevent.idle(), 
and the execution after gevent.idle() sequence  is in reverse order, and the priority param does not work.

### What I've run:
```python
from __future__ import print_function

import time
import gevent


def get_now_ms():
    return int(time.time()*1000)


def gen_test_func(num):
    def func():
        st = get_now_ms()
        # p = 100 - num # does not work
        p = 0
        print("start: num={} p={} st={}".format(num, p, st))
        gevent.idle(p)
        print("idle_end: num={} t={}".format(num, get_now_ms()))
        gevent.sleep(0.1)
        print ("end: num={}, cost={}".format(num, get_now_ms()-st))
    return func


def test_parallel():
    tasks = []
    for i in range(5):
        tasks.append(gevent.spawn(gen_test_func(i)  )  )
    gevent.joinall(tasks, timeout=5)
    print("")


if __name__ == "__main__":
    test_parallel()
```

the output always:
```text
start: num=0 p=100 st=1557927256678
start: num=1 p=99 st=1557927256678
start: num=2 p=98 st=1557927256678
start: num=3 p=97 st=1557927256678
start: num=4 p=96 st=1557927256678
idle_end: num=4 t=1557927256678
idle_end: num=3 t=1557927256678
idle_end: num=2 t=1557927256678
idle_end: num=1 t=1557927256678
idle_end: num=0 t=1557927256678
end: num=4, cost=100
end: num=3, cost=100
end: num=2, cost=100
end: num=1, cost=100
end: num=0, cost=100
```

**Comment by jamadden** [comment]
> and the execution after gevent.idle() sequence is in reverse order,

Correct.

libev documents that it runs callbacks in the reverse order of which they were started (see the [`bool ev_run (loop, int flags)` documentation](http://pod.tst.eu/http://cvs.schmorp.de/libev/ev.pod#WATCHER_PRIORITY_MODELS). (This is actually somewhat tricky to discover from the source: watchers are added to an array by appending them to the end of a type-specific array, then when `idle_reify` is called as part of the loop it feeds the necessary idle watchers to the `pendings` array starting at the first one and working forwards. Then `ev_invoke_pending` uses some inline `--count` arithmetic in its iteration to work across the `pendings` array *backwards.)

libuv doesn't document the actual order in which the same type of callback is run, but it so happens that for idle watchers, [libuv also runs them in LIFO order](https://github.com/libuv/libuv/issues/1728). That may change in the future. (This is easier to see in the source: newly started watchers are [put at the front](https://github.com/libuv/libuv/blob/v1.x/src/unix/loop-watcher.c#L32), and the queue is run [from front to back](https://github.com/libuv/libuv/blob/v1.x/src/unix/loop-watcher.c#L53).)

> and the priority param does not work.

The libuv backend doesn't support priorities at all (libuv natively doesn't do that, and gevent doesn't emulate it), so it's expected to be ignored.

The libev backend requires priorities to be in the range `EV_MINPRI` < priority < `EV_MAXPRI`. Those values vary depending on how libev was built, so it's not necessarily easy to use priorities generically. Usually `EV_MAXPRI` is 2, so all of these priorities were out of range and hence were capped to have the same value, meaning it's like no priority was given at all. (See `ev_set_priority` in [the documentation](http://pod.tst.eu/http://cvs.schmorp.de/libev/ev.pod).

Note also that libev groups idle watchers by priority and won't run them if there are other *types* of watchers (e.g., I/O) of higher priority in the loop. This is very different from what libuv does for idle watchers (since it doesn't have the concept of priorities.)

Perhaps its best to just ignore priorities.

**Comment by kaka19ace** [comment]
> > and the execution after gevent.idle() sequence is in reverse order,
> 
> Correct.
> 
> libev documents that it runs callbacks in the reverse order of which they were started (see the [`bool ev_run (loop, int flags)` documentation](http://pod.tst.eu/http://cvs.schmorp.de/libev/ev.pod#WATCHER_PRIORITY_MODELS). (This is actually somewhat tricky to discover from the source: watchers are added to an array by appending them to the end of a type-specific array, then when `idle_reify` is called as part of the loop it feeds the necessary idle watchers to the `pendings` array starting at the first one and working forwards. Then `ev_invoke_pending` uses some inline `--count` arithmetic in its iteration to work across the `pendings` array *backwards.)
> 
> libuv doesn't document the actual order in which the same type of callback is run, but it so happens that for idle watchers, [libuv also runs them in LIFO order](https://github.com/libuv/libuv/issues/1728). That may change in the future. (This is easier to see in the source: newly started watchers are [put at the front](https://github.com/libuv/libuv/blob/v1.x/src/unix/loop-watcher.c#L32), and the queue is run [from front to back](https://github.com/libuv/libuv/blob/v1.x/src/unix/loop-watcher.c#L53).)
> 
> > and the priority param does not work.
> 
> The libuv backend doesn't support priorities at all (libuv natively doesn't do that, and gevent doesn't emulate it), so it's expected to be ignored.
> 
> The libev backend requires priorities to be in the range `EV_MINPRI` < priority < `EV_MAXPRI`. Those values vary depending on how libev was built, so it's not necessarily easy to use priorities generically. Usually `EV_MAXPRI` is 2, so all of these priorities were out of range and hence were capped to have the same value, meaning it's like no priority was given at all. (See `ev_set_priority` in [the documentation](http://pod.tst.eu/http://cvs.schmorp.de/libev/ev.pod).
> 
> Note also that libev groups idle watchers by priority and won't run them if there are other _types_ of watchers (e.g., I/O) of higher priority in the loop. This is very different from what libuv does for idle watchers (since it doesn't have the concept of priorities.)
> 
> Perhaps its best to just ignore priorities.

thx for detail message :)
