### ISSUE TITLE
Greenlet.kill()  result in corrupted state ?

### ISSUE THREAD

**Issue by chaseSpace** [gevent/gevent#1452]
Hi, I am looking [doc](http://www.gevent.org/api/gevent.html#working-with-greenlets) of gevent,
But now I get a problem for desc of *kill()* mthod:  
**Caution Use care when killing greenlets. If they are not prepared for exceptions, this could result in corrupted state.**  
What is the mean of **If they are not prepared for exceptions** ? and then result in corrupted state, This desc scared me to use *kill()* method. Could you explain this for me ? 
Best wishes!

**Comment by chaseSpace** [comment]
Is the meaning of **corrupted state** unknown exception? Does it cause global exceptions and program corruption?

**Comment by jamadden** [comment]
It's not going to cause gevent to crash with a segfault or something like that, but whatever other effects it has depend on the code.

Suppose you have this code:
```python
def func(db_cursor):
   global_lock.acquire() # lock in the program
   db_cursor.execute('SELECT * FROM table FOR UPDATE') # Lock rows in the db, blocking all programs
    do_stuff_while_locked()
   db_cursor.execute('COMMIT') # Release DB locks
    global_lock.release()
```

If an exception is raised out of `do_stuff_while_locked`, the program state is corrupted: locks have been taken that will never be released. The next code that tries to acquire `global_lock` will hang forever.

Of course that exception doesn't have to be one raised by `kill`; it could just as easily be a `KeyboardInterrupt` caused by the user pressing Ctrl-C, or the result of a signal arriving. Now, clearly this code is poorly written. It is not "exception safe" let alone "asynchronous exception safe." Well-written code that is asynchronous exception safe shouldn't have any problems, but not all code was written with that in mind.

**Comment by chaseSpace** [comment]
Your answer is like a spring on my head.
