### ISSUE TITLE
No module named 'gevent.__hub_local

### ISSUE THREAD

**Issue by Eratosthenes** [gevent/gevent#1468]
* gevent version: 1.4.0
* Python version: Python 3.6.0 and Python 3.7.1
* Operating System:
NAME="CentOS Linux"
VERSION="7 (Core)"

### Description:

```
Python 3.6.0 (default, Jan 19 2017, 16:59:54)
[GCC 4.8.5 20150623 (Red Hat 4.8.5-11)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import gevent
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/code/env/lib/python3.7/site-packages/gevent/__init__.py", line 87, in <module>
    from gevent._hub_local import get_hub
  File "/code/env/lib/python3.7/site-packages/gevent/_hub_local.py", line 101, in <module>
    import_c_accel(globals(), 'gevent.__hub_local')
  File "/code/env/lib/python3.7/site-packages/gevent/_util.py", line 105, in import_c_accel
    mod = importlib.import_module(cname)
  File "/usr/lib64/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ModuleNotFoundError: No module named 'gevent.__hub_local'
```

### What I've run:

```
import gevent
```

I don't know why this is broken and I can't debug it. Please help.

**Comment by jamadden** [comment]
The first thing to do would be to run python with the `-v` flag so it shows you what it tries to import, and look at what it tries for `gevent.__hub_local`. On my system it looks like this:
```console
$ python -v -c 'import gevent' 2>&1 | grep hub_local
# /.../lib/python3.7/site-packages/gevent/__pycache__/_hub_local.cpython-37.pyc matches /.../lib/python3.7/site-packages/gevent/_hub_local.py
# code object from '/.../lib/python3.7/site-packages/gevent/__pycache__/_hub_local.cpython-37.pyc'
# extension module 'gevent.__hub_local' 
     loaded from '/...lib/python3.7/site-packages/gevent/__hub_local.cpython-37m-darwin.so'
# extension module 'gevent.__hub_local' 
     executed from '/.../lib/python3.7/site-packages/gevent/__hub_local.cpython-37m-darwin.so'
import 'gevent.__hub_local' # <_frozen_importlib_external.ExtensionFileLoader object at 0x103f5e1e0>
import 'gevent._hub_local' # <_frozen_importlib_external.SourceFileLoader object at 0x103db77e0>
# cleanup[2] removing gevent._hub_local
# cleanup[2] removing gevent.__hub_local
# destroy gevent._hub_local
# cleanup[3] wiping gevent.__hub_local
```

Those lines in my output about "extension module 'gevent.__hub_local' loaded from ... /__hub_local.cpython-37m-darwin.so'" show where it's finding `gevent.__hub_local`: A platform-specific dynamic shared library located right beside `gevent/__init__.py`.  The same should be true on any given linux system (only the name of the .so will differ slightly). 

If that .so doesn't exist on disk, something is wrong with the gevent installation. If that .so can't be loaded because of some dynamic linking issue (you may have to take a closer look at all of the output, not just the filtered output), something is wrong with the gevent installation or the environment.

**Comment by Eratosthenes** [comment]
Thank you jamadden. This problem was related to my local environment. There were two ways I found to resolve the issue. One was to clear out my PYTHONPATH, the other was to remove gevent from the site-packages directory where it was installed.

**Comment by nateimig18** [comment]
so whats that mean?
