### ISSUE TITLE
Why doesn't gevent provide functions to replace requests etc' in case one wants to avoid monkey patching?

### ISSUE THREAD

**Issue by uriva** [gevent/gevent#1474]
Essentially this question: https://stackoverflow.com/questions/58633378/why-doesnt-gevent-come-with-its-own-arsenal-of-functions-instead-of-monkey-pat?noredirect=1#comment103641315_58633378

**Comment by jamadden** [comment]
gevent typically provides green versions of the standard library functions that are more-or-less drop-in compatible (e.g., simply change `import socket` to `from gevent import socket`). 

If someone wants to ship a particular library that's had that change applied, they can, but that's not the purpose of gevent. It's as much work as we can handle right now just doing what we do, trying to vendor copies of everyone's favorite libraries would be completely impossible.

It's also possible to fiddle with `sys.modules` when doing imports to make `import socket` have the effect of `from gevent import socket` (gevent itself [does this internally](https://github.com/gevent/gevent/blob/master/src/gevent/_patcher.py#L105) ) but in order to get good results that's very application/library specific and not something I would try to do generally.

**Comment by uriva** [comment]
Sure, but if you have a simple project that only has your own calls using the stl requests, then it makes sense to use the green versions directly, doesn't it?

Also - shouldn't the docs illustrate these green versions exist and can be accessed directly?
