### ISSUE TITLE
TypeError: prepare watchers are not currently supported in libuv. If you need them, please contact the maintainers.

### ISSUE THREAD

**Issue by hackaugusto** [gevent/gevent#1515]
I'm trying to use `prepare`+`check` handlers to execute code around the event loop, but it seems the `libuv` wrapper doesn't current support it, any chances that this can be added?

I actually just want to know if I have CPU starvation, and the idea was to measure the time spent blocking on the polling backend. The approach I took was to install a `prepare` and `check` handler to get the time before and after the poll, this however doesn't work on `libev` because of the order in which the `check` watchers are executed (I tried to change the priority without success). I tried switching to libuv as a test, since the order of the `checker`s seems to be better defined in that library. Perhaps there is a better way of measuring the time spend waiting wait on the poll function?

Edit: I'm using the monitoring thread, the problem is that not a single thread is using the cpu for an extended period of time, so I want to check if the collection of all threads is, and measuring the time waiting on the poll backend was is a nice proxy for that.

**Comment by jamadden** [comment]
> any chances that this can be added?

It would have to be emulated in pure-Python because we can't use the libuv prepare watchers that exist (they're not safe in general). So it could be done, but it's a fair amount of work and it may not perform well.

(There is an escape hatch: The `prepare` class is defined in `libuv.watchers` and you can try to use it with the usual watcher pattern allocate/start/stop. If you don't do *anything* but check the time, you're *probably* safe. Stepping beyond that, especially using any gevent or greenlet APIs, could crash the process or just silently corrupt memory.)

>  Perhaps there is a better way of measuring the time spend waiting wait on the poll function?

Not that works with both event loops. In fact in libuv, I don't think it's possible to directly get that info *at all*: Polling for IO is mixed up with actually calling the IO callbacks (which is very different than libev); the lowest level C function around the syscall takes an arbitrary amount of time *after* the syscall returns. Also, libuv on all platforms, and any event loop on Windows, is always bounded in the amount of time it will sleep in a poll syscall (to .3s IIRC).

> I actually just want to know if I have CPU starvation

Have you tried using a profiler? A profiler, especially one that can profile native code in addition to Python code, ought to be able to answer that question. I've had very good luck getting an overall picture of a tree of gevent-based web servers (gunicorn) in production using https://pypi.org/project/py-spy/

**Comment by hackaugusto** [comment]
> Have you tried using a profiler?

I ended up writing a profiler based on `settrace` to get flamegraphs, nothing else worked with greenlets and python 3.7/3.8 (I will try py-spy, looks like a better solution, using settrace is extremely slow). The problem is that I have a single thread doing long-polling which must run every 20seconds, and I'm only interested on the reason why it didn't. It could either be because the IO long polling took longer than 20s or the thread didn't get a chance to run because of starvation. Profiling definitely helps to find what to optimized, but only when CPU is the issue, and because the profiler aggregates the data of the whole run I can't tell if only for the past 20s there was a CPU issue.

- Should I just give up on the event loop and try `perf` or some other system tool?
- Or maybe some scheduling prioritization?

**Comment by jamadden** [comment]
> Profiling definitely helps to find what to optimize, but only when CPU is the issue, and because the profiler aggregates the data of the whole run I can't tell if only for the past 20s there was a CPU issue.

You can watch py-spy in real time to see what's going on in a process so you don't have to worry about aggregation. And it's a sampling profiler, something that blocks in a syscall will show up like that.

> The problem is that I have a single thread doing long-polling which must run every 20seconds, and I'm only interested on the reason why it didn't.

gevent drops the GIL while it's in native code waiting for IO, so that won't prevent a different thread from running, and Python 3 is pretty fair about dividing time between threads (not so much Python 2). If you mean a different *greenlet* then it's possible that a timer could fire late, depending on what else is going on in your system. In an idle system timers are pretty accurate, but if you have lots of other greenlets doing lots of other tasks in callbacks which don't yield often it could be delayed by some amount. Adjusting the switch interval or reducing the amount of CPU work your other greenlets do between yielding might help.

I can't offer much more insight without knowing a lot more about your system than I'd care to :)

**Comment by hackaugusto** [comment]
> If you mean a different greenlet then it's possible that a timer could fire late

Yes, I meant a greenlet.

> In an idle system timers are pretty accurate, but if you have lots of other greenlets doing lots of other tasks in callbacks which don't yield often it could be delayed by some amount

Yep, that is exactly what I'm experiencing. The system works fine under low load, however it breaks under high stress.

Thanks for the answers, I will close the issue since I don't think there is much to do on the gevent side of things. I will try py-spy and see what I can get out of it.

**Comment by jamadden** [comment]
You don't mention what version of gevent that you're using. If you're below 1.5a3, you might try upgrading to that version. It's possible you could be experiencing one of the corner-cases of non-fair locking.
