### ISSUE TITLE
unable to kill  already running greenlets if we add extra greenlet to pool

### ISSUE THREAD

**Issue by Set4now** [gevent/gevent#1528]
We are  in process of a web development. and were thinking to use gevent pool killone method to kill greelets ( to accomplish an abort feature from UI).

What works:

```python
def long_task(i):
    time.sleep(5)
    send_msg('step3', {"nodename":i,"status":"completed"})
    time.sleep(5)
    send_msg('step4', {"nodename":i,"status":"failed"}) 
    time.sleep(5)
    send_msg('step5', {"nodename":i,"status":"failed"}) 
    print "I am finshed with all the stpes {}".format(i)


pool = Pool(4)
process_list = []
for i in node.split(','):
            p = Greenlet(long_task, i)
             process_list.append(p)
for p in process_list:
            pool.start(p)
pool.killone(process_list[0])
 ```

`pool.killone(process_list[0])` : if i want to kill the first greenlet  works (
Note `node.split` is coming from UI where user selects which nodes to abort.)
So if he selects 4 from the UI..which is equal to the already declared Pool(4)..all works fine..

What and when is not working?
if the user selects more than 4 nodes lets say 5 nodes from the UI dropdown,
pool(4) starts 4 greenlets as expected, but `pool.killone(process_list[0])` doesn't work any more.

So, if `pool.start` or `pool.add`  adds more greenlets than the pool size, This kill will not work.

Please suggest how to achieve this.

**Comment by jamadden** [comment]
If your pool has a maximum size of 4, it can never be tracking 5 greenlets. `Pool.start()` is a blocking method: it will only return when a greenlet has been successfully started. In this case, that means that there were three or fewer greenlets running in the pool. Attempting to start a fifth greenlet will block until an earlier greenlet has finished.

Your code appears to be trying to start 5 greenlets in a pool of size 4. The first 4 will be started, and then `pool.start(p)` will block waiting to be able to start a fifth greenlet (it can't start one because 4 are already running). When it eventually does return after starting the fifth greenlet, that means that one of the first four greenlets—most likely the very first greenlet—has finished and is no longer running. `Pool.killone()` does nothing to a greenlet that's already dead.

If you want to track an arbitrary number of greenlets, use a `Pool` with a size of `None` (the default) or a `Group`.

If you want to use a fixed number of worker greenlets to execute tasks and be able to kill unstarted tasks, consider having worker greenlets in a size-limited `Pool` reading tasks from a shared `gevent.queue.Queue`; to kill a task before it starts remove it from the `Queue` (to kill it after it starts you'll need to do something application-specific).
