### ISSUE TITLE
Support EPOLLEXCLUSIVE for epoll

### ISSUE THREAD

**Issue by rowillia** [gevent/gevent#1536]
In https://github.com/benoitc/gunicorn/pull/2266 @jamadden linked to a bunch of great articles, including https://blog.cloudflare.com/the-sad-state-of-linux-socket-balancing/ which mentioned using `EPOLLEXCLUSIVE` to avoid thundering herds for the `epoll-and-accept` model (linking to https://idea.popcount.org/2017-02-20-epoll-is-fundamentally-broken-12/ which explains more).

We have very real problems with thundering herds at the moment - our hosts aren't able to be as efficient as we would like in part because this - system calls are littered with `accept4(5, 0x7ffe4f1a9980, [110], SOCK_CLOEXEC) = -1 EAGAIN (Resource temporarily unavailable) <0.000085>`

From diving into the code it appears `libev` would need to support this (and doesn't at the moment) - what would it take to support this?  Would this help alleviate thundering herds?

**Comment by jamadden** [comment]
At the application level, beyond playing with `max_accept` the other easy thing to do is to be sure that the `SO_REUSEPORT` is set. Enabling that smoothed out our production loads quite a bit.
 
From what [the libev maintainer has said](http://lists.schmorp.de/pipermail/libev/2019q4/002841.html), [io_uring](https://lwn.net/Articles/810414/) is probably the future of libev on Linux, as soon as the kernel maintainers finish working the bugs out. The libev maintainer isn't much of a fan of epoll (or many other things, it seems) so I don't know what the chances are of landing anything special for that particular backend.

Perhaps you can try one of the alternate libev backends such as that one? You'll need the current master of gevent to make that possible. I don't know if you should expect any differences (almost certainly not) but it might be worth a try.

Even if gevent wanted to have a local patch to libev to enable something like that — and I have no idea what that would look like — its tricky because downstream packagers are usually opposed to letting gevent use its own included libraries and prefer to link gevent with their (usually old 😞) system libraries. So anyone who gets gevent from their distro would be out of luck.

My current long-term plan is to transition the default gevent loop over to libuv and away from libev. It's currently only the default on Windows, but you could try that instead (I doubt you'd see much difference, but I haven't looked into its behaviour in that area in awhile). One of the main benefits will be using more of the high-level interfaces libuv provides to manage connections, which could help things like this. Plus, the libuv maintainers are pretty responsive and accepting of patches in my experience.

**Comment by jamadden** [comment]
There hasn't been any activity on this issue in quite a while, so I'm closing it. Feel free to re-open if there is additional information to add.
