### ISSUE TITLE
c-ares hell

### ISSUE THREAD

**Issue by kiorky** [gevent/gevent#1565]
### Description:

Can we do something not to fatal error on custom CFLAGS.

Can we do something not to fatal errors triggered by users using custom CFLAGS.

Using CFLAGS on UNIX platforms to include custom directories is something very usual and that you may not prevent.

It seems that c-ares is already patched upstream, please see https://github.com/c-ares/c-ares/pull/236 (c-ares 1.16.0) and the solution may be to upgrade bundled c-ares ASAP to latest release.

cc @sebcorbin

**Comment by jamadden** [comment]
I'm aware that c-ares has an update available and will get to it in due time. 

However, the way c-ares handles things in 1.5 has been the same since [1.1](http://www.gevent.org/whatsnew_1_1.html#library-updates), over five years ago. The mitigations described there — use CPPFLAGS and not CFLAGS — continue to apply.

**Comment by kiorky** [comment]
Its breaking lot of builds relying on gevent, can you please reconsider the priority, thanks.

**Comment by kiorky** [comment]
Even more, Mitigation may not be appliable in all cases.

**Comment by kiorky** [comment]
(Even more, it's a bug upstream that is not fixed here...)

**Comment by kiorky** [comment]
If you do not want to go up to 1.16.0 now, can you at least cherry-pick the m4 macro related changes for builds gevent not to be broken ?
