### ISSUE TITLE
ThreadPoolExecutor add_done_callback executed before end of thread

### ISSUE THREAD

**Issue by johaven** [gevent/gevent#1591]
* gevent version: 1.4.0 / 1.5.0 / 20.x
* Python version: 3.7
* Operating System: Linux & OSX

### Description:

ThreadpoolExecutor callback should be called at the end of task.

``` python
from gevent import monkey
monkey.patch_all()
# uncomment lines above to get the standard behaviour
import os
from concurrent.futures import ThreadPoolExecutor

executor = ThreadPoolExecutor(2)


def done(fn):
    if fn.cancelled():
        print(f'{fn.arg}: canceled')
    elif fn.done():
        error = fn.exception()
        if error:
            print(f'task: error returned: {error}')
            fn.result()
        else:
            result = fn.result()
            print(f'task - {result} is done')


def run(fn, *args, **kwargs):
    f = executor.submit(fn, *args, **kwargs)
    f.add_done_callback(done)
    print(f'{fn} is started')


def a_func():
    os.system('ls -lR / > /dev/null')


if __name__ == '__main__':
    run(a_func)
```
**Standard behaviour**
```
<function a_func at 0x1004c29e0> is started
task - None is done
```

**Gevent (monkey.patch_all()) behaviour**
```
task - None is done
<function a_func at 0x10480be60> is started
```

**Comment by jamadden** [comment]
Thank you for the report. But I can't run the example or produce that output (lots of things are missing). Can you please make it self-contained?

**Comment by johaven** [comment]
Sorry, i updated my example :)

**Comment by jamadden** [comment]
> i think it's a context switch problem.

I think it's a result of relying on undefined behaviour, combined with confusing logging.

```python
    f = executor.submit(fn, *args, **kwargs)
    f.add_done_callback(done)
    print(f'{fn} is started')
```

The final line is not necessarily correct, and may be actively confusing. The task hasn't necessarily been started, it's just been submitted to the executor. Depending on the implementation of the threadpool and the interpreter, and how busy the threadpool is, and how the operating system is scheduling threads, etc, the function may or may not have had any chance to execute yet, and it may even be completely finished.

All three lines lines contain race conditions. They race with the execution of `a_func`. All you can say about them and `a_func` is that `done` will be called after `a_func` has finished executing. In exactly what order `a_func`, `add_done_callback`, and `print` happen to execute is anyone's guess. 

Now, CPython will drop the GIL during `os.system` so there's a good chance that execution will look like this *if* the threadpool is able to begin execution of `submit` immediately:
```
f = executor.submit(fn) # Thread 1
os.system('something that runs for awhile') # Thread 2
f.add_done_callback(done) # Thread 1
os.system('something that runs for awhile') -> done # Thread 2
done() # Thread 1
```

Change that `os.system` to anything else, say, `pass`, and you likely get very different results. Of course, none of that applies to gevent: `os.system` isn't something that gevent can monkey-patch and it doesn't otherwise switch greenlets, so there's no chance to interleave operations.

Here's a version that's tweaked to show exactly when `a_func` enters and exits, and the individual steps of `run`. I get the same results under it with both gevent and native threads if `a_func` is deterministic:
```python
import os
CALL_SYSTEM = os.getenv("CALL_SYSTEM")
if os.getenv('GEVENT'):
    from gevent import monkey
    monkey.patch_all()
    print("Monkey-patched")
else:
    print("Native threads")

from concurrent.futures import ThreadPoolExecutor

executor = ThreadPoolExecutor(2)


def done(fn):
    print("1: Done callback", fn)

def run(fn, *args, **kwargs):
    print("1: Submitting function", fn)
    future = executor.submit(fn, *args, **kwargs)
    print("1: Submitted future", future, "; adding callback")
    future.add_done_callback(done)
    print("1: Added callback to future", future)

def a_func():
    print("2: Function is running")
    if CALL_SYSTEM:
        print("2: Calling system")
        os.system('ls / > /dev/null')
    print("2: Function is completed")

if __name__ == '__main__':
    run(a_func)
```

```console
$ python /tmp/issue1592.py
Native threads
1: Submitting function <function a_func at 0x106034f50>
2: Function is running
2: Function is completed
1: Submitted future <Future at 0x105f6c780 state=running> ; adding callback
1: Done callback <Future at 0x105f6c780 state=finished returned NoneType>
1: Added callback to future <Future at 0x105f6c780 state=finished returned NoneType>
$ GEVENT=1 python /tmp/issue1592.py
Monkey-patched
1: Submitting function <function a_func at 0x1062a2690>
2: Function is running
2: Function is completed
1: Submitted future <Future at 0x10629faa0 state=finished returned NoneType> ; adding callback
1: Done callback <Future at 0x10629faa0 state=finished returned NoneType>
1: Added callback to future <Future at 0x10629faa0 state=finished returned NoneType>
```

If we let CPython drop the GIL and interleave threads, we we see that it does so:
```console
$ CALL_SYSTEM=1 python /tmp/issue1592.py
Native threads
1: Submitting function <function a_func at 0x10feebf50>
2: Function is running
2: Calling system
1: Submitted future <Future at 0x10fe125f0 state=running> ; adding callback
1: Added callback to future <Future at 0x10fe125f0 state=running>
2: Function is completed
1: Done callback <Future at 0x10fe125f0 state=finished returned NoneType>
```

But again, that's not something gevent can do; once the function begins running, everything waits for it (and once control switches back to the main greenlet, there's nowhere else to go, so those proceed in order also):
```console
$ GEVENT=1 CALL_SYSTEM=1 python /tmp/issue1592.py
Monkey-patched
1: Submitting function <function a_func at 0x110e1e690>
2: Function is running
2: Calling system
2: Function is completed
1: Submitted future <Future at 0x110e1ba50 state=finished returned NoneType> ; adding callback
1: Done callback <Future at 0x110e1ba50 state=finished returned NoneType>
1: Added callback to future <Future at 0x110e1ba50 state=finished returned NoneType>
```

Using `time.sleep` or anything else that's monkey-patched will make the two behave more similarly again.

**Comment by johaven** [comment]
Thank you for explanation, i did tests with redis (setting a value during the different phases) and you are right, it becomes very hasardous depending on the executions.

**Comment by johaven** [comment]
Just a simple question, i use this threadpoolexecutor to start tasks that will zip multiples files on fs (from zipFile python module).

Before gevent, this kind of call was not blocking, i know gevent is not very designed to support I/O disk intensive, but is there a way to avoid this kind of situation ?
