### ISSUE TITLE
Connection reset by peer which connection sent from flask internal

### ISSUE THREAD

**Issue by CaichaoGitHub** [gevent/gevent#1593]
* gevent version: 1.4.0 
* Python version: Please be as specific as possible: "Python 3.7 "
* Operating System: Please be as specific as possible: "MAC OS"

### Description:

i want to send a request from Flask while it launched by gunicorn with gevent
however after i sent request from flask , it was reseted
and i met the execption Connection reset by peer

**Here is my Server code**
<img width="652" alt="截屏2020-04-29下午8 35 42" src="https://user-images.githubusercontent.com/12059897/80596689-5752fb80-8a59-11ea-9d20-500163f81ba0.png">

**ClientCode**
<img width="561" alt="截屏2020-04-29下午8 36 22" src="https://user-images.githubusercontent.com/12059897/80596715-633ebd80-8a59-11ea-9712-760ef2c9e9d0.png">

**Comment by jamadden** [comment]
Please do not post screenshots of code. Always post the actual code as text.

There's nothing I can do with those screenshots. You'll need to provide a [short, self-contained (that is, not using gunicorn or flask) example](http://sscce.org) that demonstrates what you think the problem is.

However, I will note that your `ClientWithTimeout` function is quite strange; I've never seen that done before and it's certainly not tested with gevent, so I don't know how that will interact. I would recommend using a Timeout object if you only want to set a timeout for a particular operation.

Also, I don't know whether `multiprocessing.connection` works with gevent either. The only thing from multiprocessing that's tested is `Process`, and `multiprocessing.connection` uses functions implemented in C that are not monkey-patched so it may hang or block non-cooperatively.

**Comment by CaichaoGitHub** [comment]
> Please do not post screenshots of code. Always post the actual code as text.
> 
> There's nothing I can do with those screenshots. You'll need to provide a [short, self-contained (that is, not using gunicorn or flask) example](http://sscce.org) that demonstrates what you think the problem is.
> 
> However, I will note that your `ClientWithTimeout` function is quite strange; I've never seen that done before and it's certainly not tested with gevent, so I don't know how that will interact. I would recommend using a Timeout object if you only want to set a timeout for a particular operation.
> 
> Also, I don't know whether `multiprocessing.connection` works with gevent either. The only thing from multiprocessing that's tested is `Process`, and `multiprocessing.connection` uses functions implemented in C that are not monkey-patched so it may hang or block non-cooperatively.

thanks for replay ,  i gave up multiprocessing, instead , i used a http server to solve the problem
,
