### ISSUE TITLE
Compatibility with python-firestore

### ISSUE THREAD

**Issue by leodaher** [gevent/gevent#1615]
* gevent version: 1.5a4
* Python version: 3.8.1 installed using `pyenv`
* Operating System: macOS Catalina (10.15.3)

### Description:

I need to use the realtime snapshot available from Firestore, and in my application, I am trying to use it inside a Gevent Greenlet, but it does not work as expected. Here's a sample script:

```python
import gevent
import time

import firebase_admin
from firebase_admin import credentials
from firebase_admin import firestore

key = "/path/to/serviceAccountCredentials.json"

def listen():
    cred = credentials.Certificate(key)
    firebase_admin.initialize_app(cred)
    db = firestore.client()

    def callback(doc_snapshot, changes, read_time):
        print("Received changes")

    db.collection('orders').on_snapshot(callback)

    while True:
        pass

if __name__ == '__main__':
    gevent.spawn(listen)
    while True:
        pass
```

If I make any changes to the `orders` collection, nothing is printed in the stdout. Now, if I change the last lines of the script so it doesn't run inside Gevent, it works as expected:

```python
if __name__ == '__main__':
    listen()
```

The `google-cloud-firestore` version I'm using is 1.6.2

**Comment by jamadden** [comment]
The loop:

```python
while True:
    pass
```

simply doesn't work with gevent. It monopolizes the CPU and doesn't let gevent (or any other greenlets) run at all. (See the gevent documentation about being cooperative with the event loop.) You could write

```python
glet = gevent.spawn(listen)
glet.join()
```

but since you're not doing anything else in the main greenlet (like serving connections or spawning other greenlets) there's not much point, that's really no different than simply doing `listen()`.

That aside, while I don't know anything about this library, unless it documents otherwise, it's unlikely that it somehow detects the presence of gevent and decides to use it. To make it cooperate with the event loop, at the minimum you'll need to monkey-patch the process as the first thing you do (`from gevent import monkey; monkey.patch_all()`), but depending on how the library is implemented, that might not do the trick (e.g., if it has C extensions).

**Comment by jamadden** [comment]
Closing; no updates since May.

**Comment by tseaver** [comment]
Just for clarification:  the `on_snapshot` method of a Firestore collection (or query, or document) spawns a thread which sets up a BIDI stream, over which the Firestore server pushes update snapshots.  The return value is a `Watch` instance:  it processes those snapshots and pushes the result into the callback.
