### ISSUE TITLE
install for gevent ... error, UserWarning: Unknown distribution option: 'project_urls'

### ISSUE THREAD

**Issue by slrslr** [gevent/gevent#1646]
* gevent version: gevent-20.6.2 (?)
* Python version: 3.5.3-1 (from official debian 9 repo using apt)
* Operating System: Debian 9 (stretch) openvz kernel 2.6.32-042stab138.1

### Description:

I tried to install gevent using "python3 -m pip install" and it failed with error code -9 and also shown "UserWarning: Unknown distribution option: 'project_urls'"
Original issue on pip repository here: https://github.com/pypa/pip/issues/8449 . It contains the link to full commands done and its output.
If something is needed, note that i am an inexperienced user. Thank You

**Comment by jamadden** [comment]
> "UserWarning: Unknown distribution option: 'project_urls'"

This means that your version of `setuptools`, and mostly likely `pip` as well, is too old. You should update them. Normally, that's also done with pip. Note that you probably don't want to overwrite the versions included with your Linux distribution, so you should use either pip's `—user` option for this, or you should be working in a virtual environment.

With a modern version of pip, you may be able to install the pre-compiled binary wheels that gevent distributes. This is much faster than compiling gevent from source (the `.tar.gz` file that you're downloading and installing now). More information is [on gevent's website](http://www.gevent.org/install.html#id1).

>  it failed with error code -9

That means the process was killed with signal number 9, which should be `SIGKILL` — something specifically killed the process. Since you're on a virtual machine with only 512MB, I'd guess it's the Linux kernel out-of-memory killer killing the process to regain memory. Try allocating more memory to the VM if you can't update pip to use binary wheels.

Good luck.

**Comment by slrslr** [comment]
> your version of `setuptools`, and mostly likely `pip` as well, is too old. You should update them.

$ python3 -m pip --version
`pip 9.0.1 from /usr/lib/python3/dist-packages (python 3.5)`

apt: "python3-pip is already the newest version (9.0.1-2+deb9u1)."

$ easy_install --version
`-bash: easy_install: command not found`

$ apt-cache show *setuptools*
```
Package: python3-setuptools
Source: python-setuptools
Version: 33.1.1-1
```

$ sudo pip3 install gevent
```
Collecting gevent
Requirement already satisfied: greenlet>=0.4.16 in /usr/local/lib/python3.5/dist-packages (from gevent)
Requirement already satisfied: cffi>=1.12.2 in /usr/local/lib/python3.5/dist-packages (from gevent)
Requirement already satisfied: zope.interface in /usr/local/lib/python3.5/dist-packages (from gevent)
Requirement already satisfied: setuptools in /usr/lib/python3/dist-packages (from gevent)
Requirement already satisfied: zope.event in /usr/local/lib/python3.5/dist-packages (from gevent)
Requirement already satisfied: pycparser in /usr/local/lib/python3.5/dist-packages (from cffi>=1.12.2->gevent)
Installing collected packages: gevent
Killed
```

i would update, but i do not know how, but that is offtopic.

> > it failed with error code -9
> Try allocating more memory to the VM if you can't update pip to use binary wheels.

i think that 512MB RAM and 512MB swap should be enough to install software like gevent

**Comment by jamadden** [comment]
> apt: "python3-pip is already the newest version (9.0.1-2+deb9u1)."

Debian ships notoriously out of date python modules and python versions. The current version of pip is 20.1.1. You need 19.x to install binary wheels. 

> i think that 512MB RAM and 512MB swap should be enough to install software like gevent

That's a nice sentiment. However, I can't do anything about it. I have absolutely no control over the process by the point its killed. It takes the resources it takes.

> sudo pip3 install gevent

Please use extreme caution using `sudo` to pip install things. It's generally not recommended to use pip as root outside a virtual environment or you could corrupt your python installation. Others have written extensively about this.

> i would update, but i do not know how, but that is offtopic.

No, that's the main topic. You need modern tools to install gevent binary wheels, otherwise you must compile and install from source.

Something like this should work:

First, make an isolated virtual environment, and activate it.
```console
$ python3 -m venv ./gevent-env
$ . ./gevent-env/bin/activate
```

Then update pip and setuptools:
```console
(gevent-env) $ python3 -m pip install -U pip setuptools
```

And last install the binary of gevent, failing if that's not possible:
```console
(gevent-env) $ python3 -m pip install —only-binary gevent gevent
```

**Comment by slrslr** [comment]
```
user@hr2:~$ python3 -m venv ./gevent-env
user@hr2:~$ . ./gevent-env/bin/activate
(gevent-env) user@hr2:~$ python3 -m pip install -U pip setuptools
Collecting pip
  Downloading https://files.pythonhosted.org/packages/longaddresshere/pip-20.1.1-py2.py3-none-any.whl (1.5MB)
    100% |################################| 1.5MB 555kB/s
Collecting setuptools
  Downloading https://files.pythonhosted.org/packages/longaddresshere/setuptools-47.3.1-py3-none-any.whl (582kB)
    100% |################################| 583kB 1.2MB/s
Installing collected packages: pip, setuptools
  Found existing installation: pip 9.0.1
    Uninstalling pip-9.0.1:
      Successfully uninstalled pip-9.0.1
  Found existing installation: setuptools 33.1.1
    Uninstalling setuptools-33.1.1:
      Successfully uninstalled setuptools-33.1.1
Successfully installed pip-20.1.1 setuptools-47.3.1
(gevent-env) user@hr2:~$ python3 -m pip install —only-binary gevent gevent
ERROR: Invalid requirement: '\udce2\udc80\udc94only-binary'

```

**Comment by jamadden** [comment]
It looks like you copied and pasted and got unicode characters. Use two dashes for the option.

**Comment by slrslr** [comment]
Thanks, Firefox copied some strange dash before the "only-binary". And when i manualy typed two dashes -- then it worked.
(python3 -m pip install --only-binary gevent gevent)
Yet was again killed:
```
(gevent-env) user@hr2:~$ python3 -m pip install --only-binary gevent gevent
Collecting gevent
  Using cached gevent-20.6.2-cp35-cp35m-manylinux2010_x86_64.whl (5.2 MB)
Requirement already satisfied: greenlet>=0.4.16; platform_python_implementation == "CPython" in ./gevent-env/lib/python3.5/site-packages (from gevent) (0.4.16)
Requirement already satisfied: zope.interface in ./gevent-env/lib/python3.5/site-packages (from gevent) (5.1.0)
Requirement already satisfied: setuptools in ./gevent-env/lib/python3.5/site-packages (from gevent) (47.3.1)
Requirement already satisfied: zope.event in ./gevent-env/lib/python3.5/site-packages (from gevent) (4.4)
Installing collected packages: gevent
Killed
(gevent-env) user@hr2:~$ free -mht
              total        used        free      shared  buff/cache   available
Mem:           512M         33M        472M         25M        6.0M        447M
Swap:          512M         30M        481M
Total:         1.0G         64M        953M

```

I am wondering how do i install gevent without using excessive amount of memory. Dou you know any already made tutorial on how to do it? I am Linux inexperienced user.

**Comment by jamadden** [comment]
When installing from a binary wheel, NO CODE from gevent is run. It's just pip unzipping a zip file and byte compiling python files found inside of it before moving everything into place. If you don't have enough memory to do that, it seems unlikely you'll have enough memory to run any application.

Since gevent isn't involved in that process at all, I don't see how I can help you any more.

**Comment by phcreery** [comment]
I managed to solve this same issue on my raspberry pi zero (even less memory) by using a compiled binary instead of pip.
`sudo apt-get install python-gevent`

```
pi@raspberrypi:~ $ free -mht
              total        used        free      shared  buff/cache   available
Mem:          432Mi        25Mi       249Mi       1.0Mi       157Mi       354Mi
Swap:          99Mi       8.0Mi        91Mi
Total:        532Mi        33Mi       341Mi
```
