### ISSUE TITLE
arm64 wheels

### ISSUE THREAD

**Issue by tsahee** [gevent/gevent#1673]
With the increase of Arm CPUs in datacenters and the upcoming Apple migration to Arm, the use of Python on these platforms is growing. However, installing Python modules without Wheels is often fails or it is very slow. The error messages users see are not clearly identifying the problem as missing build dependency. Publishing a Wheel is typically low effort, just a few lines in the build script. For users this saves significant time by avoiding troubleshooting and not having to wait for build processes to finish.

Arm64 whell building on travis.com is quite simple. I have created a pull request (https://github.com/gevent/gevent/pull/1672) which was closed without comments. Would be happy to discuss anything that needs to be changed and any way forward.

Thank you!
Tsahi.

**Comment by jamadden** [comment]
Thank you for your interest! 

I am not currently prepared to support binary wheels for arm64, primarily because we don't officially support "linux on 64-bit arm" at all. In the meantime, those that wish to use that platform will also need to build cutting edge versions of `greenlet`, `psutil`, `zope.interface`, `cffi`, etc, so the marginal advantage of publishing gevent is low, while the cost of supporting the platform is comparatively high. It's much more than just clicking a button to publish wheels; every platform that we support requires testing and…support, including making sure all our dependencies, starting with lib*v on up, also support the platform. 

Users are free to use such platforms, of course, and we'll do what we can to help with problems, but needing to build so many dependencies shouldn't deter such users.

No doubt gevent will get to the point where "linux on 64-bit arm" is a platform with enough demand that it should be officially supported, with all the burdens that entails. But I haven't seen evidence that convinces me we're at that point.

**Comment by tsahee** [comment]
Thank you!

There is a lot of work being done on getting wheel for arm64. Different wheels are in different stages, including cffi (https://github.com/python-cffi/cffi-travis-wheel/pull/1) greenlet (https://github.com/python-greenlet/greenlet/pull/176) psutil (https://github.com/giampaolo/psutil/issues/1782) and others. There is a chicken-and-egg situation: the more arm64 wheels will be available, the more users for python wheels on linux/arm64, and vice-versa. There is also a delay factor between PR merge and version/wheel issue, which is important to keep in mind.

Gevent is a great candidate for "early adopter" of arm64 since you already use travis.com and manylinux to publish wheels and test, making the required adjustments to arm64 minimal. My PR here failed on what seems like an unrelated test - but in my own fork I was quick to get the wheel building well on arm64: https://travis-ci.com/github/tsahee/gevent/jobs/385924723.

I am happy you agree linux on 64-bit arm binary wheel is in the future for gevent. Is there a specific test/wheel/etc you'd like to see pass on arm64, before moving forward with this?

**Comment by jamadden** [comment]
> making the required adjustments to arm64 minimal

That's missing the point. Building a wheel is not the same thing as supporting said wheels.

> Is there a specific test/wheel/etc you'd like to see pass on arm64, before moving forward with this?

I doubt it will be until sometime after I can drop a supported platform. As I said, I'm not anxious to add additional supported platforms because that increases the support burden. The most likely platform to fully drop support for will be 32-bit systems. I haven't looked at the download trends recently enough to hazard a guess as to when that will be. 

It may not be until I have direct access to arm64 hardware myself and can be comfortable supporting it.

**Comment by tsahee** [comment]
Thank you!

Two small comments:
Unless I'm missing something, the current travis script does not seem to create 32-bit wheels. The make-manylinux script always creates 64bit wheels, even when called from the 32-bit wheel generation job. I fixed it here: https://github.com/gevent/gevent/pull/1672/commits/0ccb11a6e9fd539b80b3bbb806f79e506d40727c, but then the 32-bit build failed due to a cython int overflow. I don't know when it was broken.

If you ever wish to put your hands on an arm64 system, the easiest way would probably be using AWS graviton instance. There is even a free trial until the end of 2020 on the smallest instance size (https://aws.amazon.com/about-aws/whats-new/2020/09/announcing-new-amazon-ec2-t4g-instances-powered-by-aws-graviton2-processors/)
