### ISSUE TITLE
gevent.subprocess.Popen: stdout.read returns with partial read

### ISSUE THREAD

**Issue by erickj00001** [gevent/gevent#1701]
* gevent version: 20.9.0
* Python version: Python 2.7.17 (default, Sep 30 2020, 13:38:04) [GCC 7.5.0] on linux2, installed from apt
* Operating System: Ubuntu 18.04.5 LTS (GNU/Linux 5.4.0-52-generic x86_64)

### Description:

When using `gevent.subprocess.Popen`, the `read` method on `stdout` should wait until the specified number of bytes have been read or it reaches EOF, to be consistent with the `read` method on any other file-like object.  Instead, it returns as soon as it has any data (i.e. more like the `recv` method for sockets).

The problem only occurs in Python 2.7, for gevent>=1.5.0.  It does not occur in Python 3 even with the latest gevent, and it does not occur in Python 2.7 with gevent==1.4.0.

### What I've run:

```python
from gevent import subprocess
# import subprocess
import unittest


class SubprocessReadTest(unittest.TestCase):
    def test_subprocess(self):
        proc = subprocess.Popen('echo hello ; sleep 2 ; echo world',
                                stdout=subprocess.PIPE, shell=True)
        data = proc.stdout.read(100000)
        self.assertEqual(data, b'hello\nworld\n')


if __name__ == '__main__':
    unittest.main()
```

This unit test fails for Python 2.7, gevent>=1.5.0: The `data` variable just receives the "hello\n" part, rather than waiting for 100000 bytes or EOF.  When using Python 3.7.5 *or* downgrading gevent to 1.4.0, it passes.  If you change it to just `import subprocess`, it also passes (even in Python 2.7).

**Comment by jamadden** [comment]
On Python 2, `Popen` does not buffer any data for `stdout` by default:

>  The default value for *bufsize* is 0 (unbuffered).

Prior to gevent 1.5, this was ignored and stdout/stderr were always buffered. 

Python 3 defaults to buffering. If you disable buffering by passing `bufsize=0` on plain Python 3, you'll see the same behaviour you're seeing here.

gevent's stdout/stderr objects are based on the `io` module; without buffering, a `read` call is supposed to only make a single system call (which here returns partial data).

CPython2 implements stdout/stderr as built-in `file` objects which have a number of platform specific behaviours (it's a trivial wrapper for the C function `fread`), and, even when buffering is disabled, they *will* make multiple system calls and buffer internally in `read`. Once again, this behaviour is changed in Python 3 (these are objects from the `io` module).

Instead of relying on implicit buffering inside `file.read`, I suggest being explicit and passing `bufsize=-1` to request the default buffering. This should work on all platforms and Python versions, with or without gevent.

**Comment by erickj00001** [comment]
Aha, that clears things up, thanks!  Setting `bufsize=-1` fixes this in my test case and also in the original script where I was having difficulties.

**Comment by jamadden** [comment]
Great!
