### ISSUE TITLE
PyPy3.6 install failed on libev 

### ISSUE THREAD

**Issue by qluo1** [gevent/gevent#1702]
* gevent version: 20.9.0
* Python version: pypy3.6
* Operating System: REL6

``` code
15:05 $ uname -a
Linux xxxx 2.6.32-754.31.1.el6.x86_64 #1 SMP Mon Jun 15 08:08:31 EDT 2020 x86_64 x86_64 x86_64 GNU/Linux
```

### Description:
```code
/local/data/home/gevent-20.9.0/deps/libev/ev.c:68:24: error: #if with no expression
 # if HAVE_CLOCK_GETTIME
                        ^
```
fixed with 
```code
# if defined(HAVE_CLOCK_GETTIME)
```

### What I've run:

pip install gevent

**Comment by jamadden** [comment]
I assume that by "REL6" you're referring to Red Hat Enterprise Linux 6. I understand that that went out of extended support in 2017, three years ago. 

gevent is built and tested with the [manylinux 2010 images](https://www.python.org/dev/peps/pep-0513/). Those are based on CentOS 6, which had maintenance updates up until November of this year. So we know that gevent can be properly built on a system of that vintage, as long as it is up to date. Notably, the compiler is gcc 8.3.1, significantly newer than what originally shipped back on 2010. Potentially other development headers have been updated as well, but all of the updates are from official repositories.

gevent just runs the `configure` script shipped with with libev, unchanged from upstream. libev itself is unchanged.

I can suggest two possibilities.

First, make sure your system is fully up to date and try again. Given a gevent directory (e.g., unpacked source tarball from PyPi or a git clone at the 20.9.0 tag) you ought to be able to simply `(cd deps/libev && ./configure && make)` to see if libev compiles. If it doesn't, the problem is somewhere in your development environment.

If that fails, you can always try to use a system-installed version of libev, as long as it is a recent libev. Install libev, then set the appropriate environment variables to cause gevent to use it before installing gevent.

More information on both options can be found at http://www.gevent.org/development/installing_from_source.html

If you try these things and have more to add, please feel free to open a new issue with the details.

Good luck!
