### ISSUE TITLE
Socket packages sent out of order

### ISSUE THREAD

**Issue by languitar** [gevent/gevent#1706]
* gevent version: 20.9.0
* Python version: Python 3.8.6, Archlinux package, also discovered on 3.8 running on k8s
* Operating System: Arch Linux 64 bit on Ryzen 1700

### Description:

When sending larger amounts of data using the (monkeypatched) gevent sockets, sometimes, data from individual `send` calls is mixed up and receives out of order.

### What I've run:

Here are two executable that can be used to reproduce (with some luck) the situation:

sender.py:
```python
from gevent import monkey
monkey.patch_all()
import gevent

import socket
import struct


chunk_size = 65000

def send():
    sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
    print(sock)
    sock.connect(('localhost', 3310))

    try:
        for _ in range(50000):
            sock.send(struct.pack("!L", chunk_size))
            sock.send(b'#' * chunk_size)

    finally:
        sock.close()


res = gevent.spawn(send)
res.get(True)
```

server.py
```python
import socket
import struct

sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)

server_address = ("localhost", 3310)
sock.bind(server_address)

sock.listen(1)

while True:
    connection, client_address = sock.accept()

    print(f"New client: {client_address}")

    while True:
        length_data = connection.recv(4)
        if len(length_data) != 4:
            print(f"Unexpected length data '{length_data}'. Terminating")
            break

        length, = struct.unpack("!L", length_data)
        print(f"New chunk length: {length}")

        if length > 70000:
            print("ERROR!!!")
            print(f"length: {length}, length_data: {length_data}")
            connection.close()
            break

        length_remaining = length
        chunk = b''
        while length_remaining > 0:
            local_chunk = connection.recv(length_remaining)
            length_remaining -= len(local_chunk)
            chunk += local_chunk

        if not chunk:
            print("Sending result")
            connection.sendall(b'foo: OK\n')
            connection.close()
            break
```

These two scripts implement a simple protocol, where the sender first sends a chunk size and then sends the specified amount of data. The server repeatedly reads first the chunk length and then the specified amount of binary data. So, to reproduce the issue, first start `server.py` and then repeatedly trigger `sender.py` until the `ERROR!!!` message appears in the server.

What happens here is that sometimes, instead of receiving the packed chunk size, the received four bytes for the length contain the payload data (repeated `#` characters). This indicates that data was sent out of order.

This does not happen with standard Python code. It also doesn't happen if tcpnodelay is activated on the sending side.

**Comment by jamadden** [comment]
Data is not sent out of order. However, this code contains bugs that explain the behaviour you're seeing.

```python
        for _ in range(50000):
            sock.send(struct.pack("!L", chunk_size))
            sock.send(b'#' * chunk_size)
```

I'll quote [the documentation for `socket.send`](https://docs.python.org/3/library/socket.html#socket.socket.send):

> Returns the number of bytes sent. Applications are responsible for checking that all data has been sent; if only some of the data was transmitted, the application needs to attempt delivery of the remaining data.

You can see in the example that the code is *not* checking to see how much data was actually sent and delivering the remainder. This is a bug in the code and will sometimes or often result in partial transmission. The circumstances under which partial transmission occurs depends on many things, including the operating system, whether you're using the loopback interface, the size of socket buffers, the configuration of the network, etc, etc. Because gevent uses non-blocking sockets, partial transmission is somewhat more likely, but it is *always* a possibility.

If you don't want to deal with partial transmission and redelivery yourself, then you need to use [`socket.sendall`](https://docs.python.org/3/library/socket.html#socket.socket.sendall). Again, this is valid for both standard library sockets and gevent sockets.

**Comment by languitar** [comment]
Thanks for the explanations and this extremely fast response. This is actually a reduced version of what pyclamd does when scanning a file via TCP. Then the bug is already present there and just sufficiently unlikely without gevent that no one noticed it so far.
