### ISSUE TITLE
Gevent made gunicorn blocked

### ISSUE THREAD

**Issue by CMGS** [gevent/gevent#173]
as we know, gevent support subprocess monkey patch now. but i found a strange problem when i use gunicorn with when ready function in configure file.

in my case, i have to spawn a monitor process after gunicorn ready  so i wrote config file like this

```python
def when_ready(server):
    """Gunicorn server ready hook
    """
    from subprocess import Popen
    # no matter what process i open
    p = Popen(['sleep', '90'], close_fds=True)
```

and then wrote the app.py like this

```python
from subprocess import *

def app(e, s):
    s('200 OK', [])
    p = Popen(['echo', 'abc'])
    print '*'*100
    #blocked
    print p.wait()
    return 'yw'
```

then i visit the url, i found that it seems something block the request. p.wait() can not return immediately and block the whole request! 

the execute command is 

```bash
gunicorn -k gevent -c config.py -b :9999 app:app --debug --log-level=debug
```

i test gevent 1.0b2, it seems ok, request will not be blocked, but when i upgrade to 1.0b3 or dev version, the problem appeared. 

could someone help me to solve this problem?

**Comment by jamadden** [comment]
Since gunicorn 19.0, [it has been explicitly patching subprocess](http://gunicorn-docs.readthedocs.org/en/latest/2014-news.html#gevent-worker) so the default here didn't matter. gevent 1.1 (current master) has switched back to patching subprocess by default as well and made several improvements to process integration. Please feel free to open another issue if you continue to have problems on these more recent versions.
