### ISSUE TITLE
Does socket.sendfile use sendifle(2)?

### ISSUE THREAD

**Issue by dsuch** [gevent/gevent#1738]
Hello,

I am just trying to understand one thing.

I am looking at the implementation of socket.sendfile in [socket._sendfile_use_send](https://github.com/gevent/gevent/blob/master/src/gevent/_socket3.py#L418) and as far as I can see, it does not use the kernel's sendfile(2) facility, is that right?

If I understand it correctly, the data to be sent is read in blocks from one file object and transferred to another file object immediately which means that there is transfer (copying) of bytes from the kernel to Python and then back to kernel? I can see a memoryview object is used but this overlays a Python object with data already read in to the Python process I believe? (I can also see a caveat about os.senfile's not being cooperative).

I am asking in the context of sending data from actual files from a disk to a TCP socket - the current implementation will copy bytes between files / sockets through Python objects, i.e. it will not use sendfile(2) - could you please confirm it?

Thanks a lot.

**Comment by jamadden** [comment]
That's correct, the implementation of `gevent.socket:socket.sendfile` does not use [`os.sendfile`](https://docs.python.org/3/library/os.html#os.sendfile).

As noted, `os.sendfile` is not cooperative with the event loop. Somewhat more importantly, though, gevent sockets are always in non-blocking mode as far as the kernel is concerned. This means that a call to `os.sendfile` would typically return almost immediately, having only filled the socket's send buffer. We would then have to make one or more trips around the event loop waiting for space to become available before repeating the process. The advantage of being able to do most of the work in a single kernel call would be lost. 

Now, such looping could be done, and in fact it has to be done anyway because even regular blocking sockets may still require multiple calls to `os.sendfile` to complete the job. But it would be much tighter loop, and there's a fair amount of extra overhead involved in that loop. Perhaps it is for this very reason that the standard library implementation of `socket.sendfile` actually refuses to operate on non-blocking sockets, or perhaps its because of platform differences in the interaction of `os.sendfile` with non-blocking socket, I don't know.

Given that, there didn't seem much advantage to trying to use `os.sendfile` with gevent's non-blocking sockets. The basic loop is already present for `socket.send`, so re-implementing it around `os.sendfile` would be extra work (we can't — don't want to — use the loop implementation that CPython's sockets use as its inefficient in this case). Yes, there's a bit of copying that might not have to occur otherwise, but the copies are in small chunks and the overhead, relative to everything else going on, was believed small, especially for busy applications.

Additionally, because `_sendfile_use_send` relies on the python-level `file.read()` operation, it works with gevent's non-blocking file objects as a source, including those that need to use the threadpool; that wouldn't work using `os.sendfile`.

**Comment by dsuch** [comment]
Hi Jason,

my apologies for a late reply - I thank you for what, as always, was a thorough and well thought out response. I did not appreciate all the intricacies of the call and now I do. Thank you again.
