### ISSUE TITLE
request.url returns a URL with respect to the 'Host' Header.

### ISSUE THREAD

**Issue by IngeniousCoder** [gevent/gevent#1740]
* gevent version: 20.9.0 by pip
* Python version: Py3.8.6 from Python website
* Operating System: Windows 10

### Description:
I own the domain ingeniousapps.net and this domain points to my server.
I do not own the domain phuocbds.com, however this domain also points to my server.

My webserver at is configured to only accept requests coming from the domain ingeiousapps.net.

-----------

By doing a simple request in python on http://phuocbds.com without forging headers, a 403 is returned.
```py
>>> r = requests.get("http://phuocbds.com")
>>> r
<Response [403]>
```
On my server, this is the relevant log entry.
```
User 101.78.81.213 -- [2021-01-05 15:23:30] GET http://phuocbds.com/ "HTTP/1.1" "python-requests/2.25.0" |403 FORBIDDEN -
```

--------------

By doing a simple request in python on http://phuocbds.com, with a forged Host header "ingeniousapps.net", a 200 is returned.
```py
>>> r = requests.get("http://phuocbds.com",headers={"Host":"ingeniousapps.net"})
>>> r
<Response [200]>
```
On my server, this is the relevant log entry.
```
User 101.78.81.213 -- [2021-01-05 15:24:43] GET http://ingeniousapps.net/ "HTTP/1.1" "python-requests/2.25.0" |200 OK -
```

-------------

Next, I attempt to do another request in python on http://phuocbds.com/apples, with a forged Host header 'ingeniousapps.net' again. This time, a 404 is returned, and it does make sense as there is no such url ingeniousapps.net/apples.
```py
>>> r = requests.get("http://phuocbds.com/apples",headers={"Host":"ingeniousapps.net"})
>>> r
<Response [404]>
```
However, the relevant log entry in my server shows something unexpected:
```
User 101.78.81.213 -- [2021-01-05 15:24:50] GET http://ingeniousapps.net/apples "HTTP/1.1" "python-requests/2.25.0" |404 NOT FOUND -
```
**Expected Behavior**
`request.url` should be "http://phuocbds.com/apples"  instead of "http://ingeniousapps.net/apples".

Expected Log : User 101.78.81.213 -- [2021-01-05 15:24:50] GET http://phuocbds.com/apples "HTTP/1.1" "python-requests/2.25.0" |404 NOT FOUND -

**Actual Behavior**
`request.url` is  "http://ingeniousapps.net/apples".
Actual Log : User 101.78.81.213 -- [2021-01-05 15:24:50] GET http://ingeniousapps.net/apples "HTTP/1.1" "python-requests/2.25.0" |404 NOT FOUND -

This should not be the case. 

This webserver is a flask webserver running on a gevent PyWSGI server.

**Comment by jamadden** [comment]
In short, I don't understand what this report has to do with gevent. I think you should suspect a bug in your environment or application framework (e.g., flask).

> request.url returns a URL

I don't know  what `request.url` is. Is that something provided by your application framework? It's not a part of gevent or WSGI. This is part of why I think you need to look elsewhere.

> My webserver at is configured to only accept requests...

That's not part of gevent either.

> gevent PyWSGI server.

Which of course is an implementation of [PEP 3333](https://www.python.org/dev/peps/pep-3333/); PEP 3333 specifies nothing about virtual hosting or handling of the `Host` header, other than [to provide an example](https://www.python.org/dev/peps/pep-3333/#url-reconstruction) of how an *application* (**not** the server!) might reconstruct a URL based on what WSGI does specify. (Note: There is a somewhat surprising part of that example when it comes to handling ports.)

Let's look at what `gevent.pywsgi` and the example for URL reconstruction do together.

First, in `wsgi_test.py` we'll define the function `pep3333_url_reconstruction` as a direct copy-and-paste from the WSGI specification:
```python
def pep3333_url_reconstruction(environ):
    from urllib.parse import quote
    url = environ['wsgi.url_scheme']+'://'

    if environ.get('HTTP_HOST'):
        url += environ['HTTP_HOST']
    else:
        url += environ['SERVER_NAME']

        if environ['wsgi.url_scheme'] == 'https':
            if environ['SERVER_PORT'] != '443':
                url += ':' + environ['SERVER_PORT']
        else:
            if environ['SERVER_PORT'] != '80':
                url += ':' + environ['SERVER_PORT']

    url += quote(environ.get('SCRIPT_NAME', ''))
    url += quote(environ.get('PATH_INFO', ''))
    if environ.get('QUERY_STRING'):
        url += '?' + environ['QUERY_STRING']
    return url
```

In that same file, we'll define a WSGI callable that uses this and prints some interesting information. (The WSGI callable is the only thing that PEP 3333 defines for the server to interact with Python code; note that there is no `request.url` here)

```python
def app(environ, start_response):
    url = pep3333_url_reconstruction(environ)
    body = f"""
    WSGI Application
    SERVER_NAME      :   {environ['SERVER_NAME']}
    SERVER_PORT      :   {environ['SERVER_PORT']}
    HTTP_HOST        :   {environ['HTTP_HOST']}
    Reconstructed URL:   {url}
    """

    start_response('200 OK', [('Content-Type', 'text/plain')])
    return [body.encode('utf-8')]
```

We'll start gevent's WSGI server using this file, listening only on localhost:
```console:
$ python -m gevent.pywsgi -b localhost:8080 wsgi_test:app &
[1] 75414
```

Last, we'll use curl to make some HTTP requests and show exactly what headers get sent in the request and the response. 

By default, curl uses HTTP 1.1 and generates a `Host` header based on the URL typed; the generated URL in the response exactly matches the expected value. (See that the `SERVER_NAME` is based on a reverse DNS lookup of what the listening socket is bound to, but a correct URL reconstruction doesn't use this.)
```console
$ curl -v http://localhost:8080
*   Trying 127.0.0.1:8080...
* Connected to localhost (127.0.0.1) port 8080 (#0)
> GET / HTTP/1.1
> Host: localhost:8080
> User-Agent: curl/7.74.0
> Accept: */*
>
127.0.0.1 - - [2021-01-07 07:40:33] "GET / HTTP/1.1" 200 295 0.000112
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< Content-Type: text/plain
< Date: Thu, 07 Jan 2021 13:40:33 GMT
< Content-Length: 192
<

    WSGI Application
    SERVER_NAME      :   1.0.0.127.in-addr.arpa
    SERVER_PORT      :   8080
    HTTP_HOST        :   localhost:8080
    Reconstructed URL:   http://localhost:8080/
* Connection #0 to host localhost left intact
```

If we explicitly pick a value for the `Host` header, the generated URL is again as expected (there is no port value in the response because there was none in the request header; this is the vaguely surprising bit because the `Host` header is actually also supposed to include the port).
```console
$ curl -v http://localhost:8080 -H "Host: foo"
*   Trying 127.0.0.1:8080...
* Connected to localhost (127.0.0.1) port 8080 (#0)
> GET / HTTP/1.1
> Host: foo
> User-Agent: curl/7.74.0
> Accept: */*
>
127.0.0.1 - - [2021-01-07 07:55:53] "GET / HTTP/1.1" 200 273 0.000093
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< Content-Type: text/plain
< Date: Thu, 07 Jan 2021 13:55:53 GMT
< Content-Length: 170
<

    WSGI Application
    SERVER_NAME      :   1.0.0.127.in-addr.arpa
    SERVER_PORT      :   8080
    HTTP_HOST        :   foo
    Reconstructed URL:   http://foo/
* Connection #0 to host localhost left intact
```

Following the specification that says that URL reconstruction should only use the `Host` header if it's there, then if we exclude that header, the URL reconstruction algorithm does its best to pick based on the discovered `SERVER_NAME`:
```console
$ curl -v http://localhost:8080 -H "Host: "
*   Trying 127.0.0.1:8080...
* Connected to localhost (127.0.0.1) port 8080 (#0)
> GET / HTTP/1.1
> Host:
> User-Agent: curl/7.74.0
> Accept: */*
>
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< Content-Type: text/plain
127.0.0.1 - - [2021-01-07 08:00:43] "GET / HTTP/1.1" 200 294 0.000193
< Date: Thu, 07 Jan 2021 14:00:43 GMT
< Content-Length: 191
<

    WSGI Application
    SERVER_NAME      :   1.0.0.127.in-addr.arpa
    SERVER_PORT      :   8080
    HTTP_HOST        :
    Reconstructed URL:   http://1.0.0.127.in-addr.arpa:8080/
* Connection #0 to host localhost left intact
```

Lastly, if I have `gevent.pywsgi` bind to all my available IP addresses, we can see how it discovers a different `SERVER_NAME`, but that's still only used in the absense of a `Host` header:
```console
$ fg
python -m gevent.pywsgi -b localhost:8080 wsgi_test:app
^CKeyboardInterrupt
…
KeyboardInterrupt
$ python -m gevent.pywsgi wsgi_test:app &
[1] 80809
$ curl -v http://localhost:8080
*   Trying 127.0.0.1:8080...
* Connected to localhost (127.0.0.1) port 8080 (#0)
> GET / HTTP/1.1
> Host: localhost:8080
> User-Agent: curl/7.74.0
> Accept: */*
>
127.0.0.1 - - [2021-01-07 08:03:16] "GET / HTTP/1.1" 200 288 0.000384
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< Content-Type: text/plain
< Date: Thu, 07 Jan 2021 14:03:16 GMT
< Content-Length: 185
<

    WSGI Application
    SERVER_NAME      :   platform.ou.edu
    SERVER_PORT      :   8080
    HTTP_HOST        :   localhost:8080
    Reconstructed URL:   http://localhost:8080/
* Connection #0 to host localhost left intact

$ curl -v http://localhost:8080 -H 'Host: '
*   Trying 127.0.0.1:8080...
* Connected to localhost (127.0.0.1) port 8080 (#0)
> GET / HTTP/1.1
> Host:
> User-Agent: curl/7.74.0
> Accept: */*
>
127.0.0.1 - - [2021-01-07 08:03:40] "GET / HTTP/1.1" 200 280 0.000100
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< Content-Type: text/plain
< Date: Thu, 07 Jan 2021 14:03:40 GMT
< Content-Length: 177
<

    WSGI Application
    SERVER_NAME      :   platform.ou.edu
    SERVER_PORT      :   8080
    HTTP_HOST        :
    Reconstructed URL:   http://platform.ou.edu:8080/
* Connection #0 to host localhost left intact
```

I'll note another potential bug in the example URL reconstruction code, which is that it fails if there is no `Host` header provided *at all*
```console
$ curl -v http://localhost:8080 -H 'Host:'
*   Trying 127.0.0.1:8080...
* Connected to localhost (127.0.0.1) port 8080 (#0)
> GET / HTTP/1.1
> User-Agent: curl/7.74.0
> Accept: */*
>
Traceback (most recent call last):
  File "//src/gevent/pywsgi.py", line 999, in handle_one_response
    self.run_application()
  File "//src/gevent/pywsgi.py", line 945, in run_application
    self.result = self.application(self.environ, self.start_response)
  File "/private/tmp/wsgi_test.py", line 8, in app
    HTTP_HOST        :   {environ['HTTP_HOST']}
KeyError: 'HTTP_HOST'
2021-01-07T14:03:29Z {'REMOTE_ADDR': '127.0.0.1', 'REMOTE_PORT': '58735', (hidden keys: 19)} failed with KeyError

127.0.0.1 - - [2021-01-07 08:03:29] "GET / HTTP/1.1" 500 161 0.001845
* Mark bundle as not supporting multiuse
< HTTP/1.1 500 Internal Server Error
< Content-Type: text/plain
< Connection: close
< Content-Length: 21
< Date: Thu, 07 Jan 2021 14:03:29 GMT
<
* Closing connection 0
Internal Server Error
```

Of course, this is a violation of the HTTP 1.1 specification and is technically an invalid request; servers *MAY* refuse to accept such a request and respond with a 400, but gevent and the `wsgiref.simple_server` reference implementation allow the request to proceed.

**Comment by IngeniousCoder** [comment]
Hello @jamadden 
Thanks for your detailed response.

I have actually reported the issue to flask earlier as `requests.url` is indeed part of flask.
However, I was told by Flask that it was probably how my WSGIServer handles it.

The relevant issue is at https://github.com/pallets/werkzeug/issues/1991. 

> My webserver at is configured to only accept requests...

This is indeed not part of GEvent. In my **flask** code, I have actually implemented this check before any requests:

```if request.headers.get("Host").endswith(".ingeniousapps.net") or request.headers.get("Host") == "ingeniousapps.net"```

As such, I am unsure if it is how the WSGIServer from gevent handles it, or if it is flask.

> Following the specification that says that URL reconstruction should only use the Host header if it's there, then if we exclude that header, the URL reconstruction algorithm does its best to pick based on the discovered SERVER_NAME:

Does this mean that gevent reconstructs the URL based on the Host header if it is there?

**Comment by jamadden** [comment]
>> My webserver at is configured to only accept requests...

> This is indeed not part of GEvent. In my flask code, I have actually implemented this check before any requests:

> `if request.headers.get("Host").endswith(".ingeniousapps.net") or request.headers.get("Host") == "ingeniousapps.net"`

> As such, I am unsure if it is how the WSGIServer from gevent handles it, or if it is flask.

There is no `request` object in WSGI, so whatever you're doing there is happening long after gevent's involvement.

> Does this mean that gevent reconstructs the URL based on the Host header if it is there?

No. gevent does *nothing* with reconstructing URLs. The only thing gevent does with anything close to URLs is break down the HTTP request line into the parts needed to populate the specified WSGI variables, notably `PATH_INFO` and `QUERY_STRING`. (Recall that the request line is not a URL; the host and port — and possibly other values like username and password — have already been handled by the client.) Similarly, the only thing gevent does with the HTTP `Host` header is copy it into the `HTTP_HOST` value in the `environ` dict passed to the WSGI callable. This should hold true for any WSGI implementation.

**Comment by IngeniousCoder** [comment]
Hi @jamadden 

Thank you for your quick and detailed response.
I will bring this matter up to the flask developers again for their reference.

Thanks for your time! I will reply here again should I have any further issues.

**Comment by jamadden** [comment]
I'm not explicitly saying this is directly a problem in flask or wherever you get your `request` object; the algorithm to reconstruct URLs is straightforward. But the algorithm depends on getting the proper inputs; so it seems more likely to me that it's an environment or configuration issue, with whatever software you've placed in front of `gevent.pywsgi`. (Hopefully there is some! Hopefully you don't have `gevent.pywsgi` directly exposed to the open Internet without some proxy support.)  Perhaps it's not passing the `Host` header through, or it may be modifying it. 

That said, given everything we've been over here, I don't see how I can help much more with this besides wishing you good luck finding the discrepancy.

**Comment by IngeniousCoder** [comment]
Hi @jamadden 
I have did some tests on Flask alone without gevent and have determined that it is not related to gevent.

The following code was what I did:

```py
>>> import flask
>>> app = flask.Flask(__name__)
>>> from datetime import datetime
>>> from flask import request
>>> @app.before_request
... def bef_req():
...     pass
...
>>> @app.after_request
... def aft_req(response):
...     print(f"User {request.environ.get('REMOTE_ADDR')} -- [{datetime.now().strftime('%Y-%m-%d %H:%M:%S')}] {request.environ.get('REQUEST_METHOD')} {request.url} \"{request.environ.get('SERVER_PROTOCOL')}\" \"{request.environ.get('HTTP_USER_AGENT')}\" |{response._status} - ")
...     return response
...
>>> @app.route("/")
... def main():
...     return "Test"
...
>>> app.run("0.0.0.0",port=80)
 * Serving Flask app "__main__" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
 * Running on http://0.0.0.0:80/ (Press CTRL+C to quit)
```

Thereafter, on a separate shell I used `requests` to query the new server:
```py
>>> requests.get("http://127.0.0.1")
<Response [200]>
>>> requests.get("http://127.0.0.1/apples")
<Response [404]>
>>> requests.get("http://127.0.0.1/apples",headers={"Host":"ingeniousapps.net"})
<Response [404]>
```
And the logs showed were:
```
User 127.0.0.1 -- [2021-01-07 23:24:15] GET http://127.0.0.1/ "HTTP/1.1" "python-requests/2.25.0" |200 OK -
127.0.0.1 - - [07/Jan/2021 23:24:15] "←[37mGET / HTTP/1.1←[0m" 200 -
User 127.0.0.1 -- [2021-01-07 23:24:34] GET http://127.0.0.1/apples "HTTP/1.1" "python-requests/2.25.0" |404 NOT FOUND -
127.0.0.1 - - [07/Jan/2021 23:24:34] "←[33mGET /apples HTTP/1.1←[0m" 404 -
User 127.0.0.1 -- [2021-01-07 23:24:50] GET http://ingeniousapps.net/apples "HTTP/1.1" "python-requests/2.25.0" |404 NOT FOUND -
127.0.0.1 - - [07/Jan/2021 23:24:50] "←[33mGET /apples HTTP/1.1←[0m" 404 -```


As such, I have determined that is not an issue with Gevent. I'm sorry for wasting your time. Have a great day ahead.

**Comment by jamadden** [comment]
Those logs are exactly what I would expect. It matches the semantics described in PEP 3333, following the purpose of the HTTP `Host` header. I don't see a bug here. 

Recall that the `Host` header is to tell the server who the client *thinks* it is connecting to (name-based [virtual hosting](https://en.wikipedia.org/wiki/Virtual_hosting)), regardless of the actual IP address it *does* connect to. Beyond its original use cases, this is necessary in the modern Internet, where a single server may have multiple IP addresses, and also be serving multiple domains; or a single IP and multiple domains, or a single IP and a single domain; or serving a domain may be spread across multiple servers or a CDN (thus with multiple IPs), and any combination thereof. This is the same reason that modern TLS/SSL includes [server name indication](https://en.wikipedia.org/wiki/Server_Name_Indication), to allow a client to tell a server who it is connecting to in order to pick the appropriate certificate.
