### ISSUE TITLE
Failed to build gevent 21.1.2

### ISSUE THREAD

**Issue by yesyves** [gevent/gevent#1765]
* gevent version: 21.1.2 installed through pip 21.0
* Python version: Python 3.9.1 built from source from python.org through Macports 2.6.4
* Operating System: MacOS 10.11.6

### Description:

Error Message (Complete build output in build.txt) : 

```
 /usr/bin/clang -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -pipe -Os -I/opt/local/include -I/opt/local/include -DLIBEV_EMBED=1 -DEV_COMMON= -DEV_CLEANUP_ENABLE=0 -DEV_EMBED_ENABLE=0 -DEV_PERIODIC_ENABLE=0 -DEV_USE_REALTIME=1 -DEV_USE_MONOTONIC=1 -DEV_USE_FLOOR=1 -Isrc/gevent/libev -I/opt/local/Library/Frameworks/Python.framework/Versions/3.9/include/python3.9 -I/private/var/folders/84/d3kmlqs95v78tgttk8pknqh80000gp/T/pip-install-ko7s16ut/gevent_4e61ae38b21f4cc085d31587063bc910/deps -I/private/var/folders/84/d3kmlqs95v78tgttk8pknqh80000gp/T/pip-install-ko7s16ut/gevent_4e61ae38b21f4cc085d31587063bc910/src/gevent/libev -I/private/var/folders/84/d3kmlqs95v78tgttk8pknqh80000gp/T/pip-install-ko7s16ut/gevent_4e61ae38b21f4cc085d31587063bc910/deps/libev -Isrc/gevent -Isrc/gevent/libev -Isrc/gevent/resolver -I. -I/Users/yves/.virtualenvs/passages/include -I/opt/local/Library/Frameworks/Python.framework/Versions/3.9/include/python3.9 -c src/gevent/libev/corecext.c -o build/temp.macosx-10.11-x86_64-3.9/src/gevent/libev/corecext.o -Wno-unreachable-code -Wno-deprecated-declarations -Wno-incompatible-sysroot -Wno-tautological-compare -Wno-implicit-function-declaration -Wno-unused-value -Wno-macro-redefined
  In file included from src/gevent/libev/corecext.c:872:
  In file included from src/gevent/libev/libev.h:9:
  /private/var/folders/84/d3kmlqs95v78tgttk8pknqh80000gp/T/pip-install-ko7s16ut/gevent_4e61ae38b21f4cc085d31587063bc910/deps/libev/ev.c:4105:34: error: use of undeclared identifier 'have_monotonic'
              if (ecb_expect_true (have_monotonic))
                                   ^
  1 error generated.
  error: command '/usr/bin/clang' failed with exit code 1
  ----------------------------------------
  ERROR: Failed building wheel for gevent
Failed to build gevent
ERROR: Could not build wheels for gevent which use PEP 517 and cannot be installed directly
[build.txt](https://github.com/gevent/gevent/files/5863150/build.txt)
```

Thanks !

**Comment by jamadden** [comment]
It's quite possible that libev no longer supports macOS 10.11. I have no capability to test on it or otherwise support 10.11 myself, so there's very little I can do.

I ran into a similar issue building on old versions of Windows, IIRC. I was able to get around it by setting certain compile time environment variables. You can see them in [this commit](https://github.com/gevent/gevent/commit/6ac4a329f9112ae72f687028b8430c535f3f58bf). You might be able to get it to build by doing the same thing (e.g., `$ CPPFLAGS="-DEV_PERIODIC_ENABLE=1 pip install gevent`).

Good luck!

**Comment by ibrewster** [comment]
For what it's worth, I am having the same error when trying to install event on MacOS Catalina, 10.15.7, using python 3.6.5 installed through the python installer package. libev installs fine via homebrew, but I get this error when trying to build gevent via pip install. Adding that CPPFLAGS environment variable doesn't appear to help in my case at least.

**Comment by ibrewster** [comment]
Interesting additional fact I just discovered: gevent 21.1.1 installs fine. Only gevent 21.1.2 gives this error for me. So apparently this is caused by something that changed between 21.1.1 and 21.1.2

**Comment by jamadden** [comment]
I just installed gevent 21.1.2 from source on macOS 10.15.7 using CPython 3.6.8 from the python.org installer without any issue. 

```console
$ uname -a
Darwin Curie 19.6.0 Darwin Kernel Version 19.6.0: Tue Nov 10 00:10:30 PST 2020; root:xnu-6153.141.10~1/RELEASE_X86_64 x86_64 i386 MacBookPro15,1 Darwin
$ cd /tmp
$ /usr/local/bin/python3.6 -m venv py36gevent
$ ./py36gevent/bin/pip install -v --no-binary gevent gevent==21.1.2
…lots of output…
done
  Removing source in /private/var/folders/y5/x7pvzk651c3dqkllbxd1jd280000gn/T/pip-install-e_gbq5d4/gevent
Successfully installed gevent-21.1.2 greenlet-1.0.0 zope.event-4.5.0 zope.interface-5.2.0
Cleaning up...
Removed build tracker '/private/var/folders/y5/x7pvzk651c3dqkllbxd1jd280000gn/T/pip-req-tracker-s8xet0oq'
You are using pip version 18.1, however version 21.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
```

I can't see that the version of Python would have any effect.

I certainly wouldn't expect that same exact error on a recent version of macOS (it occurs when the configure script can't find certain symbols *and* the `EV_PERIODIC` watchers aren't enabled, which gevent doesn't use or enable; the symbols should be defined on recent macOS. Arguably this is a bug in libev, but the systems without those symbols should be quite rare so I haven't tried to report it). Are you positive it's the same issue?

Other options include: using a version of Python that's tested on macOS and distributes binary wheels (3.7+) or using your system's copy of libev (via the `*EMBED*` environment variables that are semi-documented…somewhere…on the website, I think).

**Comment by ibrewster** [comment]
The error is identical, from everything I can see, though my build has more warnings. Here is the end of my pip install output:

```
 /usr/local/include/sys/cdefs.h:499:32: note: expanded from macro '__DARWIN_NO_LONG_LONG'
  #define __DARWIN_NO_LONG_LONG   (defined(__STRICT_ANSI__) \
                                   ^
  In file included from src/gevent/libev/corecext.c:92:
  In file included from /Library/Frameworks/Python.framework/Versions/3.6/include/python3.6m/Python.h:80:
  In file included from /Library/Frameworks/Python.framework/Versions/3.6/include/python3.6m/unicodeobject.h:111:
  /usr/local/include/wchar.h:202:6: warning: macro expansion producing 'defined' has undefined behavior [-Wexpansion-to-defined]
  /usr/local/include/sys/cdefs.h:501:9: note: expanded from macro '__DARWIN_NO_LONG_LONG'
                                  && !defined(__GNUG__))
                                      ^
  In file included from src/gevent/libev/corecext.c:872:
  In file included from src/gevent/libev/libev.h:9:
  /private/var/folders/b3/81zhsyrx58n_yvdw8hmwzy440000gn/T/pip-install-wl68cu4i/gevent_10b8312268a145e9ae881230355b9bfb/deps/libev/ev.c:4105:34: error: use of undeclared identifier 'have_monotonic'
              if (ecb_expect_true (have_monotonic))
                                   ^
  16 warnings and 1 error generated.
  error: command 'gcc' failed with exit status 1
  ----------------------------------------
  ERROR: Failed building wheel for gevent
Failed to build gevent
ERROR: Could not build wheels for gevent which use PEP 517 and cannot be installed directly
```

Note that I have *not* tried installing from source, but the command `pip install --no-cache-dir --no-binary gevent gevent==21.1.2 ` produces the exact same output. Also note that in both the original post and my case, we are using pip 21.0, while you are using pip version 18 - there are (to my understanding) significant differences in the pip build process between the two versions (though gevent 21.1.1 still works with the latest pip, so that may or may not be significant)

my `uname -a` output:
`Darwin IsraelsiMac.local 19.6.0 Darwin Kernel Version 19.6.0: Tue Nov 10 00:10:30 PST 2020; root:xnu-6153.141.10~1/RELEASE_X86_64 x86_64`

**Comment by jamadden** [comment]
The output indicating includes from `/usr/local/include/sys` is suspicious and I wouldn't be surprised if that's the problem. Normally, `cdefs.h`, for example, comes from Apple's SDK with a path like `/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/System/Library/Frameworks/Kernel.framework/Versions/A/Headers/sys/cdefs.h`.

Perhaps you've installed something from homebrew that's interfering with  the normal SDK? Maybe try building with Apple's `clang` instead of `gcc` (presumably from homebrew too, I'd guess).

**Comment by ibrewster** [comment]
And yet, there is still a difference between 21.1.1 and 21.1.2 that triggers this issue. Yes, I have a lot of libraries installed via homebrew, perhaps something is messing with the install. The original reporter mentioned using MacPorts, so same idea. However, that doesn't change the fact that something changed between minor versions of gevent to trigger this problem, even if said change isn't the "root cause".

For what it's worth, gcc, at least on my machine, does not appear to be a homebrew version:

```
(DorbellCam) israel@IsraelsiMac DorbellCam % which gcc
/usr/bin/gcc
(DorbellCam) israel@IsraelsiMac DorbellCam % ls -l /usr/bin/gcc
-rwxr-xr-x  1 root  wheel  31488 Sep 21 16:30 /usr/bin/gcc
(DorbellCam) israel@IsraelsiMac DorbellCam % gcc -v
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/c++/4.2.1
Apple clang version 12.0.0 (clang-1200.0.32.29)
Target: x86_64-apple-darwin19.6.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
(DorbellCam) israel@IsraelsiMac DorbellCam % 
```

Have you tried with the latest pip, which introduces the PEP 517 wheels that seem to be the problem?

**Comment by jamadden** [comment]
Yes, we know exactly what the difference is. It has nothing to do with pip (trust me, I've used and tested with every version of pip, repeatedly) and everything to do with the fact that the bundled version of libev was updated. There's something in your environment that libev doesn't like, and most likely its that you have the wrong headers on the include path.

**Comment by ibrewster** [comment]
You updated a bundled library in a bug fix patch release????? Wow. Yes, that would definitely explain it - there is apparently a bug in the updated version of libev, which has nothing to do with you (presumably). So that  I can report this bug in the proper place, what version did you update from and to?

Thanks for the information and spending your time looking into it.

**Comment by jamadden** [comment]
gevent does not use SemVer, it uses calendar ver. All that '21.1.2' means is that it's the second release made in the first month of 2021. 

Please (always) see the change notes for details and issue links.

**Comment by yesyves** [comment]
Thanks everybody for your (mostly) constructive input !

So the issue would be linked to NOT using MacOS bundled python, or failing to reproduce its behaviour ?

I'll try to have a look at this.

**Comment by jamadden** [comment]
> So the issue would be linked to NOT using MacOS bundled python, or failing to reproduce its behaviour ?

I doubt it. I regularly build and test with both python.org installers and python versions built by MacPorts without issue. (MacPorts python versions are my primary development pythons.)

The problem ibrewser experienced is most likely related to incorrect system headers taking the place of the correct system headers supplied by Apple's SDK. Thus, libev's configure script determines that the system doesn't support monotonic clocks (because the headers don't say that they do). I don't know when macOS started supporting the necessary APIs for monotonic clocks, but I know that 10.15 does support them, and most likely 10.14 did as well.

**Comment by jamadden** [comment]
@yesyves If you wanted to build gevent from source (either from the tarball on PyPI or from a git clone) with `python setup.py build_ext`, that should result in some logs, specifically (IIRC), `deps/libev/config.log`. That file might give a sense of where things are going wrong for you when libev checks for monotonic clocks.

**Comment by yesyves** [comment]
Hi

Here is my config.log resulting from building the tarball with `python setup.py build_ext -i` and the build output.

Hope that helps

[config.log](https://github.com/gevent/gevent/files/5962946/config.log)

[build.txt](https://github.com/gevent/gevent/files/5962948/build.txt)

**Comment by jamadden** [comment]
Thank you. That confirms my suspicions. The configuration log reports:
```
Undefined symbols for architecture x86_64:
  "_clock_gettime", referenced from:
      _main in conftest-34497d.o
ld: symbol(s) not found for architecture x86_64
```

And thus the libev define `HAVE_CLOCK_GETTIME` is not set. libev now (4.33, March 2020) implicitly depends on this definition, or things break (obviously). I would say this is a bug in libev, but the further commits to the libev source are actually making this dependency *stronger*, so at the very least systems that don't define `clock_gettime` are no longer tested by libev. 

According to `/usr/bin/man clock_gettime`, 

> These functions first appeared in Mac OSX 10.12

So it would appear that 10.12 (2016) is the earliest version still likely to be supported by libev. (Note that I am unable to test macOS systems earlier than 10.15.)

Possible options:

If you can build a patched version of libev 4.33 as a shared library, you can arrange for gevent to link to that instead of using its embedded version by setting some environment variables.

You could alter gevent's `_setuplibev.py` to attempt a workaround for the `have_monotonic` issue (look for `EV_PERIODIC_ENABLE` and set it to `1`). 

If you can build libev 4.32 as a shared library, you can arrange for gevent to link to that. This is not a tested configuration and might break.

You could alter gevent's `setup.py` to not even try building the libev extensions, and just use the libuv loop. gevent's libev loop is (slowly) being phased out in favor of libuv anyway.

**Comment by yesyves** [comment]
Thanks !

The funny part is that libev 4.33 builds just fine on 10.11 !

**Comment by jamadden** [comment]
libev has about a billion possible configuration options for speed and size. gevent has always turned off many things we don't need or use for better performance and decreased memory usage. Apparently many of those options are no longer tested on old systems, though. Building a shared library libev without specifying any of those options may work, but will result in a larger, slower library.

**Comment by yesyves** [comment]
I'll probably not go ahead on this because, as I said earlier, I probably will never have gevent 21.1.1 vs 21.1.2 issues in my development environment.

Thanks for at least setting the 10.12 issue straight !
