### ISSUE TITLE
what is the behavior of a synchronous application after monkey patched by gevent

### ISSUE THREAD

**Issue by EricLin89** [gevent/gevent#1770]
Hi,
I previously asked a question about migrating an existing synchonous application to asynchronous by using [gevent().](https://github.com/gevent/gevent/issues/1768). Now I have another question: What is the behavior of a synchronous application after monkey patched by gevent?

For example, if I have a piece of code sending requests to a lot of hosts concurrently, which was previously implemented using python threading. I want to increase its performance by using gevent instead. Do I need to rewrite the code to start tasks with`gevent.spawn()` and use `gevent.joinall()` to wait for them, or do I only need to call `monkey.patch_all()` and everything becoms asynchronous without any other modifications(probably because thread and socket is "patched"?)?

Other parts of the application, for example, it also starts a threaded http server, listen to requests and spawn a new thread to handle it, maybe also run some commands using `subprocess.Popen()`. What will be it's behavior after `monkey.patch_all()`(synchronous or asynchronous)?

Thank you.

**Comment by jamadden** [comment]
The whole point of monkey-patching is that you don't need to make any other code changes to use gevent and greenlets instead of kernel blocking operations and native threads.

When you monkey-patch, everything that previously used threads now uses greenlets, and sockets and other things, including `subprocess` are modified to cooperate with the gevent event loop and greenlets. [This](http://www.gevent.org/intro.html#monkey-patching) is all [documented.](http://www.gevent.org/api/gevent.monkey.html) 

[It's not really correct to speak of "synchronous" or "asynchronous": none of the APIs or programmer visible behaviour (at a high level) changes: operations still "block". Things just use greenlets and the event loop instead of native threads and native blocking operations (and is thus lighter weight and hopefully more efficient, since Python only uses one core anyway). The effect is exactly the same as using gevent directly. (Because, again, at a high-level, gevent is not "asynchronous", the APIs exposed to the programmer are normal blocking APIs.)]

**Comment by EricLin89** [comment]
Thank you for the reply. So here is how I understand:

1. A monkey-patched socket or subprocess still "blocks" when called directly, just as its native counterparts do. 
2. A task started in a monkey-patched thread is very similar to a gevent task created by `gevent.spawn()`, they both use greenlets.
3. When a monkey-patched socket or subprocess is called by `gevent.spawn()` or in a monkey-patched thread, they work in the cooperative way.
4. For programs running blocking IO operations in threads, simply call `monkey.patch_all()` at the beginning of the code will do all the magic to transform it into a greenlet and event loop based program.

Am I undertanding it right? Correct me if I'm wrong :)

**Comment by jamadden** [comment]
Yes, that's exactly the (only) point of monkey-patching.
