### ISSUE TITLE
Failing to install Gevent 21.1.0

### ISSUE THREAD

**Issue by shaqaruden** [gevent/gevent#1778]
* gevent version: 20.12.1/21.1.0 (PyPI)
* Python version: 2.7
* Operating System: Docker Container balenalib/rpi-raspbian:buster

### Description:

I am assisting with fixing an issue with the screenly-ose project. During the container building process the server dockerfile installs a bunch of python packages, one of these being gevent. The dependencies are specified in a requirements.txt file

```
pip install --no-cache-dir -r /tmp/requirements.txt
```

The install fails with 
```
Command "/usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-d9OWmy/gevent/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-BJ_sRL/install-record.txt --single-version-externally-managed --compile" failed with error code -9 in /tmp/pip-install-d9OWmy/gevent/The command '/bin/sh -c pip install --no-cache-dir -r /tmp/requirements.txt' returned a non-zero code: 1
```

Here is a copy of the output
[output.txt](https://github.com/gevent/gevent/files/6167428/output.txt)

**Comment by jamadden** [comment]
"failed with error code -9" means the process was killed by signal number 9, which I think is SIGKILL. I also think SIGKILL is what the Linux kernel sends to victim processes when it runs out of memory. So I think that the process is getting killed because your container needs more memory.

This is happening during the byte-compilation of Python files; there's nothing gevent can do about that. However, there is the '—no-compile' option to pip that prevents it from doing byte compilation; this does mean that importing the package will be slower (and possibly also run out of memory…).

**Comment by shaqaruden** [comment]
> 
> 
> "failed with error code -9" means the process was killed by signal number 9, which I think is SIGKILL. I also think SIGKILL is what the Linux kernel sends to victim processes when it runs out of memory. So I think that the process is getting killed because your container needs more memory.
> 
> This is happening during the byte-compilation of Python files; there's nothing gevent can do about that. However, there is the '—no-compile' option to pip that prevents it from doing byte compilation; this does mean that importing the package will be slower (and possibly also run out of memory…).

Thanks for the information. I will try this with a PI with more RAM.
