### ISSUE TITLE
Syntax error

### ISSUE THREAD

**Issue by leomiglio02** [gevent/gevent#1782]
* gevent version: 0.4.17-1+b1 preinstalled in parrotOS
* Python version: "Python 3.9.2-1 preinstalled on parrotOS"
* Operating System: "ParrotOS parrot5.7.0-2parrot2-amd64 (Debian Linux 5.7.10) x86_64"

### Description:

I was updating from apt and get configuration error caused by syntax error on /var/lib/dpkg/info/python3-greenlet.postinst

Setting up python3-greenlet (0.4.17-1+b)
/var/lib/dpkg/info/python3-greenlet.postinst: 1: Syntax error: ")" unexpected
dpkg: error processing package python3-greenlet (--configure):
installed python3-greenlet package post-installation script subprocess return
ed error exit status 2
Errors were encountered while processing:
python3-greenlet

### What I've run:

sudo dpkg --configure python3-greenlet

**Comment by jamadden** [comment]
Thanks for the report.

This package is not greenlet, this package is gevent. According to the error message, your issue is with the packaging of greenlet.

That said, neither the greenlet project nor the gevent project has anything to do with packaging for Debian and other operating systems. The greenlet and gevent projects only provide packages on PyPI that can be installed with a regular, unmodified `pip`; if you're using operating system tools such as `dpkg` to install gevent or greenlet, that has nothing to do with the gevent or greenlet project.

You'll need to contact the maintainer of your  operating system's 'python3-greenlet' package if you want them to fix this. Or you could use a regular, unmodified, pip to install (an up-to-date version) of gevent and greenlet.
