### ISSUE TITLE
Pydev warning about calling _sys.settrace()

### ISSUE THREAD

**Issue by jkemp101** [gevent/gevent#1783]
* gevent version: piped 20.12.1
* Python version: cPython 3.6.9
* Operating System: Ubuntu 18.04.4 LTS
* Pycharm: 2020.3.5

### Description:
After upgrading to `20.12.1` I get the following warning in Pycharm from pydev. I believe the change that triggered the warning is in https://github.com/gevent/gevent/pull/1722. Breakpoints are now erratic when I try to use Pycharm to debug gunicorn running in a docker container. Should there be a way to disable calling `settrace()` so that gevent is compatible with pydev?

```python-traceback
PYDEV DEBUGGER WARNING:
sys.settrace() should not be used when the debugger is being used.
This may cause the debugger to stop working correctly.
If this is needed, please check: 
http://pydev.blogspot.com/2007/06/why-cant-pydev-debugger-work-with.html
to see how to restore the debug tracing back correctly.
Call Location:
File "/venv/lib/python3.6/site-packages/gevent/threadpool.py", line 162, in _after_run_task
  _sys.settrace(None)
```

**Comment by jamadden** [comment]
PR #1722 makes gevent behave *more* like the standard library `threading` module. It too [calls sys.settrace() when starting threads](https://github.com/python/cpython/blob/c3c43dc07bd5055e5c31934533b935cb405f862d/Lib/threading.py#L948-L949). 

`sys.settrace` is thread-local state. In the standard library case, when the thread's function exits, the thread goes away, and so too (implicitly) the effect of `sys.settrace` is undone in that thread.

Here, gevent is maintaining a thread *pool*, and those threads are typically quite long lived (they usually live for the life of the process and are often created quite early). During that time, they are frequently idle, until they wake up and process a work item; then they go back to sleep. To allow for calls to `threading.settrace()` and `threading.setprofile()` to have some effect, it's necessary for gevent to make the corresponding `sys` calls each time a thread picks up a work item to begin processing. This again is thread-local state and shouldn't affect any other thread. I don't see any way around that. 

When done processing a work item, the thread-local hooks are removed while the thread sleeps because watching the gevent thread sleep is usually not what the tracer or profiler is installed for and tends to produce invalid/confusing output. Naturally, if they're still installed in the `threading` module when the next work item is ready to be processed, they are re-installed while it runs. I don't see any way around that either.

True, `concurrent.futures.ThreadPoolExecutor` does not do that. It relies on `threading` to set the appropriate values when the threads are added to its pool, and then just assumes they never change (and that it's useful to watch the threads sleep). That may work for `ThreadPoolExecutor` because one could shut it down and create a new one if the profile or trace hooks change, but the gevent's thread pool is used implicitly and people often don't even know it's there so that's not an appropriate solution for gevent.

If somehow this thread-local state is messing up your debugger, perhaps you could avoid using gevent's thread pool? On unix platforms, the most common implicit use of the thread pool is DNS lookups, so you could [configure it to use something that doesn't use threads](http://www.gevent.org/configuration.html#gevent._config.Config.resolver) — the blocking resolver is often a good choice when debugging.

**Comment by jkemp101** [comment]
Thanks for the detailed response. I tested again with everything updated and breakpoints seem to be working as expected. I also see that pydevd seems to ignore this situation with the standard library by checking filenames [here](https://github.com/fabioz/Pydev/blob/a6cd91c0ef63412930de19fe3fbd8b49f9ecb12c/plugins/org.python.pydev.core/pysrc/pydevd_tracing.py#L62). I'm closing this issue and will reopen if I have more specifics of what is going on.

**Comment by eyaler** [comment]
i am getting this issue on google colab

**Comment by max-l** [comment]
I'm getting this warning while using a pydev (with PyCharm).

Gevent is depended upon indirectly by a librairy that I use: https://github.com/ParallelSSH/parallel-ssh

The debbuger seems to be working just fine, but the warning pops up quite often and it is quite annoying.
