### ISSUE TITLE
Broken installation for ubuntu16 (docker) + python3.10

### ISSUE THREAD

**Issue by bogdandm** [gevent/gevent#1825]
* gevent version: gevent-21.8.0, from pip
* greenlet version: greenlet-1.1.2 from pip
* Python version: Python 3.10.0a6 from ppa:deadsnakes/ppa
* Operating System:
```
Linux abf2e55ef89e 5.4.0-89-generic #100~18.04.1-Ubuntu SMP Wed Sep 29 10:59:42 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.6 LTS
Release:        16.04
Codename:       xenial
```

### Description:

Got errors about wrong greenlet size:
```python-traceback
<frozen importlib._bootstrap>:241: RuntimeWarning: greenlet.greenlet size changed, may indicate binary incompatibility. Expected 152 from C header, got 160 from PyObject
<frozen importlib._bootstrap>:241: RuntimeWarning: greenlet.greenlet size changed, may indicate binary incompatibility. Expected 152 from C header, got 160 from PyObject
<frozen importlib._bootstrap>:241: RuntimeWarning: greenlet.greenlet size changed, may indicate binary incompatibility. Expected 152 from C header, got 160 from PyObject
<frozen importlib._bootstrap>:241: RuntimeWarning: greenlet.greenlet size changed, may indicate binary incompatibility. Expected 152 from C header, got 160 from PyObject
```
All versions are correct and should work together. I run same setup on ubuntu18 (real machine, not docker) without any issue.

### What I've run:

```
FROM ubuntu:xenial

ENV ROOT_PATH="/builds/project" \
    BUILD_DIR="/build/project" \
    VIRTUAL_ENV="/tv"

RUN mkdir -p $BUILD_DIR
WORKDIR $BUILD_DIR
RUN apt-get update \
    && apt-get install -y software-properties-common curl \
    && add-apt-repository ppa:deadsnakes/ppa \
    && apt-get update  \
    && apt-get install -y --no-install-recommends \
        build-essential \
        libssl-dev  \
        libffi-dev \
	    python3.10-dev \
	    python3.10-venv \
    && curl -s -L https://bootstrap.pypa.io/get-pip.py | python3.10

RUN echo "cache buster: 1"
RUN python3.10 -m venv . \
    && . bin/activate \
    && pip install --upgrade pip wheel \
    && pip install greenlet==1.1.2 gevent==21.8.0 \
    && pip freeze \
    && python -c "import gevent; print(gevent.getcurrent())"
RUN python3.10 -V && lsb_release -a && uname -a
```

Full log - https://gist.github.com/bogdandm/97c16bce2803076bdf3be1ba07a757a7

If I disable usage of .whl files with `pip install greenlet==1.1.2 gevent==21.8.0 --no-binary :all:` everything starts working fine

**Comment by jamadden** [comment]
The 1.1.2 greenlet wheels were built with CPython 3.10rc1 (rc1 status is typically the earliest I start supplying binary wheels due to the possibility of ABI changes). I can only assume that there was some ABI change between alpha 6 and rc1 that led to this. It's not obvious to me what it would be from the CPython changelog, but greenlet (used to) embeds a number of internal CPython structures in its objects, so the CPython developers may not have called out such a change.

At any rate, binary wheels of gevent for 3.10 manylinux are now available, and have been tested against the binary wheels for greenlet. Things should Just Work using CPython 3.10rc1 or above.
