### ISSUE TITLE
Latest gevent crashes with Illegal Instruction on import

### ISSUE THREAD

**Issue by chad-ermacora** [gevent/gevent#1854]
* gevent version: 21.12.0 (upgraded using pip 21.3.1)
* Python version: Python 3.7.3 (Included in Raspberry Pi OS 10 buster)
* Operating System: "Raspbian (Debian Linux 10.0 Linux 5.10.63+ armv6l)" (Running on Raspberry Pi Zero W)

### Description:
I upgraded pip modules for my program "Kootnet Sensors" on my older sensors running Raspberry Pi OS 10, when it completes it tries to start up my Pthon3 program but gives "Illegal Instruction" and crashes. 

I tracked down the issue to this module (and Numpy) by running python3 from the command line and importing each dependency to see where it crashes. It crashed when importing gevent and numpy on all 9 of my sensors (Numpy was only being used on 2 of the sensors, so I only needed to downgrade it on those 2). 

Installing the previous version 21.8.0 of gevent solved the issue. 

FYI, the upgraded Python modules work just fine when running on Raspberry Pi OS 11 using Python 3.9.2. 

When Kootnet Sensors crashes, the only thing shown before dropping back to the terminal is this (besides my normal log entries). 
```python-traceback
Illegal Instruction
```

### What I've run:
This is what I did for testing in the terminal (Start Python3 and import the module).

```python
import gevent
```

**Comment by jamadden** [comment]
I don't know what to tell you other than to try to compile gevent and/or greenlet yourself. Both gevent and greenlet provide aarch64 binary wheels built using the official aarch64 build image. gevent provided these same wheels in the last version; in greenlet, this is very new (but the version of greenlet didn't change—only new wheels for an older version where uploaded). 

The only build change in gevent binary wheels was to *disable* certain optimizations—but those optimizations were never applied to aarch64 wheels.

(In general, if you care about performance at all, especially with greenlet and gevent, and especially outside of the x86 architecture, I really suggest building your own wheels wiht appropriate optimizations. The distributed binary wheels are necessarily build by old compilers with generic optimization settings.)

I don't have enough information to offer any further assistance, especially since numpy also causes the same issue.
