### ISSUE TITLE
ImportError in MacOS 13.0 - incompatible architecture

### ISSUE THREAD

**Issue by sukhbir-singh** [gevent/gevent#1926]
* gevent version: 22.10.2
* Python version: Python 3.10.8
* Operating System: MacOS 13.0

### Description:

I created one small project where I just added few libraries in requirements.txt file and run pip install command. After that when I try running project using python main.py command, I am getting error related to gevent and it says something related to incompatible architecture. Can you please help in resolving this error ?

``
ImportError: dlopen(/Users/usr/temp-env/lib/python3.10/site-packages/gevent/_gevent_c_hub_local.cpython-310-darwin.so, 0x0002): tried: '/Users/usr/test-env/lib/python3.10/site-packages/gevent/_gevent_c_hub_local.cpython-310-darwin.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64')), '/System/Volumes/Preboot/Cryptexes/OS/Users/usr/test-env/lib/python3.10/site-packages/gevent/_gevent_c_hub_local.cpython-310-darwin.so' (no such file), '/Users/usr/test-env/lib/python3.10/site-packages/gevent/_gevent_c_hub_local.cpython-310-darwin.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64'))
``

### What I've run:

```
pip3 install requirements.txt
python main.py
```

My requirements.txt file looks like this

```python
locust~=2.12.2
grpcio==1.50.0
grpcio-tools==1.50.0
```

**Comment by jamadden** [comment]
Thank you for the report. The error is saying that you need an Apple Silicon binary of gevent, but you have an Intel binary. This is likely because of an error in our build process that I describe below. 

To fix this, you'll need to uninstall gevent, then build and install gevent again. Unfortunately, this will be complicated by the fact that you'll likely have a bad gevent binary stored in pip's local cache that you'll need to remove first. Something like this should work:

```console
$ python -m pip uninstall gevent
$ python -m pip cache remove gevent
$ python -m pip install --no-binary gevent gevent==22.10.2
```

That `--no-binary gevent` is there in case there is some other cache, like a devpi instance or HTTP proxy, that also has the bad gevent cached.

## Explanation

On macOS, it's possible to distribute binary wheels containing only Apple Silicon files, only Intel files, or both. Files containing both are called "universal2" wheels. Up until now, there was a universal wheel for cPython 3.10 on PyPI. But for some reason, some error in the build process, it did not actually contain universal files; it only contained Intel files. *I have removed this faulty wheel; it is **not possible** to upload a fixed version.*

```console
$ wget https://files.pythonhosted.org/packages/.../gevent-22.10.2-cp310-cp310-macosx_10_9_universal2.whl
--2022-11-14 09:02:45--  
Connecting to files.pythonhosted.org (files.pythonhosted.org)|2a04:4e42::319|:443... connected.
...
2022-11-14 09:02:45 (34.4 MB/s) - ‘gevent-22.10.2-cp310-cp310-macosx_10_9_universal2.whl’ saved [1877572/1877572]
$ unzip gevent-22.10.2-cp310-cp310-macosx_10_9_universal2.whl
$ file gevent/*.so
_gevent_c_abstract_linkable.cpython-310-darwin.so:   Mach-O 64-bit x86_64 bundle, flags:<NOUNDEFS|DYLDLINK|TWOLEVEL>
_gevent_c_greenlet_primitives.cpython-310-darwin.so: Mach-O 64-bit x86_64 bundle, flags:<NOUNDEFS|DYLDLINK|TWOLEVEL>
_gevent_c_hub_local.cpython-310-darwin.so:           Mach-O 64-bit x86_64 bundle, flags:<NOUNDEFS|DYLDLINK|TWOLEVEL>
_gevent_c_hub_primitives.cpython-310-darwin.so:      Mach-O 64-bit x86_64 bundle, flags:<NOUNDEFS|DYLDLINK|TWOLEVEL>
_gevent_c_ident.cpython-310-darwin.so:               Mach-O 64-bit x86_64 bundle, flags:<NOUNDEFS|DYLDLINK|TWOLEVEL>
_gevent_c_imap.cpython-310-darwin.so:                Mach-O 64-bit x86_64 bundle, flags:<NOUNDEFS|DYLDLINK|TWOLEVEL>
_gevent_c_semaphore.cpython-310-darwin.so:           Mach-O 64-bit x86_64 bundle, flags:<NOUNDEFS|DYLDLINK|TWOLEVEL>
_gevent_c_tracer.cpython-310-darwin.so:              Mach-O 64-bit x86_64 bundle, flags:<NOUNDEFS|DYLDLINK|TWOLEVEL>
_gevent_c_waiter.cpython-310-darwin.so:              Mach-O 64-bit x86_64 bundle, flags:<NOUNDEFS|DYLDLINK|TWOLEVEL>
_gevent_cevent.cpython-310-darwin.so:                Mach-O 64-bit x86_64 bundle, flags:<NOUNDEFS|DYLDLINK|TWOLEVEL>
_gevent_cgreenlet.cpython-310-darwin.so:             Mach-O 64-bit x86_64 bundle, flags:<NOUNDEFS|DYLDLINK|TWOLEVEL>
_gevent_clocal.cpython-310-darwin.so:                Mach-O 64-bit x86_64 bundle, flags:<NOUNDEFS|DYLDLINK|TWOLEVEL>
_gevent_cqueue.cpython-310-darwin.so:                Mach-O 64-bit x86_64 bundle, flags:<NOUNDEFS|DYLDLINK|TWOLEVEL>
```

There is also a universal2 wheel for cPython 3.11, but it appears to be correct. Repeating the above exercise results in things like this, as it should: 

```
_gevent_c_abstract_linkable.cpython-311-darwin.so:   Mach-O universal binary with 2 architectures: [\012- x86_64:\012- Mach-O 64-bit x86_64 bundle, flags:<NOUNDEFS|DYLDLINK|TWOLEVEL>] [\012- arm64:\012- Mach-O 64-bit arm64 bundle, flags:<NOUNDEFS|DYLDLINK|TWOLEVEL>
```
