### ISSUE TITLE
After patching subprocess Popen dosen't work

### ISSUE THREAD

**Issue by AMecea** [gevent/gevent#1988]
* gevent version: `gevent==23.7.0` (from PyPI)
* Python version: 3.11.5
* Operating System: Mac OS

### Description:

If the subprocess is imported before the Python subprocess is patched, it will fail with an obscure error. 
Here is the snippet to reproduce the error:

```python
from gevent import monkey
from subprocess import Popen

monkey.patch_subprocess()

Popen(['echo', 'ok'])
``` 

Will result in the following error:
```python-traceback
Traceback (most recent call last):
  File "/Users/bug.py", line 7, in <module>
    Popen(['echo', 'ok'])
  File "/usr/local/Cellar/python@3.11/3.11.5/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/local/Cellar/python@3.11/3.11.5/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 1883, in _execute_child
    self.pid = _fork_exec(
               ^^^^^^^^^^^
TypeError: 'NoneType' object is not callable
```

**Comment by jamadden** [comment]
You're patching in the wrong order. Do this:
```python
from gevent import monkey; monkey.patch_all()
from subprocess import Popen
Popen(['echo', 'ok'])
```

(I'm using `patch_all()` **because that's the recommended way to patch**; patching only some modules is advanced usage and isn't guaranteed to work because of interactions between modules.)

gevent's patching replaces the entire `subprocess.Popen` object, but if you've already imported it by name, you have your own private reference to the old stdlib `Popen` object, which cannot work.

This also works (it should be clear from the above *why* it works), but **this is not recommended** --- you should instead patch as early as possible.
```python
from gevent import monkey
import subprocess
monkey.patch_all()

subprocess.Popen(['echo', 'ok'])
```
