### ISSUE TITLE
gevent.reinit doesn't go far enough

### ISSUE THREAD

**Issue by vitaly-krugl** [gevent/gevent#200]
Presently, it just does "hub.loop.reinit()".  Shouldn't it do something like hub.destroy(destroy_loop=True) followed by gevent.get_hub(default=True) in order to survive fork on unix, etc.?

If not, then what's the purpose of gevent.reinit? When should it be used?

**Comment by jamadden** [comment]
That's a good question. I think the reason that the hub and loop aren't destroyed is that anyone that had previously stashed the return value of `get_hub()` or `get_hub().pool` into a local variable would be broken after that. Simply re-initing the pool causes the fork watchers to run at the next iteration of the event loop, which takes care of things like the threaded resolver and thread pool, without invalidating all of those values.

Destroying the pool also has some additional side-effects that re-initing it doesn't, such as running any cleanup watchers (which I don't think are exposed to the Python level) and uninstalling signal handlers.

So it seems like reiniting the pool is the safest option. If gevent master is still broken after a fork() for you, please do submit any specific issues.

Closing in triage for gevent 1.1.

**Comment by jgehrcke** [comment]
For future reference, my input on this topic:

Proper specification of behavior when forking a gevent application at an arbitrary state is currently non-existent and would be tremendously complex. I have tried to simplify this with gipc (https://pypi.python.org/pypi/gipc) by performing the drastic measures as requested here (loop and hub re-creation, see https://bitbucket.org/jgehrcke/gipc/src/2a6580bf535e444ec0062bce8cd01a64ac7aa7cb/gipc/gipc.py?at=default#cl-270). This works very well in many cases, but various subtle problems appeared to me in the past years. Two references indicating the complexity:

http://lists.schmorp.de/pipermail/libev/2013q4/002299.html
https://groups.google.com/forum/#!topic/gevent/bDP1qaMwrdI

> If gevent master is still broken after a fork() for you

The major issue is in my opinion that it is unclear how "broken" is defined in this case. Examples: 

* Duplication of greenlets does not make sense in most application scenarios. Would you consider the existence of duplicated greenlets as broken? If the answer is "yes", then a fork() in gevent currently is broken. If the answer is "no" and the developer should take care of this himself, then the conclusion is that fork() is not allowed after greenlets were spawned **or** manual greenlet deactivation/cleanup code is required in the child. Both are heavy and undocumented consequences.

* After a fork and manual event loop destruction in the child, inherited libev watchers might easily end up in unspecified behavior and do unexpected things. In my opinion this is "broken", but it can be handled on a case-to-case basis, like I did here: https://bitbucket.org/jgehrcke/gipc/issues/7

I think the current state of the art is that application developers have to figure out by themselves at which point in their application they can/should fork and which side effects this implicates. gipc is there to simplify (but not mitigate) this problem.

Fact is that forking in the context of libev and gevent may on the one hand be deterministic, but on the other hand may show very different behavior depending on the exact circumstances. This comes down to the fact that it is dangerous/difficult to declare `multiprocessing.Process` as being supported by gevent in the current state, because it is unclear (at least to me) what "supported" even means.

In the long term this situation should clearly be simplified, so that the behavior is simple (not saying "easy") instead of complex. Generic allowance of fork() within gevent is not doable in my opinion. Supporting a limited feature set of the multiprocessing module, however, is more realistic (strings attached, clearly!). Merging gevent and gipc might make sense in this regard.
