### ISSUE TITLE
Wheels for Python 3.9 - ARM64 missing for new releases

### ISSUE THREAD

**Issue by elsmorian** [gevent/gevent#2000]
* gevent version: 23.9.1
* Python version: 3.9
* Operating System: Linux

### Description:

With previous versions of gevent there have been wheels of `aarch64` builds hosted on pypi for all supported Python 3 versions, eg. 22.10.2 has both `x86-64` and `aarch64` builds for all versions of Python 3.11 to 3.6, however the newest 23.9.1 build is missing a few- `aarch64` builds for Python 3.9 and 3.8 are not present even though the rest of the `x86-64` versions are.

Any chance we could have them back please?

**Comment by jamadden** [comment]
[Python 3.9 has left active support and entered security-fix-only mode.](https://devguide.python.org/versions/)

Because of the enormous amount of time it takes to build and test gevent binaries under emulation, [this project doesn't build or test binary wheels for security-fix-only versions of Python in emulation](https://github.com/gevent/gevent/blob/b4aa4a4e660eb88c72d03c61cc12f3e2e4f9b0d9/scripts/releases/make-manylinux#L135-L144).

**Comment by elsmorian** [comment]
@jamadden Aha, thanks for the reply. That makes sense, though Python 3.10 seems to be in the same security only mode and there are `aarch64` builds for that? I guess they will be going away soon too?
