### ISSUE TITLE
Problem uploading large files: pywsgi.Input.Input._discard reads all input data

### ISSUE THREAD

**Issue by evgenii-moriakhin** [gevent/gevent#2015]
I am trying to upload a large (4GB) file to a server running pywsgi.

And I am facing the following problem - if the request reaches the WSGIHandler.handle_one_response (https://www.gevent.org/api/gevent.pywsgi.html#gevent.pywsgi.WSGIHandler.handle_one_response) call,  and if my wsgi application raises any error before planned correct reading the data from pywsgi.Input.Input(e.g. to save a file), then the code

```python
    def _discard(self):
        if self._chunked_input_error:
            # We are in an unknown state, so we can't necessarily discard
            # the body (e.g., if the client keeps the socket open, we could hang
            # here forever).
            # In this case, we've raised an exception and the user of this object
            # is going to close the socket, so we don't have to discard
            return

        if self.socket is None and (self.position < (self.content_length or 0) or self.chunked_input):
            # ## Read and discard body
            while 1:
                d = self.read(16384)
                if not d:
                    break
```

will read all the data from pywsgi.Input.Input. 
That is, the application code raises some user error, but the pywsgi server does not immediately respond, but still reads all the data from the input.

The client has to wait for the 4GB input to be processed by the server before getting a response.

Does the server really have to read all the data before giving a response? How do I upload large data and do custom preprocessing at the application level that can raise an error before processing that data?

**Comment by jamadden** [comment]
If you want to actually, you know, use HTTP in a standards-compliant manner, yes, you have to read and discard the chunked upload between requests. Otherwise pipelining breaks.

But the application itself doesn't have to do that. That's why WSGI apps return iterables: make the iterable a generator and you can choose when you send parts of the response. That's also why there's the write callable the application can access.

As a last resort, you can always prematurely close the socket, or even try shutting it down half-duplex. The client will get a connection terminated error at that point, and the server side will probably also log errors. You can get to the socket through the WSGI environment.
