### ISSUE TITLE
gevent.monkey.patch_sys breaks the arrow keys

### ISSUE THREAD

**Issue by bikeshedder** [gevent/gevent#274]
I am using `gevent` in *mushroom* (https://bitbucket.org/terreon/mushroom) and would like to provide an interactive console using the Python `cmd` module. Using the new `gevent.moneky.patch_sys` breaks the arrow keys.

-----

**[Update]** Shorter example showing the behavior:

```python
from gevent import monkey
monkey.patch_sys()
input()
```

-----

Example program making use of `cli`. Just start the application and try pressing theup- and down-arrow keys.

```python
#!/usr/bin/env python2

import cmd

from gevent import monkey


class Cmd(cmd.Cmd):

    def do_exit(self, args):
        '''Exit the console.'''
        return 'exit'

    def do_EOF(self, args):
        '''You can exit the console by typing Ctrl+D.'''
        return 'EOF'

    def do_ping(self, args):
        '''Return "pong".'''
        print 'pong'


if __name__ == '__main__':
    monkey.patch_sys()
    cmd = Cmd()
    cmd.cmdloop()
```

**Expected behaviour:** It should be possible to pick a previous command from the history by using the arrow keys.
**Actual behavior:** It outputs `^[[A` and `^[[B`.

**Comment by jamadden** [comment]
Unfortunately, the arrow key behaviour (and in general, integration with the readline module) is hardcoded in the C interpreter source code to only work with genuine `file` objects. *Any* type of wrapper around them throws off the use of the `readline` module, devolving instead into a simple call to the `readline` method.

Arrow keys and the like are kept behind this gate in the `raw_input` builtin function:
```C
    if (PyFile_AsFile(fin) && PyFile_AsFile(fout)
        && isatty(fileno(PyFile_AsFile(fin)))
        && isatty(fileno(PyFile_AsFile(fout)))) {
       ...
       PyOS_Readline(PyFile_AsFile(fin), PyFile_AsFile(fout),
                          prompt);
       ...
    }
    else { // effectively
       return PyFile_GetLine(fin, -1); // fin.readline()
    }
```

All the magic happens in `PyOS_Readline`. 

I don't see what gevent can do about this other than attempting to replace builtin functions, and that doesn't sound like a good idea to me, especially given that the functionality of `patch_sys` is removed altogether under Python 3 because of more low-level interpreter changes. I would be willing to review a PR though, if somebody can come up with a patch that works in all cases and has no risk :)

For now, to help with the triage for gevent 1.1, closing this. Please feel free to open another PR or comment on this one if you see another way.
