### ISSUE TITLE
Greenlet.kill doesn't raise the exception as soon as the execution is resumed in a targeted greenlet

### ISSUE THREAD

**Issue by kapouille** [gevent/gevent#394]
I'm not sure my assumptions are correct, but I would be expecting an exception issued by kill to be a criteria for awaking the targeted greenlet and get it to handle it straight away.

According to my tests, an exception induced by **Greenlet.kill()** only gets issued in the next call to **gevent.sleep()** after it was scheduled for execution.

Here's the full unit test file I used to test this:
```python
from functools import wraps
from gevent import sleep, getcurrent, spawn
from gevent.event import Event
from unittest2 import TestCase


class CancelledError(Exception):
    pass


def cancellable(fun):
    @wraps(fun)
    def handle_cancellation(*args, **kwargs):
        try:
            return fun(*args, **kwargs)
        except CancelledError as error:
            print "I'm cancelled! {}".format(error)
            return "cancelled"

    return handle_cancellation


def trace(fun):
    @wraps(fun)
    def trace_wrapper(*args, **kwargs):
        try:
            print "Entering {}".format(getcurrent())
            return fun(*args, **kwargs)
        finally:
            print "Leaving {}".format(getcurrent())

    return trace_wrapper


class TestKill(TestCase):
    def test_kill_one_sleep(self):
        @trace
        @cancellable
        def weird_kill(i_m_started):
            i_m_started.set()
            print "I yield execution now"
            sleep()
            print "I carry on doing stuff as if nothing happened"
            return "not cancelled"

        started_event = Event()
        one_sleep = spawn(weird_kill, started_event)
        started_event.wait()
        ###############################################################
        # This call:
        one_sleep.kill(CancelledError)
        # Causes this:
        # Traceback (most recent call last):
        #   File "/usr/local/lib/python2.7/site-packages/gevent/greenlet.py", line 391, in _kill
        #     greenlet.throw(exception)
        #   File "/usr/local/lib/python2.7/site-packages/gevent/greenlet.py", line 166, in throw
        #     greenlet.throw(self, *args)
        # CancelledError
        # <Greenlet at 0x16b4550: weird_kill(<gevent.event.Event object at 0x16b6890>)> failed with CancelledError
        ###############################################################
        self.assertEqual(one_sleep.value, "cancelled")  # ==> FAILS!

    def test_kill_more_sleep(self):

        @trace
        @cancellable
        def weird_kill_more_sleep(i_m_started):
            i_m_started.set()
            print "I yield execution now"
            sleep()
            print "I carry on doing stuff as if nothing happened"
            print "but hold on, let's yield execution once again"
            sleep()
            print "Even that didn't work"
            return "not cancelled"

        started_event = Event()
        more_sleeps = spawn(weird_kill_more_sleep, started_event)
        started_event.wait()
        more_sleeps.kill(CancelledError)
        self.assertEqual(more_sleeps.value, "cancelled")
```

Please let me know if there's something I misunderstand.

**Comment by jamadden** [comment]
Because of the [implementation details](https://github.com/gevent/gevent/issues/524#issuecomment-118190533) of `sleep()` (with no or a zero argument) and `Greenlet.kill`, you are correct: an exception may not be raised  *immediately* after the greenlet resumes execution. It depends on the specifics of the event loop at that point in time. Note that passing a non-zero argument to `sleep` happens to immediately raise the exception; again, this is an implementation detail. 

For purposes of `kill`, certain other greenlet-switching calls will behave like the former (`sleep(0)`) and raise the exception in the future, and some will behave like the latter (`sleep(0.1)`) and raise the exception immediately. Which ones are implementation details subject to change. Users of `kill` should expect that the exception will be raised at the first opportunity (which may be never, depending on what the greenlet does), but not necessarily immediately.

Depending on your use-case, here are some suggestions:
- If you are using sleep with an argument of 0, use a non-zero argument.
- Try to use `greenlet.throw` instead, which immediately raises the exception in all cases. Note, however, that it is tricky and dangerous to do, which is why `kill` exists.

I'll update the documentation on `kill` to clarify these facts.
