### ISSUE TITLE
pywsgi now modifies the input headers

### ISSUE THREAD

**Issue by raylu** [gevent/gevent#438]
bf67ee68cb5883d27e4d40835a91c31b731ae545 stops capitalizing the headers for you, but this also no longer copies the header list. `finalize_headers` adds headers to this list and this behavior is likely unexpected and can be tricky to debug:

```python
import gevent.pywsgi

DEFAULT_HEADERS = [
    ('Access-Control-Allow-Origin', '*'),
    ('Access-Control-Allow-Headers', 'X-Requested-With, X-Request'),
]

def application(environ, start_response):
    start_response('200 OK', DEFAULT_HEADERS)
    if environ['REQUEST_METHOD'] == 'OPTIONS':
        return []
    else:
        return ['hello!']

server = gevent.pywsgi.WSGIServer(('0.0.0.0', 1234), application)
server.serve_forever()
```

```bash
$ curl localhost:1234 -X OPTIONS -i
HTTP/1.1 200 OK
Access-Control-Allow-Origin: *
Access-Control-Allow-Headers: X-Requested-With, X-Request
Date: Thu, 08 May 2014 07:49:55 GMT
Content-Length: 0

$ curl localhost:1234 -i
HTTP/1.1 200 OK
Access-Control-Allow-Origin: *
Access-Control-Allow-Headers: X-Requested-With, X-Request
Date: Thu, 08 May 2014 07:49:55 GMT
Content-Length: 0

```
This happens because `DEFAULT_HEADERS` has been altered by `finalize_headers`

Unfortunately, according to the [WSGI spec](http://legacy.python.org/dev/peps/pep-0333/#the-start-response-callable),

> The response_headers argument is a list ... and the server may change its contents in any way it desires.

but I still argue that nobody expects this and, more importantly, it breaks existing code.

**Comment by jamadden** [comment]
The spec is pretty clear, I think. Interoperable code must return new lists for each response. It's not just pywsgi that exploits that behaviour; it's not uncommon for WSGI middleware to modify the response headers too (e.g., to add session cookies). I've seen this discussed before (in gunicorn? or pyramid? or webob? can't quite remember which frameworks), and in each case the value to the server/middleware (not having to make a copy at each layer) and the value of interoperable, standards-compliant code has won out. Existing code that exploited this old quirk of gevent was non-portable and non-standards compliant; the bug was in it.
