### ISSUE TITLE
pip install:  TypeError: unsupported operand type

### ISSUE THREAD

**Issue by jactuary** [gevent/gevent#441]
as a noob, I assume I've made a simple error.
I'm running 'pip3 install gevent', and receive a long log ending in the error below.  
If my error, is there a suggested fix?  
Otherwise, is this a bug?

-------------------------------------------------------
File "/private/var/folders/hz/my0nlh5s3ys5kzdysx3rmskr0000gn/T/pip_build_Folder1/gevent/setup.py", line 111, in make_universal_header

    print >>f, line

TypeError: unsupported operand type(s) for >>: 'builtin_function_or_method' and '_io.TextIOWrapper'

**Comment by jamadden** [comment]
There is a a gevent 1.1a1 release available on PyPI that is installable under Python 3.

**Comment by metakermit** [comment]
Thanks, @jamadden. `pip install gevent==1.1a1` worked indeed. This is not listed [in the docs](http://www.gevent.org/intro.html#installation), so I got confused at first.

**Comment by jamadden** [comment]
At this time, current version is 1.1rc1; I would definitely install that instead of 1.1a1 :) 

The docs are for the current version listed on PyPI, which is 1.1rc1. Depending on your version of pip and configuration, you may or may not have to specify versions or flags in order for pip to automatically choose "pre-release" versions (something of a misnomer in gevent's case, the release cycle is just historically long).

**Comment by metakermit** [comment]
Yeah, I just have a virtualenv installed using `mkvirtualenv -p /usr/local/bin/python3 venv` and by just doing `pip install gevent` (python 3.5, pip 7.1.2), I got:
```
Collecting gevent
  Using cached gevent-1.0.2.tar.gz
Requirement already satisfied (use --upgrade to upgrade): greenlet>=0.4.7 in /Users/kermit/.virtualenvs/mpyd/lib/python3.5/site-packages (from gevent)
Installing collected packages: gevent
  Running setup.py install for gevent
```

Before I tried to do `pip install Flask-Sockets`, so maybe that also "cached the wrong version" or whatever. Anyway, 1.1rc1 also seems to work :)
