### ISSUE TITLE
Add 'runcount' attribute

### ISSUE THREAD

**Issue by MichaelAz** [gevent/gevent#465]
Stackless has a `runcount` attribute which returns the number of runnable tasklets.
It's be useful for gevent to expose a similar attribute for the number of runnable greenlets.

**Comment by jamadden** [comment]
gevent doesn't keep track of the total number of greenlets in existence, and neither does the underlying `greenlet` library. 

Because greenlets are directly switched to by reference from some *other* greenlet, the greenlet library really has no motivation to keep track of all created greenlets. Either they get switched to or they don't; if they don't it could be because the last reference to them vanished or because no one ever decided to call `switch` on them.

Because gevent can run just fine using raw greenlets from the greenlet library (it even provides a shortcut function `spawn_raw` for this purpose), it's insufficient for gevent to try to keep track of all greenlets created through its interface. Too, greenlets can switch in and out of being scheduled by the gevent hub and directly cooperatively with other greenlets.

To address the questions raised in the referenced comment, it seems to me like this is something that would have to be implemented by the lower-level greenlet library. Have you tried checking at that level?
