### ISSUE TITLE
Streaming response is buffered until ~50KB is generated

### ISSUE THREAD

**Issue by shahafabileah** [gevent/gevent#518]
Does gevent.pywsgi.WSGIServer buffer responses until ~50KB is generated?

I have a Flask app served by gevent.pywsgi.WSGIServer.  In my app, I have a view that does a "streaming" response (Transfer-Encoding: chunked).  The view is written like this: http://flask.pocoo.org/docs/0.10/patterns/streaming/#basic-usage.  It generates 35 chunks of text, with a 1 second wait in between.

When I run it locally, it works.  When I run it in production (on Heroku), it doesn't.  The request seems to block for ~35 seconds, which exceeds Heroku's timeout of 30 seconds.

See for yourself: https://www.vamo.com/backstage/test-streaming

So it looks like there's some kind of buffering going on.  I've been chatting with someone from Heroku to figure out what it is.  He said that they don't buffer on their end, and that from his TCP trace, it appears that the issue is in our app.

As a test, he suggested altering the view to force it to generate lots of text.  Indeed, when I do this, the streaming response starts after ~50KB has been generated.

See for yourself: https://www.vamo.com/backstage/test-streaming?block-size=10000

He noted that there might be a TCP setting that I need to set, in order to ensure that there's no buffering going on, perhaps TCP_NODELAY (http://linux.die.net/man/7/tcp).

Does such an option exist with gevent.pywsgi.WSGIServer?  I didn't see anything obvious in the docs (http://www.gevent.org/gevent.pywsgi.html#gevent.pywsgi.WSGIServer) or in the code.

For what it's worth, I noticed that cherrypy's WSGIServer seems to have an explicit option for this:
https://cherrypy.readthedocs.org/en/3.3.0/refman/wsgiserver/init.html#cherrypy.wsgiserver.HTTPServer.nodelay

Thanks!

**Comment by jamadden** [comment]
`pywsgi` does no buffering on its own. Each chunk a WSGI application generates (whether through the use of a returned iterator or by writing to the object returned by `start_response`) is immediately written to the connection using `socket.sendall`. There may be delays if the upstream socket isn't accepting data, of course, but that's out of gevent's hands.

Since different behaviour is observed in different environments, I would suspect an environmental difference: perhaps middleware, or an upstream reverse proxy, etc. 

I'm closing this as part of the triage for 1.1. Please feel free to comment or open another issue if you feel like there's still a problem. This kind of question, though, might get better response on the mailing list.
