### ISSUE TITLE
Unexpected Greenlet switching pattern

### ISSUE THREAD

**Issue by EelcoHoogendoorn** [gevent/gevent#524]
I have a greenlet which runs a main loop, which will over time spawn a collection of child greenlets. The child greenlets are a subclass of greenlet. The child greenlets perform an iterative algorithm, and at each iteration they sleep, such as to yield to one of their siblings, which indeed they do as expected. However, the child greenlets as a whole only switch back to their parent greenlet every 500 iterations. This is neither desirable (I want to spawn new children faster than that), nor expected (to me). I imagined the hub to switch to different greenlets using a simple FIFO queue, but this does not appear to be the case. As far as I can tell, this is not documented behavior. Is that a lack of documentation, or am I looking at a bug here? Or perhaps there is a simple rookie mistake that could explain this kind of behavior? I get the impression the act of spawning greenlets inside greenlets has something to do with it.

**Comment by thedrow** [comment]
Will you be willing to provide a failing test case that demonstrates this behavior?
Preferably in the form of a pull request.

**Comment by jamadden** [comment]
I think we're safely in the realm of undocumented, implementation-specific behaviour that's subject to change and liable to differ between platforms (CPython/PyPy) or gevent releases.

In the current implementation, if *all* greenlets are only yielding via `gevent.sleep(0)`, then all greenlets will effectively run in a FIFO fashion. Parentage has nothing to do with it. However, as soon as some greenlets start doing other kinds of cooperative tasks, like I/O or using Timeout objects or even sleeping with a positive `seconds` argument---basically anything that uses the underlying libev event loop---then those greenlets get taken out of the FIFO ordering. This is because gevent only periodically returns to the libev loop---it has to prioritize somehow, and trips to libev are relatively expensive so if there's still work to do without going back to the loop, it will do it (up to a limit).

In effect, currently greenlets that are `sleep`ing have higher priority than those doing I/O. One possible rationale could be that if you're sleeping just to yield, you probably have more CPU work to do, whereas odds are that the IO-bound tasks might not be ready yet.

I hope this helps. I'm closing this issue as part of triage for the upcoming 1.1 release. If you have other questions or want to propose an alternate scheduling mechanism, please feel free to reopen this issue or a different one (though changing in scheduling policies is probably a big change, too big to slip into 1.1 at this point, and it would probably need quite a bit of thought and discussion.)
