### ISSUE TITLE
ThreadPool.spawn is slow under greenlet

### ISSUE THREAD

**Issue by lifei** [gevent/gevent#529]
Here's code

```python
import time
import contextlib
import gevent
from gevent.threadpool import ThreadPool


pool = ThreadPool(1)


@contextlib.contextmanager
def timer(label):

    bt = time.time()
    yield
    print '%s %.2f ms' % (label, 1000 * (time.time() - bt))


def _eat_cpu():
    time.sleep(1)


def handle(i):

    with timer('pool.spawn: %s' % i):
        r = pool.spawn(_eat_cpu)

    return r.get()


def test1():

    for i in xrange(10000):
        gevent.spawn(handle, i)


def test2():

    for i in xrange(10000):
        handle(i)


# test1()
test2()

gevent.wait()

```

result of test1
pool.spawn: 0 0.23 ms
pool.spawn: 1 0.05 ms
pool.spawn: 2 1001.69 ms
pool.spawn: 3 2006.98 ms
pool.spawn: 4 3010.17 ms
pool.spawn: 5 4012.46 ms
pool.spawn: 6 5017.56 ms
pool.spawn: 7 6020.28 ms
pool.spawn: 8 7025.68 ms
pool.spawn: 9 8027.78 ms
pool.spawn: 10 9033.52 ms

result of test2
pool.spawn: 0 0.74 ms
pool.spawn: 1 0.08 ms
pool.spawn: 2 0.08 ms
pool.spawn: 3 0.08 ms
pool.spawn: 4 0.12 ms
pool.spawn: 5 0.07 ms
pool.spawn: 6 0.11 ms
pool.spawn: 7 0.07 ms
pool.spawn: 8 0.14 ms
pool.spawn: 9 0.10 ms
pool.spawn: 10 0.07 ms

I find test1 is wait for pool's semaphore, the code is below.

```python
148     def spawn(self, func, *args, **kwargs):
149         while True:
150             semaphore = self._semaphore
151             semaphore.acquire()
152             if semaphore is self._semaphore:
153                 break
154         try:
155             task_queue = self.task_queue
156             result = AsyncResult()
157             thread_result = ThreadResult(result, hub=self.hub)
158             task_queue.put((func, args, kwargs, thread_result))
159             self.adjust()
160             # rawlink() must be the last call
161             result.rawlink(lambda *args: self._semaphore.release())
162             # XXX this _semaphore.release() is competing for order with get()
163             # XXX this is not good, just make ThreadResult release the semaphore before doing anything else
164         except:
```

162             # XXX this _semaphore.release() is competing for order with get()
163             # XXX this is not good, just make ThreadResult release the semaphore before doing 

The notes describe the reasons for using a semaphore. 

I tried the following code and it works fine. the spawn is no longer waiting, but i don't know whether it's ok for the modification.

```python
154         try:
155             task_queue = self.task_queue
156             result = AsyncResult()
157             thread_result = ThreadResult(result, hub=self.hub)
158             task_queue.put((func, args, kwargs, thread_result))
159             self.adjust()
160             result.rawlink(lambda *args: self._semaphore.release())
161         finally:
162             self._semaphore.release()
```

Actually, what I want is the pool should behavior like a size fixed queue. When it is full, it should refuse to accept any new task and raise a Full exception so the client know the server is overload and try another server. Either waiting a new position or unlimited size task queue is not good.

**Comment by jamadden** [comment]
`gevent.threadpool.ThreadPool` is a bounded-size pool implementation. It's semantics are meant to match that of `gevent.pool.Pool`. In that model, the `spawn` method does not return until the task has been accepted for processing.

In your example's `test1`, you are spawning 10,000 greenlets in a single burst. These greenlets each run in sequence and attempt to spawn a task in the `ThreadPool`. Because of the way greenlet switching works, all 10,000 greenlets are effectively trying to spawn a task at the same time. Once all 10,000 greenlets have attempted their `spawn` call, one at a time they each actually get to acquire the semaphore that protects the `ThreadPool` from queueing too many tasks to spawn. Because each task takes one second, and because the `ThreadPool` is only allowed to run one task at a time, concurrent `spawn` calls *can be no faster than one second apart*. And because there are 10,000 greenlets, all of which run sequentially, each greenlet is going to have waited *one more second* than the previous greenlet.

In `test2`, this second wait between spawns is transferred to `r.get()`, which blocks until the task has finished running. If you take that out, `test2` becomes effectively identical to `test1` with each spawn taking one second (the only difference is that they're sequential, not parallel so only one is waiting at a time).

Releasing the semaphore at the end of the `spawn` method defeats the point of having a semaphore and turns the `ThreadPool` into an unbounded queue whose `spawn` method never blocks. There may be a place for that, but it doesn't match the semantics of `Pool`.

So based on this, this example doesn't present any evidence that releasing the semaphore is a bottleneck.

It should be possible to subclass `ThreadPool` and override the `spawn` method to raise an exception instead of blocking if desired.
