### ISSUE TITLE
One problem with resolver_thread.py, line 34, in getaddrinfo

### ISSUE THREAD

**Issue by emamirazavi** [gevent/gevent#573]
I use gunicorn with Gevent workers, Peewee as an ORM and it's connection pool from package named playhouse. I have this error that makes me suspicious to both Gevent and Peewee. But it may belong to the Gevent. Please see the traceback and give me your view:
```
Jun 12 10:23:52 www.example.com gunicorn[4763]: [2015-06-12 10:23:52 +0000] [4763] [DEBUG] 3 workers
Jun 12 10:23:53 www.example.com gunicorn[4763]: [2015-06-12 10:23:53 +0000] [4763] [DEBUG] 3 workers
Jun 12 10:23:54 www.example.com gunicorn[4763]: [2015-06-12 10:23:53 +0000] [2876] [DEBUG] GET /inbound
Jun 12 10:23:54 www.example.com gunicorn[4763]: [2015-06-12 10:23:53 +0000] [2876] [ERROR] Error handling request
Jun 12 10:23:54 www.example.com gunicorn[4763]: Traceback (most recent call last):
Jun 12 10:23:54 www.example.com gunicorn[4763]: File "/usr/lib/python2.7/site-packages/gunicorn/workers/async.py", line 52, in handle
Jun 12 10:23:54 www.example.com gunicorn[4763]: self.handle_request(listener_name, req, client, addr)
Jun 12 10:23:54 www.example.com gunicorn[4763]: File "/usr/lib/python2.7/site-packages/gunicorn/workers/ggevent.py", line 159, in handle_request
Jun 12 10:23:54 www.example.com gunicorn[4763]: super(GeventWorker, self).handle_request(*args)
Jun 12 10:23:54 www.example.com gunicorn[4763]: File "/usr/lib/python2.7/site-packages/gunicorn/workers/async.py", line 105, in handle_request
Jun 12 10:23:54 www.example.com gunicorn[4763]: respiter = self.wsgi(environ, resp.start_response)
Jun 12 10:23:54 www.example.com gunicorn[4763]: File "/usr/lib/python2.7/site-packages/flask/app.py", line 1836, in __call__
Jun 12 10:23:54 www.example.com gunicorn[4763]: return self.wsgi_app(environ, start_response)
Jun 12 10:23:54 www.example.com gunicorn[4763]: File "/usr/lib/python2.7/site-packages/flask/app.py", line 1820, in wsgi_app
Jun 12 10:23:54 www.example.com gunicorn[4763]: response = self.make_response(self.handle_exception(e))
Jun 12 10:23:54 www.example.com gunicorn[4763]: File "/usr/lib/python2.7/site-packages/flask/app.py", line 1403, in handle_exception
Jun 12 10:23:54 www.example.com gunicorn[4763]: reraise(exc_type, exc_value, tb)
Jun 12 10:23:54 www.example.com gunicorn[4763]: File "/usr/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
Jun 12 10:23:54 www.example.com gunicorn[4763]: response = self.full_dispatch_request()
Jun 12 10:23:54 www.example.com gunicorn[4763]: File "/usr/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
Jun 12 10:23:54 www.example.com gunicorn[4763]: rv = self.handle_user_exception(e)
Jun 12 10:23:54 www.example.com gunicorn[4763]: File "/usr/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
Jun 12 10:23:54 www.example.com gunicorn[4763]: reraise(exc_type, exc_value, tb)
Jun 12 10:23:54 www.example.com gunicorn[4763]: File "/usr/lib/python2.7/site-packages/flask/app.py", line 1473, in full_dispatch_request
Jun 12 10:23:54 www.example.com gunicorn[4763]: rv = self.preprocess_request()
Jun 12 10:23:54 www.example.com gunicorn[4763]: File "/usr/lib/python2.7/site-packages/flask/app.py", line 1666, in preprocess_request
Jun 12 10:23:54 www.example.com gunicorn[4763]: rv = func()
Jun 12 10:23:54 www.example.com gunicorn[4763]: File "/usr/local/src/aaron/lib/myapp/webserver.py", line 96, in before_request
Jun 12 10:23:54 www.example.com gunicorn[4763]: g.db.connect()
Jun 12 10:23:54 www.example.com gunicorn[4763]: File "/usr/local/src/aaron/lib/myapp/database.py", line 77, in connect
Jun 12 10:23:54 www.example.com gunicorn[4763]: super(MyPooledMySQLDatabase, self).connect()
Jun 12 10:23:54 www.example.com gunicorn[4763]: File "/usr/lib/python2.7/site-packages/peewee.py", line 2944, in connect
Jun 12 10:23:54 www.example.com gunicorn[4763]: **self.connect_kwargs)
Jun 12 10:23:54 www.example.com gunicorn[4763]: File "/usr/lib/python2.7/site-packages/playhouse/pool.py", line 108, in _connect
Jun 12 10:23:54 www.example.com gunicorn[4763]: conn = super(PooledDatabase, self)._connect(*args, **kwargs)
Jun 12 10:23:54 www.example.com gunicorn[4763]: File "/usr/lib/python2.7/site-packages/peewee.py", line 3399, in _connect
Jun 12 10:23:54 www.example.com gunicorn[4763]: return mysql.connect(db=database, **conn_kwargs)
Jun 12 10:23:54 www.example.com gunicorn[4763]: File "/usr/lib/python2.7/site-packages/pymysql/__init__.py", line 88, in Connect
Jun 12 10:23:54 www.example.com gunicorn[4763]: return Connection(*args, **kwargs)
Jun 12 10:23:54 www.example.com gunicorn[4763]: File "/usr/lib/python2.7/site-packages/pymysql/connections.py", line 644, in __init__
Jun 12 10:23:54 www.example.com gunicorn[4763]: self._connect()
Jun 12 10:23:54 www.example.com gunicorn[4763]: File "/usr/lib/python2.7/site-packages/pymysql/connections.py", line 823, in _connect
Jun 12 10:23:54 www.example.com gunicorn[4763]: (self.host, self.port), self.connect_timeout)
Jun 12 10:23:54 www.example.com gunicorn[4763]: File "/usr/lib64/python2.7/site-packages/gevent/socket.py", line 570, in create_connection
Jun 12 10:23:54 www.example.com gunicorn[4763]: for res in getaddrinfo(host, port, 0 if has_ipv6 else AF_INET, SOCK_STREAM):
Jun 12 10:23:54 www.example.com gunicorn[4763]: File "/usr/lib64/python2.7/site-packages/gevent/socket.py", line 621, in getaddrinfo
Jun 12 10:23:54 www.example.com gunicorn[4763]: return get_hub().resolver.getaddrinfo(host, port, family, socktype, proto, flags)
Jun 12 10:23:54 www.example.com gunicorn[4763]: File "/usr/lib64/python2.7/site-packages/gevent/resolver_thread.py", line 34, in getaddrinfo
Jun 12 10:23:54 www.example.com gunicorn[4763]: return self.pool.apply_e(self.expected_errors, _socket.getaddrinfo, args, kwargs)
Jun 12 10:23:54 www.example.com gunicorn[4763]: File "/usr/lib64/python2.7/site-packages/gevent/threadpool.py", line 222, in apply_e
Jun 12 10:23:54 www.example.com gunicorn[4763]: success, result = self.spawn(wrap_errors, expected_errors, function, args, kwargs).get()
Jun 12 10:23:54 www.example.com gunicorn[4763]: File "/usr/lib64/python2.7/site-packages/gevent/threadpool.py", line 159, in spawn
Jun 12 10:23:54 www.example.com gunicorn[4763]: self.adjust()
Jun 12 10:23:54 www.example.com gunicorn[4763]: File "/usr/lib64/python2.7/site-packages/gevent/threadpool.py", line 133, in adjust
Jun 12 10:23:54 www.example.com gunicorn[4763]: self._adjust_step()
Jun 12 10:23:54 www.example.com gunicorn[4763]: File "/usr/lib64/python2.7/site-packages/gevent/threadpool.py", line 113, in _adjust_step
Jun 12 10:23:54 www.example.com gunicorn[4763]: self._add_thread()
Jun 12 10:23:54 www.example.com gunicorn[4763]: File "/usr/lib64/python2.7/site-packages/gevent/threadpool.py", line 142, in _add_thread
Jun 12 10:23:54 www.example.com gunicorn[4763]: start_new_thread(self._worker, ())
Jun 12 10:23:54 www.example.com gunicorn[4763]: error: can't start new thread
Jun 12 10:23:54 www.example.com gunicorn[4763]: [2015-06-12 10:23:54 +0000] [4763] [DEBUG] 3 workers
Jun 12 10:23:55 www.example.com gunicorn[4763]: [2015-06-12 10:23:55 +0000] [4763] [DEBUG] 3 workers
Jun 12 10:23:56 www.example.com gunicorn[4763]: [2015-06-12 10:23:56 +0000] [4763] [DEBUG] 3 workers
Jun 12 10:23:57 www.example.com gunicorn[4763]: [2015-06-12 10:23:57 +0000] [4763] [DEBUG] 3 workers
Jun 12 10:23:58 www.example.com gunicorn[4763]: [2015-06-12 10:23:58 +0000] [4763] [DEBUG] 3 workers
Jun 12 10:23:59 www.example.com gunicorn[4763]: [2015-06-12 10:23:59 +0000] [4763] [DEBUG] 3 workers
Jun 12 10:24:00 www.example.com gunicorn[4763]: [2015-06-12 10:24:00 +0000] [4763] [DEBUG] 3 workers
```

**Comment by jgehrcke** [comment]
Quite likely this is an issue on application level, neither in gevent nor in peewee.

The actual error is easy to spot. It is, as usual, at the bottom of the traceback: **"error: can't start new thread"**

A quick Internet search for the error message tells us that it is a well-known error (even in the context of gevent) for an application trying to create too many threads.

The error message is thrown in CPython's [_threadmodule.c](https://github.com/python/cpython/blob/master/Modules/_threadmodule.c): this is the operating system telling your application that it won't let it spawn a new thread right now. Usually that means that your application has started too many threads in the current process. The operating system prevents your application from consuming too many resources. The actual limit implementation entirely depends on the operating system.

Sure, Peewee or gevent *could* provoke this situation. But if that was the case it would be unlikely that you are the first one to discover this problem. What is much more likely: your application code (directly or indirectly) spawns too many threads. Since you did not provide a minimal working example for reproducing your issue, we must assume that the problem is in your application.

I think in the context of gevent one might easily get this error when one, without knowing, creates treal OS threads instead of greenlets. Possibly you did not properly apply gevent monkey-patching, but this really is just wild speculation.

And, please take this note serious: it is good to provide feedback, but you should not start reporting "important bugs" without providing the most essential ingredients (answers to questions like: Which operating system do you run on? Which software versions do you use? When does the issue occur? Can you reproduce the issue? Can you come up with a minimal working example?).

**Comment by emamirazavi** [comment]
I'm using in two places of my code gevent.ThreadPool. But they are not
related to this error, i think. If you tell me use of ThreadPool is
dangerous i may accept but i don't know what problem is! With
limitation(max concurrent) to 10 i am using gevent ThreadPool in this
format that i just once have created this two ThreadPool() and have used
them in two while in two different threads. Previously i had this error(*error:
can't start new thread*) because several times i was creating ThreadPool()
but after that with defining one time this two TreadPool() that problem was
solved. Now i think gunicorn with gevent workers leads to this error! Just
i think! I must apologize for this title. You're right. That was a
judgement and is very bad behaviour. Have you ever had any assumption like
me about gunicorn, gevent and peewee in this state or you think using
ThreadPool in my code leads to this problem?! Thanks,

**Comment by emamirazavi** [comment]
see this #569

**Comment by jgehrcke** [comment]
I did not try to suggest that using ThreadPool is dangerous. You need to understand the purpose of each entity before using it. If you wish to say so, threads, processes and greenlets are all equally "dangerous". Building a reasonable architecture with reliable behavior based on these ingredients is sometimes incredibly complex to get right.

Really, considering the discussion in #569 it becomes obvious that you do not have enough experience/knowledge so far in order to build a reliable architecture for your problem. What you need to take as given from here is that *you are spawning too many threads in your application*. You need to solve this on your own.

Regarding this issue here, I am pretty sure that it can be closed. But let's approach this systematically. No "I think"s, please. You must come up with a minimal working code example that reproduces the issue you are observing. Otherwise we cannot efficiently treat this topic.

**Comment by emamirazavi** [comment]
BTW i am suspicious to gevent apply_e. According to the traceback, it's using ThreadPool to conclude gethostbyname. See gevent.resolver_thread. If you want to close it close it.

**Comment by jgehrcke** [comment]
@emamirazavi: this is an issue tracker. We cannot start working on this issue without having more facts/boundary conditions/code in our hands. Please stop speculating, let us discuss facts! I take your inquiry serious and I really hope you can provide more facts about the issue you are observing.


> BTW i am suspicious to gevent apply_e. [...] it's using ThreadPool to conclude gethostbyname

There is absolutely nothing suspicious about this very fact. It is well-documented. In the gevent README it is stated: "*DNS queries performed through c-ares or a threadpool.*". I hope you understand why gevent bundles c-ares in the first place. So if you do not "like" a thread being used for that, configure gevent to use c-ares!

However, I can almost assure you that the number of threads used by your application for name resolution is low. Name resolution is, almost for guarantee, not responsible for your application hitting a thread count limit.

> If you want to close it close it.

Neither can I close this issue, nor do I want to close this issue. See, this is distributed work. You have your chance here to explain why you think this might be an issue with gevent. It is easiest for us to understand if you can provide a minimal working code example. 

Let me break down the relevant information you have provided so far: you have a rather complex application which hits the OS thread count limit and you *think* this might be an issue with gevent.

In particular, you did not pin-point a certain component in gevent, and you did not even attempt to speculate what could be wrong with gevent internals.

So what do you expect? That someone goes through the gevent code base, *trying* to find *something* because someone *thinks* there *might* be *something* wrong *somewhere* in gevent?

Will not happen, we need more facts. So, do your homework, and investigate *why* your application fails. If you can narrow down gevent as the source of the issue, then come back here and present your arguments. This will be helpful, thanks!

**Comment by emamirazavi** [comment]
For now i close this issue and will rewrite our code without ThreadPool. If the problem again exists, i will open this. Thanks for your extended answers.
