### ISSUE TITLE
StreamServer close socket after handle

### ISSUE THREAD

**Issue by Champax** [gevent/gevent#594]
Hello,

on gevent 1.1a1 : it seems that the StreamServer, after accepting a tcp socket (handle callback), just close it.

If whenever your accept stuff start handling the socket in an async manner, StreamServer will close it.

I hacked stuff by using a custom StreamServer and overriding do_close(), but is this intentional?

From BaseServer
```
def do_handle(self, *args):
        spawn = self._spawn
        handle = self._handle

        def _close_when_done(*args):
            try:
                return handle(*args)
            finally:
                self.do_close(*args)
```

BaseServer.do_close do nothing, but StreamServer blast the socket
```
    def do_close(self, socket, *args):
        socket.close()
```

**Comment by jamadden** [comment]
Yes, this is intentional. It was discussed [here](https://github.com/gevent/gevent/issues/248#issuecomment-82467350). In a nutshell, leaving the socket around after the handler returned was undocumented behaviour that only worked correctly on CPython 2 due to reference-based semantics. On PyPy it led to leaks and IIRC on Python 3 ResourceWarnings.

The intention of StreamServer is that the `handle` function or method does not return until handling is complete and you are done with the socket. If you are spawning another greenlet to deal with the socket in your handler, you should `join` it to prevent your handler from returning.

I realize this isn't well documented but that was part of the original problem :)

**Comment by Champax** [comment]
Thanks for quick feedback.

Yeah i spawn stuff to handle the socket. I will keep my hack for the moment, i will move to join later if required.
Closing this.
