### ISSUE TITLE
gevent._ssl3.py blocks in SSLSocket.read() if no socket.setdefaulttimeout()

### ISSUE THREAD

**Issue by FirefighterBlu3** [gevent/gevent#597]
(python3)

self._sslobj.read() inside the SSLSocket class will block the whole process until the first client initially causing the read() closes the socket. (5 minutes for chrome)

to replicate this, establish a simple wsgiserver w/ ssl and a simple route for '/' or '/index.html' etc. in chrome or firefox, load this route. from command line run openssl s_client to retrieve the same url.

the openssl client will hang waiting for the connection to be accepted while the first client idles on the ssl socket.

**Comment by jamadden** [comment]
Thanks for the report! 

Unfortunately, not only does this affect Python 3, it also affects Python 2.7.9 and above, because 2.7.9 basically shares the Python 3 ssl implementation. (This means that the released version 1.0.2 is vulnerable to this issue.)

I've added a failing test case to master, but at this time I'm not sure how to fix it. Ideas and PRs welcome! Pinging everyone who has committed code to `_ssl3.py` or `_sslgte279.py`: @denik @fantix @ivoz @sprin

**Comment by jamadden** [comment]
I think I have this figured out now.

**Comment by FirefighterBlu3** [comment]
excellent. i haven't had a chance to get away from office work to spend time on it today. i have a python ssl tool which handles the ssl wantread and wantwrite status cleanly using non blocking poll. i had wanted to implement this here. what's your approach?

**Comment by jamadden** [comment]
It turned out to be very simple, just hidden in all the dynamic import magic: if the process wasn't monkey patched, the `gevent.ssl` module ended up using the stdlib's `socket` object instead of the gevent version.

**Comment by BingoZ** [comment]
I recently find ssl socket still blocks the whole process using the newest version, no matter whether I use `monkey.patch_ssl` or `from gevent import ssl` . I wonder if this bug is fixed and how should I do to avoid it.

**Comment by odedfos** [comment]
I also encountered ssl hanging issue.
Running latest gevent==1.2.1 and python 2.7.13
It does not happen on my local environment, only when running via jenkins.
