### ISSUE TITLE
gevent 1.1b1 monkey.patch_builtins() crashes PyPy 2.6.0

### ISSUE THREAD

**Issue by parasyte** [gevent/gevent#618]
Details in the PyPy tracker: https://bitbucket.org/pypy/pypy/issues/2089/crash-in-pypy-260-linux64-with-gevent-11b1

I do not know whether this is the gevent lock implementation misbehaving, or a bug in PyPy (have not investigated further than reducing a test case). I filed it against PyPy, and linking here for reference.

**Comment by parasyte** [comment]
From the PyPy core dump backtrace, I would say it looks a lot like import recursion. This is very likely related: https://github.com/gevent/gevent/commit/0924a16f3d87d6af5a234ee806a94d9adff7cec5#diff-da8f63ebb2bd4dab3782671c16926349

**Comment by jamadden** [comment]
Thanks for the report and the reproducible example. It should be fixed now.

I'm not sure I'd call this a bug in either gevent or PyPy (though it would be nice if PyPy didn't crash and reliably raised the RuntimeError on all platforms, but cpyext has its sharp edges). It's more of an incompatibility due to implementation details on certain platforms...and gevent monkeys (hah!) with those implementation details. This is the kind of thing we'll have to watch out for as new versions come out.

**Comment by parasyte** [comment]
@jamadden Looks good here. Much appreciated!
