### ISSUE TITLE
gevent.pool.IMapUnordered.queue should be bounded

### ISSUE THREAD

**Issue by sylvinus** [gevent/gevent#638]
Hi,

I'm fetching documents from a primary database (MongoDB), performing some transformations on them in parallel with `gevent.pool.imap_unordered`, using its output as iterator to bulk-insert into a secondary database (Elasticsearch).

This is a nice usecase for IMapUnordered because everything can run in parallel. It's ideal for this kind of  [ETL](https://en.wikipedia.org/wiki/Extract,_transform,_load) workflow.

However, my secondary database (receiving writes) is the slowest component of the pipeline, and because `gevent.pool.IMapUnordered.queue` is not bounded, the `gevent.pool.IMapUnordered._run` method can iterate very fast regardless of the speed of the `gevent.pool.IMapUnordered.__next__` calls performed on the iterator, leaving a growing amount of intermediate results in memory. In our usecase it's ~200Mb a minute, which kills the app very quickly.

I think we should add a semaphore to avoid blowing things up. This is the patch I made to avoid having more intermediate results than the size of the pool, which seems reasonable:

```
class BoundedIMapUnordered(gevent.pool.IMapUnordered):

  def __init__(self, *args, **kwargs):
      self.spawned = gevent.lock.Semaphore(value=kwargs.pop("maxsize", 100))
      super(BoundedIMapUnordered, self).__init__(*args, **kwargs)

  def _inext(self):
        value = self.queue.get()
        self.spawned.release()
        return value

  def _ispawn(self, *args):
        self.spawned.acquire()
        return super(BoundedIMapUnordered, self)._ispawn(*args)


class BoundedPool(gevent.pool.Pool):
    def imap_unordered(self, func, *iterables):
        return BoundedIMapUnordered.spawn(func, izip(*iterables), spawn=self.spawn,
                                          _zipped=True, maxsize=self.size)
```

Let me know what you think!

**Comment by jamadden** [comment]
Good point. That's a big enough hole in the API that I consider it a bug (and the `_i*` methods are a private implementation detail so we couldn't support this exact workaround in the future). I've added a `maxsize` parameter in the referenced commit that should handle this case. Please let me know if it doesn't.

Depending on the complexity of a specific application, though, this might be better handled at the application level. If there are many network-using but not memory/CPU intensive parts to the `func`, which then pulls together the final results at the end, a semaphore around the "expensive" part of the application code inside `func` is going to result in a better degree of parallelism than anything that can be done at the IMapUnordered level, since it can only bluntly limit concurrency around the entire thing. And note that this is on top of the spawn limit of the pool itself, so the lowest value will be the effective value.

**Comment by sylvinus** [comment]
Wow, thanks, was not expecting a patch this big :)
