### ISSUE TITLE
Incorrect decode() attempt in pywsgi @ PY3

### ISSUE THREAD

**Issue by Eugeny** [gevent/gevent#659]
https://github.com/gevent/gevent/blob/9f79cc0a1ca3b5d3bf64ca1d44476f9f2c69495d/gevent/pywsgi.py#L503

If the underlying socket object's `readline()` method returns a `str` instance (decoded string), gevent still incorrectly attempts to decode it. This leads to a crash on Python 3 (unlike with Python 2, where such decode/encode consistency is not enforced).

Solution: add `if isinstance(line, str):` before the `decode` call.

**Comment by jamadden** [comment]
`self.rfile` is created in mode `rb`, so it should not be returning a `str`, it should be returning a `bytes`. When does it return a `str`?

**Comment by Ivoz** [comment]
Possibly `rfile` needs to be documented that it must be a binary file-like object?

**Comment by jamadden** [comment]
If you mean the constructor keyword argument, I would rather not document it at all; I'd rather comment it as deprecated and remove it in the future. It was added in 2011 as part of a refactoring, but was never documented or used by gevent, as far as I can see (probably it was intended for tests). None of gunicorn gevent-socketio or gevent-websocket or ajenti make use of that parameter (again, AFAICS), and supporting it obviously makes refactoring harder because the class invariants are harder to be sure of. I'm having a hard time coming up with a case where that parameter *should* be used as anything other than what it normally would be set to, but perhaps there is a valid use case...that's what I'm waiting to hear.

**Comment by Eugeny** [comment]
@jamadden you're right, I've just changed the `makefile` behavior on my fake socket object to return a `io.BufferedRWPair` with a fake `readline` method instead of `io.TextIOWrapper`. My initial source of confusion was that gevent required a `readline()` method on the file object, which hints at possible non-binary nature of the file.
