### ISSUE TITLE
gevent._semaphore.Semaphore leaks list objects under PyPy

### ISSUE THREAD

**Issue by parasyte** [gevent/gevent#660]
I'm investigating a memory leak in my application, and seem to have found at least one with `Semaphore` when `threading` is monkey patched. This only occurs with PyPy; CPython is not affected.

I'm using [`objgraph`](https://mg.pov.lt/objgraph/) for leak detection. Here's an example REPL session that shows the leak pretty clearly:

```python
(env)$ pypy
Python 2.7.9 (295ee98b6928, May 31 2015, 07:29:04)
[PyPy 2.6.0 with GCC 4.8.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>>> import threading
>>>> import objgraph

>>>> # warmup the objgraph statistics
>>>> objgraph.show_growth(limit=1)
str     8862     +8862
>>>> objgraph.show_growth(limit=1)
int     3542       +83
>>>> objgraph.show_growth(limit=1)

>>>> # create some garbage, and check the object growth
>>>> for i in range(1000): _ = threading.Semaphore()
>>>> objgraph.show_growth(limit=10)
method           80        +2
list            201        +1
lock              6        +1
unicode         548        +1
_Condition        4        +1
_Semaphore        2        +1

>>>> # create even more garbage to ensure there is no leak
>>>> for i in range(1000): _ = threading.Semaphore()
>>>> objgraph.show_growth(limit=10)

>>>> # monkey patch and warmup the objgraph stats again
>>>> import gevent.monkey
>>>> gevent.monkey.patch_all()
>>>> objgraph.show_growth(limit=1)
int               16502    +12960
>>>> objgraph.show_growth(limit=1)
int    16556       +54
>>>> objgraph.show_growth(limit=1)

>>>> # create some garbage with the gevent monkey patch, and check the object growth
>>>> for i in range(1000): _ = threading.Semaphore()
>>>> objgraph.show_growth(limit=10)
list         1422     +1000
LockType        2        +2
dict         1156        +1
str         14364        +1
tuple        4471        +1
>>>> objgraph.show_growth(limit=10)
int    16557        +1
>>>> objgraph.show_growth(limit=10)

>>>> # create even more garbage, just to be sure it's a real leak
>>>> for i in range(1000): _ = threading.Semaphore()
>>>> objgraph.show_growth(limit=10)
list      2422     +1000
tuple     4473        +2
dict      1157        +1
>>>> objgraph.show_growth(limit=10)

>>>> # create even more garbage, just to be sure it's a real leak
>>>> for i in range(1000): _ = threading.Semaphore()
>>>> objgraph.show_growth(limit=10)
list      3422     +1000
tuple     4476        +3
>>>>
```

So far I've failed to determine what the referrers are. I've also tried using the `gc` module to force collections, but it doesn't change the number of `list` objects. I suspect this is something to do with the new CFFI-based semaphore module for PyPy.

**Comment by jamadden** [comment]
Wow, that's definitely worth looking into. I'm afraid it's going to turn out to be a PyPy bug, though, in their C-extension compatilibity code: Under both CPython and PyPy, the lock primitive (`thread.allocate_lock`) is from `gevent._semaphore`, which is a Cython compiled module (because that was the easiest/best way to get truly atomic operations on PyPy).

**Comment by parasyte** [comment]
Ah, it's compiled by Cython. There's also another interesting point; `list` is not leaked when using `gevent.lock.Semaphore()`

**Comment by parasyte** [comment]
Minimal test cases:

## No leak with `gevent.lock.Semaphore`

```python
# semaphore.py

from gevent.lock import Semaphore
import objgraph

objgraph.show_growth(limit=1)

print '---'
for i in range(1000): _ = Semaphore()
objgraph.show_growth(limit=1)

print '---'
for i in range(1000): _ = Semaphore()
objgraph.show_growth(limit=1)

print '---'
for i in range(1000): _ = Semaphore()
objgraph.show_growth(limit=1)

print '---'
for i in range(1000): _ = Semaphore()
objgraph.show_growth(limit=1)

print 'done'
```

### Results:

```
(env)$ pypy semaphore.py
str    17384    +17384
---
list      935      +444
---
list      978       +43
---
list     1106      +128
---
list     1190       +84
done
```

----

## Leak with subclass of `gevent.lock.Semaphore`

```python
# subsemaphore.py

from gevent.lock import Semaphore
import objgraph

class SubSemaphore(Semaphore):
    pass

objgraph.show_growth(limit=1)

print '---'
for i in range(1000): _ = SubSemaphore()
objgraph.show_growth(limit=1)

print '---'
for i in range(1000): _ = SubSemaphore()
objgraph.show_growth(limit=1)

print '---'
for i in range(1000): _ = SubSemaphore()
objgraph.show_growth(limit=1)

print '---'
for i in range(1000): _ = SubSemaphore()
objgraph.show_growth(limit=1)

print 'done'
```

### Results:

```
(env)$ pypy subsemaphore.py
str    17384    +17384
---
list     1491     +1000
---
list     2491     +1000
---
list     3491     +1000
---
list     4491     +1000
done
```

**Comment by jamadden** [comment]
Thanks for the test case! I've reproduced this and I think I have it solved (commit forthcoming). I've also used the same method to make sure that the following loop doesn't leak:
```python
print("--- Loop")
for j in range(2):
	s = SubSemaphore()
	for i in range(30000):
		s.acquire()
		g = gevent.spawn(s.release)
		gevent.sleep()
		s.acquire()
		s.release()
		del g
objgraph.show_growth(limit=1)
```
Which now yields:
```
--- Loop
tuple     3028        +3
done
```

Note that the call to `gevent.sleep` (or something similar) is required to allow everything to be reported as cleared. Without it the results can be are very different:
```
--- Loop
tuple   123042   +120017
done
```

**Comment by parasyte** [comment]
:+1: That solves the `list` leak... (Still trying to track down a tuple leak in my app. If it happens to be from gevent, I'll open a new ticket.)

**Comment by jamadden** [comment]
The details are explained in a comment in the commit but I'll repeat them here for posterity and to expand upon them:

In PyPy 2.6.1 with Cython 0.23, `cdef public` or `cdef readonly` or simply `cdef` attributes of type `object` can appear to leak if a Python subclass is used (this is visible simply instantiating the subclass if the constructor of the Cython object sets the attribute). In this case, we have `_links`  and `_notifier` that are such attributes and the Cython constructor initialized `_links` to a new list. A class in gevent.thread subclasses this class, and instantiating it leaked a list. This is demonstrated in the test case above. 

The solution was to carefully manage the lifetime of the objects we put in these attributes so that, in the normal case of a semaphore used correctly (dealloced when it's not locked and no one is waiting), the leak goes away (because these objects are back to None). (That is, the constructor no longer initializes the attribute).

This can also be solved on PyPy by simply not declaring these objects in the pxd file, but that doesn't work for CPython ("AttributeError: No attribute..."). Declaring attributes in the pxd causes them to be directly stored in the `struct` that makes up the object; not declaring them (or attributes set by subclasses) puts them in the instance's `__dict__`.

The pxd definition looks like this:
```python
cdef class Semaphore:
    cdef public int counter
    cdef readonly object _links
    cdef readonly object _notifier
    cdef public int _dirty
```

And the constructor was the usual thing:
```python
class Semaphore(object):
    def __init__(self, value=1):
        self.counter = value
        self._dirty = False
        self._notifier = None
        self._links = [] # LEAK
```

**Comment by jamadden** [comment]
On #pypy from an author arigato:
>>> 
>>> jamadden: ok, seems simple enough: tp_dealloc is never called in PyPy for an instance of a user subclass of a cpyext class
>>> 11:52
>>> arigato
>>> that's indeed a bug of PyPy

**Comment by parasyte** [comment]
That's excellent info! Thanks for the followup.
