### ISSUE TITLE
v1.1b6 - NameError: name 'GetStdHandle' is not defined

### ISSUE THREAD

**Issue by srossross** [gevent/gevent#668]
In the latest gevent beta release `gevent==1.1b6`

 subprocecss has a few errors on the windows platform does not work on windows

```
[python3] C:\Users\Administrator> python ge.py
Traceback (most recent call last):
  File "ge.py", line 134, in <module>
    main()
  File "ge.py", line 107, in main
    close_fds=False)
  File "C:\Miniconda3\envs\python3\lib\site-packages\gevent\subprocess.py", line
 384, in __init__
    errread, errwrite) = self._get_handles(stdin, stdout, stderr)
  File "C:\Miniconda3\envs\python3\lib\site-packages\gevent\subprocess.py", line
 627, in _get_handles
    p2cread = GetStdHandle(STD_INPUT_HANDLE)
NameError: name 'GetStdHandle' is not defined
```

**Comment by jamadden** [comment]
The internals of the stdlib subprocess module have changed under Python 3 on Windows, perhaps more than once. It is not necessarily expected to work, but it isn't really a regression since Python 3 was previously not supported at all. The subprocess module doesn't seem to be much used under Windows, though, as these are the first user reports, even though the issue has existed since 1.1a1, I believe. 

PRs welcome! (Otherwise I'll probably wind up turning patching off by default on win/py3 in final release.)

**Comment by jamadden** [comment]
Thanks for the reports. I was able to merge in the Python 3 changes without a huge amount of effort, so subprocess is working now. (At least mostly, there's a corner case or two with universal newlines that may or may not be working correctly.)
