### ISSUE TITLE
sslwrap issues have made it back to python 2.7.5 (Red Hat)

### ISSUE THREAD

**Issue by GarrettHeel** [gevent/gevent#702]
After upgrading to the Centos 7.2 release today, I noticed that the following patch has been backported to python 2.7.5:

https://bugzilla.redhat.com/show_bug.cgi?id=1259421
https://rhn.redhat.com/errata/RHSA-2015-2101.html

This was previously causing the `sslwrap` issues in python >= 2.7.9 and is now also affecting 2.7.5.

Relevant links:

Commit that fixed 2.7.9: https://github.com/gevent/gevent/commit/b6fcd5e468a82cf1926760efee3a531e45948d18#diff-117c9127922ead54983bc5b173701483

2.7.9 discussion: https://github.com/gevent/gevent/issues/477

**Comment by Ivoz** [comment]
Can you paste a traceback of what exactly is breaking for you?

This seems mostly because Redhad is creating a Frankenstein 2.7.5 that's not conformant to what either 2.7.5 or 2.7.9 should be. :/

Redhat's EPEL may give you an actual CPython 2.7.9 that works, if I understand what EPEL is for correctly.

**Comment by jamadden** [comment]
Yeah, there was discussion on python-dev. I think RedHat is backporting PEP 466 to their LTS versions. They know that this is going to have compatibility issues and some of those they've planned for (e.g., a config file to switch HTTPS cert verification *back off* by default), but some they can't.

So if that's what's going on here, I'm not sure what to do about. In general, given how closely tied gevent is to the standard library, it doesn't seem reasonable to support frakenversions distributed by particular distros. (For one thing, it could be extremely hard to test; travis doesn't have access to these hybrids.) On the other hand, in this particular case, it is probably possible to do an attr check to decide which version of the ssl module to use, rather than switching explicitly off version.

**Comment by GarrettHeel** [comment]
Thanks for the answers @ivoz and @jamadden.

I don't have the exact traceback since boto is obscuring it but I do see:
```TypeError: __init__() got an unexpected keyword argument 'server_hostname'```

...which appears to be the same as the traceback from https://github.com/gevent/gevent/issues/477

I completely understand that it's difficult for gevent to support these releases and point taken about looking at the EPEL packages instead.

I'm happy to leave it up to you guys to decide whether an attr check is better or to just call it unsupported and leave it at that.

**Comment by jamadden** [comment]
I'd rather not make a change in how the SSL modules are loaded and patched before 1.1.0 as that would necessitate at least one more release candidate. The exception, of course, would be if we *need* another RC because this affects a significant number of people with no easy workarounds. So far this is the first report of this issue we've had since 1.0.2 was released back in May. But that could change if RedHat is just now rolling out the backport (although I haven't been able to find any release notes for a RedHat Python 2.7.5 more recent than April of this year).

**Comment by RyanGWU82** [comment]
Red Hat did just start pushing this out recently. The backport was pushed out in Red Hat Enterprise Linux 7.2 which was just released on November 19. Related to that, CentOS 7.2 was just released yesterday. Our servers automatically install CentOS updates, which is why Garrett and I were one of the first teams to run into this.

**Comment by blakeblackshear** [comment]
@RyanGWU82 how did you end up working around this?

**Comment by jamadden** [comment]
I'm testing out a PR for this: it looks like we may need another RC to deal with some PyPy crashes too.

**Comment by jamadden** [comment]
If someone that has this issue with a frankenversion could please test out PR #705 and leave feedback there I'd appreciate it. I don't have easy access to one of those versions.

**Comment by RyanGWU82** [comment]
@blakeblackshear We reinstalled the Python 2.7.5-18 RPMs from CentOS 7.1. (That was the last update released for CentOS/RHEL 7.1. In version 7.2 they bumped it to Python 2.7.5-34 which is the frankenversion.) This is the command we used to roll back:

```
rpm -Uvh --oldpackage http://mirror.centos.org/centos-7/7.1.1503/updates/x86_64/Packages/python-2.7.5-18.el7_1.1.x86_64.rpm \
  http://mirror.centos.org/centos-7/7.1.1503/updates/x86_64/Packages/python-devel-2.7.5-18.el7_1.1.x86_64.rpm \
  http://mirror.centos.org/centos-7/7.1.1503/updates/x86_64/Packages/python-libs-2.7.5-18.el7_1.1.x86_64.rpm
```

This should work for most CentOS users, although you might also need to rollback other packages like python-debug or python-tools. There should be a way for RHEL users to rollback too, but I'm not exactly sure how.

**Comment by blakeblackshear** [comment]
Thanks @RyanGWU82. That has been my strategy too.

**Comment by schakrava** [comment]
Thanks @RyanGWU82, very much like the awesome cs107 TA years ago :)

the frankenversion broke Rockstor(based on centos) in subtle ways and rolling back proved to be the clean solution.

**Comment by feifangit** [comment]
@RyanGWU82 Thanks for your solution!

**Comment by jamadden** [comment]
1.1rc3 has been released which hopefully fixes the issue.

**Comment by pembo13** [comment]
Just to let others know, with:

CentOS 7.2.1511 (all updates applied)
Python 2.7.5
Gevent 1.0.2

The following code was enough to trigger the error:

```python
from gevent.monkey import patch_all ; patch_all()
import requests
requests.get('https://www.google.com')
```
In my case, I was using Guinicorn with `--worker-class gevent` I just have to remove that for now to get past the error that was being triggered in a view that made a web API call.

**Comment by noilly** [comment]
Workaround suggested by @RyanGWU82 now requires different URLs (as the suggested URLs have since been deprecated by CentOS):

sudo rpm -Uvh --oldpackage http://vault.centos.org/7.1.1503/updates/x86_64/Packages/python-2.7.5-18.el7_1.1.x86_64.rpm \
  http://vault.centos.org/7.1.1503/updates/x86_64/Packages/python-devel-2.7.5-18.el7_1.1.x86_64.rpm \
  http://vault.centos.org/7.1.1503/updates/x86_64/Packages/python-libs-2.7.5-18.el7_1.1.x86_64.rpm

**Comment by zivziv77** [comment]
Hi

I have encountered the same problem and installed 1.1rc3  which seems to solve the problem!

Thanks
