### ISSUE TITLE
why GZIP (zlib) not release greenlet?

### ISSUE THREAD

**Issue by byaka** [gevent/gevent#713]
In multithreaded program zlib release GIL and give second thread to work while compressing.
But in geven- patched it nothing happened.

**Comment by jgehrcke** [comment]
Can you show code? The common mode of operation in gevent is to run single-threaded, and to patch the threading module so that a 'thread' actually is executed as a coroutine (whereas multiple coroutines run within a single OS-level thread!). A coroutine which does not yield back to the hub does not allow for other coroutines to run. At all. Generally, coroutines (greenlets in case of gevent) should perform I/O-intense tasks for taking most advantage of the underlying concept. You should make sure that your CPU-intense task is executed in a different thread (real thread) than your I/O-controlling coroutines run in. Otherwise your I/O operations will experience severe latency issues.

**Comment by byaka** [comment]
example, where i test this
```python
# -*- coding: utf-8 -*-
from gevent import monkey

monkey.patch_all() #COMMENT this line for see like this work in threads

import sys, time, random, threading

class testThis:
   def gzip(self, data):
      from cStringIO import StringIO
      from gzip import GzipFile
      print '%s BEFORE gzip'%(' '*10)
      gzip_buffer=StringIO()
      with GzipFile(mode='wb', fileobj=gzip_buffer) as f: f.write(data)
      dataC=gzip_buffer.getvalue()
      print '%s AFTER gzip'%(' '*10)

def tester():
   while True:
      print '>>> message from another thread/greenlet'
      time.sleep(0.1)

if __name__=='__main__':
   #prepare
   import string
   data=''.join([random.choice(string.ascii_lowercase) for i in xrange(10**8)])
   #start
   threading.Thread(target=tester).start()
   threading.Thread(target=testThis().gzip, args=[data]).start()
   while True: time.sleep(10)
```
example generate some data for compressing (near 700mb) so be patient

without monkey-patching while gzip comperssion program switched to secont 'tester' thread.
but with monkey-patching second greenlet work only when compression finished..

**Comment by jamadden** [comment]
I think @jgehrcke did a good job of explaining what's going on. While `StringIO` and `GzipFile` may release the GIL (allowing other native threads to run), neither of them makes a blocking I/O call that is intercepted by gevent, even when the system is monkey-patched. Therefore, no other greenlet gets to run. (gevent is only going to intercept I/O calls on sockets and pipes, basically.) To get some sort of concurrency out of this code, you need to use native threads (or operate on I/O objects other than `StringIO` that are intercepted by gevent). One possible, non-intrusive, way to introduce threads in a monkey-patched system is to wrap the `StringIO` object with a `FileObjectThread`.
