### ISSUE TITLE
Several tests fail because python lack ssl.PROTOCOL_SSLv3

### ISSUE THREAD

**Issue by czarkoff** [gevent/gevent#735]
Here, on OpenBSD -current python doesn't have ssl.PROTOCOL_SSLv3. This causes several tests for 1.1rc3 fail. Reproducible with python 2.7 from packages.

**Comment by jamadden** [comment]
Which tests and how do they fail? Do you have a log of the test run? Does this impact actually *using* gevent, or just running the tests? I don't have an OpenBSD box laying around to test on.

**Comment by czarkoff** [comment]
It doesn't impact using gevent - outside tests framework there is no single reference to `PROTOCOL_SSLv3`. Judging by my patches, the affected tests are in `greentest/2_7/test_ftplib_py` and in `greentest/2_7/test_ssl_py`. Basically, tests are dying because python encounters construct `ssl.PROTOCOL_SSLv3`, but `ssl` does not have `PROTOCOL_SSLv3` attribute.

**Comment by jamadden** [comment]
Those test files are copies of the stdlib test files (well, `test_ssl.py` has been *slightly* modified to account for running on both < and >= 2.7.9). How does the stdlib deal with that situation? Does OpenBSD ship modified copies of those files, or use the upstream versions? Are gevent's copies out of date?

**Comment by czarkoff** [comment]
We neither ship custom versions of these files nor patch them. I'll have a look at them later.

P.S.: Here is my complete [test log](http://pastebin.com/ifeFEWWW).

**Comment by jamadden** [comment]
It seems that the removal of SSLv3 support is a system-wide change in [OpenBSD 5.8](http://www.openbsd.org/58.html), released in October, so this is likely a new issue. The stdlib tests gevent contains are from 2.7.3, which [predate the commit making SSLv3 optional](https://github.com/python/cpython/commit/3ed7b3cca7b54bd77d243b986dfc67450d464ff4). So, basically either gevent needs to pull in that specific change or update the test files in general. (Though, is SSLv23 still available? Because the stdlib test_ftplib is still using that.)

**Comment by czarkoff** [comment]
Yes, it is a system-wide change. SSLv23 is still available.
