### ISSUE TITLE
SSL3_WRITE_PENDING error with gevent 1.1rc3 + PyOpenSSL

### ISSUE THREAD

**Issue by wolever** [gevent/gevent#736]
I'm still seeing the `SSL3_WRITE_PENDING` error with gevent 1.1rc3 + PyOpenSSL.

To recreate:

```
$ pip install gevent==1.1rc3 pyopenssl gevent-openssl
$ openssl dhparam -out dh.pem 2048
$ openssl s_server -dhparam dh.pem -port 1234 -cert somecert.pem
```

Then run:

```python
from gevent import monkey
monkey.patch_all()

import gevent_openssl
gevent_openssl.monkey_patch()

import gevent
print "gevent version:", gevent.__version__

import OpenSSL
print "OpenSSL version:", OpenSSL.__version__

import socket
from OpenSSL import SSL

while True:
    for cipher in ["SSLv3_METHOD", "TLSv1_METHOD"]:
        print "Cipher:", cipher
        ctx = SSL.Context(SSL.__dict__[cipher])
        sock = SSL.Connection(ctx, socket.socket(socket.AF_INET, socket.SOCK_STREAM))
        sock.connect(("localhost", 1234))

        for x in ["x", "x" * 1024 * 1024 * 5]:
            print "    Writing %s bytes:" %(len(x), ),
            try:
                sock.sendall(x)
            except Exception as e:
                print "ERROR:", e
            else:
                print "OKAY"
        sock.close()
```

On the machines I've tested (OS X 10.10.5, some version of RHEL) it prints:

```
gevent version: 1.1rc3
OpenSSL version: 0.15.1
Cipher: SSLv3_METHOD
    Writing 1 bytes: OKAY
    Writing 5242880 bytes: ERROR: [('SSL routines', 'ssl3_write_pending', 'bad write retry')]
Cipher: TLSv1_METHOD
    Writing 1 bytes: OKAY
    Writing 5242880 bytes: ERROR: [('SSL routines', 'ssl3_write_pending', 'bad write retry')]
```

Note: it seems to happen specifically when there is a delay in the receiving end. On my machine, redirecting the output — `openssl s_server … > /dev/null` — is enough to make all the writes succeed.

Patching the `sendall` method so it's simply repeated calls to `send` appears to be a suitable workaround:

```python
from gevent_openssl.SSL import Connection
def Connection_sendall_fixed(self, buf, flags=0):
    while buf:
        sent = self.send(buf, flags)
        buf = buf[sent:]
Connection.sendall = Connection_sendall_fixed
```

**Comment by jamadden** [comment]
If the fix is in `gevent-openssl`, how is this a gevent issue?

As far as I can see from looking at the code for `gevent-openssl`, it suffers from the same issue described in [issue 317](https://github.com/gevent/gevent/issues/317#issuecomment-159641221). That is, in the event of a socket timeout (which fits with the description that a slow receiver exacerbates the problem) or certain other error conditions, it [computes a *brand new buffer*](https://github.com/pyca/pyopenssl/blob/master/src/OpenSSL/SSL.py#L1278) to pass to OpenSSL's `write` function, even if it was in the middle of a write. That's specifically illegal.

Actually, it looks like it could be worse than that. `gevent-openssl` simply calls `Connection.sendall` in [a loop](https://github.com/mjs/gevent_openssl/blob/master/gevent_openssl/SSL.py#L27) in the event of certain write conditions that indicate full buffers/stalled sockets. Naively, that seems like it could result in sending duplicate data being sent. I would expect the proposed patch to `gevent-openssl` to be more correct than its current approach.

**Comment by wolever** [comment]
Ahhh dang, you're right — I wasn't thinking very hard about this… it is obviously an issue with gevent-openssl, and their `sendall` function is definitely broken. Thanks for taking the time to dig into it. I've opened an issue there.
