### ISSUE TITLE
LoopExit error if monkey-patched after some imports or atexit uses

### ISSUE THREAD

**Issue by nolar** [gevent/gevent#747]
**Briefly:**

If gevent.monkey.patch_all() is called _after_ some imports, it causes LoopExit('This operation would block forever') at the script end.

**Detailed:**

Specifically, this includes imports of IPython & ipdb. It instantiates its HistorySavingThread, which installs atexit handler in constructor. If gevent is monkey-patched after `import ipdb`, for example, every script will fail.

The similar issue also happened with Paramiko (it uses `atexit` for transport threads too), but I cannot reproduce it now. Paramiko has `atexit` handler installed on module import.

Monkey-patching after imports is sometimes useful if it must be done conditionally. For example, if specified on command-line with `--gevent` option to enable "experimental" mode for py.test script, or something like that.

```
import ipdb
import ...

def pytest_configure(config):
    if config.option.gevent:
        import gevent.monkey
        gevent.monkey.patch_all()
```

**Reproduce:**

Here is a script to reproduce this error with 100% probability, which simulates the behaviour of IPython.HistorySavingThread:

```
import time
import atexit
import threading
import gevent
import gevent.monkey


class PostMortemThread(threading.Thread):
    def __init__(self):
        super(PostMortemThread, self).__init__()
        atexit.register(self.stop)

    def run(self):
        time.sleep(1)

    def stop(self):
        self.join()


# # OK:
# gevent.monkey.patch_all()
# PostMortemThread().start()

# NOT OK: gevent.hub.LoopExit: ('This operation would block forever', ...)
PostMortemThread().start()
gevent.monkey.patch_all()
```

**Comment by jamadden** [comment]
Yeah, it's [documented](http://www.gevent.org/intro.html#monkey-patching) that monkey-patching should be the first thing a program does. Otherwise the results can be unpredictable---the state of the system will be mixed. I don't know if there's anything that can be done about this in general.

**Comment by nolar** [comment]
Maybe, gevent should continue monkey-patching other things within python stdlib (`atexit` in this case), so that every issue is gone? One by one, steps by step, going to eventual happiness.

Or maybe change the patching strategy: instead of replacing the whole threading.Thread class, only replace the selected methods. So every library that inherited from this class or remembered it or created the instances, it would be automatically patched too.

Specifically, IPython & Paramiko do nothing special here. This is a very "normal" use-case to use stdlib `atexit` handler to join the threads. Which turns to be monkey-patched.

**Comment by jamadden** [comment]
Interestingly, this is not a problem on Python 3, only on Python 2, because of the way joining threads has changed. Since Python 3 is the future, and the future is now, this could be considered a non-issue :) (Although there may be a subtle bug in gevent's monkey-patching here.)

The trouble is not with `atexit` itself, it's with joining a thread created *before* monkey-patching, *after* the patch has taken place. That's specifically mentioned as a potentially troublesome scenario.

Note that gevent *doesn't* replace the Thread class on Python 2 or Python 3 <= 3.3, it only does so on Python 3 >= 3.4 (though again, future, now, etc).

All of this is to say that there *may* be something gevent can do on Python 2 in certain special cases, but in general, having multiple native threads going before monkey-patching threading is uncharted territory.
