### ISSUE TITLE
Greenlet tree

### ISSUE THREAD

**Issue by mahmoud** [gevent/gevent#755]
At PayPal, we've found it very useful to extend the `gevent.Greenlet` class to support tracking its spawning `Greenlet`. This creates a tree that facilitates many logging and instrumentation scenarios. This helps stitch together stack traces and generally navigate complex Greenlet-spawning paths.

That brings us to the best news, which is that we have a concrete implementation already, production-tested for almost a year now. Overhead is negligible, even in our highest performance use cases (1000+ requests per per second), and references are properly handled.

We're happy to contribute it, if there's interest. If there are questions, or anything we should know before submitting the pull requests, just let us know in the comments, or contact me directly (my work email is in my profile).

(cc @jayalane @doublereedkurt)

**Comment by doublereedkurt** [comment]
Just for reference, this is the additional stuff we wrap around greenlet in live:

https://github.com/paypal/support/blob/master/support/async.py#L38-L60

In addition to the attribute `spawn_parent` which is a weakref back to the spawning greenlet, it also keeps a light-weight stack trace of the spawn point (list of code object and line numbers), and also creates a dictionary shared among the "spawn tree" of greenlets spawned from the same parent.

(The shared spawn-tree local dictionary is used to share state among all the children of a particular request handling greenlet from a streamserver.  This part definitely doesn't belong on the root greenlet class -- it relies on the transition from gevent.greenlet.Greenlet to support.async.Greenlet to partition the spawn-trees from each other.)

Here's an isolated form of the spawn-parent-tracking greenlet:

https://gist.github.com/doublereedkurt/edc5968124c6554a47b6

Something else that we've found helpful:

https://gist.github.com/doublereedkurt/25b48114de216a5e55df

We use this to assign minimized, non-overlapping IDs to greenlets.  This is needed to integrate with existing PayPal infrastructure built around the idea of a small, fixed number of processes or threads as the units of concurrency.  This way the first greenlet to reserve an ID becomes "thread" 1, the second becomes "thread' 2.  If the first one then finishes, the third one will be "thread' 1 again since that spot is free.

It took a couple of iterations to get that right (log-n time insert + removal; hooking weakref callbacks properly).

**Comment by munro** [comment]
I would love to see this contributed!  We get lots of exceptions from `gevent/greenlet.py in get at line 274`, and without the full stack trace it makes it hard to debug the issue.

**Comment by jamadden** [comment]
Is that with 1.1? 1.1 keeps and retries the original stack in that scenario.

**Comment by munro** [comment]
awesome!  I'm on `1.0.2`, I knew I saw a commit to add that in master a bit ago. XD  but I didn't see it when I searched the change log

**Comment by jamadden** [comment]
It was all the way back I. 1.1a1: http://www.gevent.org/changelog.html#a1-jun-29-2015

- (Experimental.) Waiting on or getting results from greenlets that raised exceptions now usually raises the original traceback. This should assist things like Sentry to track the original problem. See issue #450 and issue #528 by Rodolfo and Eddi Linder and issue #240

It was extended in 1.1a2 and maybe more later but those were the big ones 

- (Experimental) Exceptions raised from iterating using the ThreadPool or Group mapping/application functions should now have the original traceback.

**Comment by cookkkie** [comment]
Hello @kurtbrose, the gist links are not working anymore. Do you have a copy please?

**Comment by mahmoud** [comment]
@jamadden That's amazing! Thanks for the followup! Regarding the comments about performance in the commit message, at this low of a level, it can really pay to avoid creating instances of objects. That's why we landed on creating simple lists and then providing utilities for manipulating them. Few application developers work with this level directly, anyways, so that bit of friction is rarely a concern.

In any case, very pleasantly surprised to see #1115 and #1116 land!

**Comment by jamadden** [comment]
> Regarding the comments about performance in the commit message, at this low of a level, it can really pay to avoid creating instances of objects. That's why we landed on creating simple lists and then providing utilities for manipulating them.

I did benchmark that and I found that once I had everything compiled with Cython, the bottleneck was actually in getting `frame.f_code` and `frame.f_lineno`. Everything else compiled into direct C function calls, but that still had to go through generic `getattr` operations.

**Comment by jamadden** [comment]
@mahmoud Is #1116 going to fit your needs, do you think?

**Comment by jamadden** [comment]
>> Regarding the comments about performance in the commit message, at this low of a level, it can really pay to avoid creating instances of objects. That's why we landed on creating simple lists and then providing utilities for manipulating them.

> I did benchmark that and I found that once I had everything compiled with Cython, the bottleneck was actually in getting frame.f_code and frame.f_lineno. Everything else compiled into direct C function calls, but that still had to go through generic getattr operations.

One possible way it could be a bit faster: tuples use a freelist, objects don't. If the greenlet and its stack are short-lived, a freelist could be useful. Cython has a decorator to make objects use freelists, but I wasn't able to get it to work in the .pxd file and quit before I tried an import-mock dance in the .py file.

**Comment by jamadden** [comment]
FWIW, with `python -m perf timeit -s 'from gevent import Greenlet' 'Greenlet()'` I get:

* 3.65us +- 0.17us for the current code
* 3.43us +- 0.19 using a freelist (7% faster)
* 3.04us +- 0.13 using just tuples (12% faster than freelist, 20% faster than current)
* 2.33us +- 0.16us if I stop accessing `f_code` and `f_lineno` from the frame altogether, i.e., that accounts for about 30% of the runtime all by itself

Using a freelist (what I had originally had in mind) turns out to be complicated. The extra .4us from using tuples is small, but may be worth the added complexity when it comes to accessing the stack (if we take the premise that such access is rare).

**Comment by mahmoud** [comment]
@jamadden yeah! talking to @kurtbrose, it does fit the bill, would have totally used this instead of the code from the gists. I do recommend tuples and util functions for the performance boost, but it's not dealbreaking material imo.
