### ISSUE TITLE
c-areas Cython extension doesn't release the GIL

### ISSUE THREAD

**Issue by thedrow** [gevent/gevent#783]
I'm looking into the Cython extension to figure out what is required to write it as CFFI and I noticed that the extension doesn't release the GIL at all although it looks like it is possible in https://github.com/gevent/gevent/blob/master/gevent/ares.pyx#L446 and https://github.com/gevent/gevent/blob/master/gevent/ares.pyx#L406 for example.
Is there a good reason why it's coded this way?
I know this might not matter since we're considering to write this in CFFI alone but until we do, it might be useful to release the GIL during DNS operations.

**Comment by jamadden** [comment]
I believe this is because c-ares is *callback* based. gevent doesn't actually sit there waiting while ares does its thing, gevent passes a callback function to ares, which immediately returns. gevent then goes ahead and takes a gevent-level `Waiter` object to wait for the callback to get returned---which in turn allows the hub to switch to another greenlet. In this way the asynchornous callback nature of ares is transformed into an apparently synchronous blocking interface (basically it's the same pattern gevent uses everywhere, just with a third-party library involved). 

There's thus no real point to trying to drop the GIL because *Python code is going to continue to run* while ares does its thing in the background. At best the GIL would be dropped for the tiny amount of time it takes ares to make the syscall and setup the asynch operation before returning.

**Comment by thedrow** [comment]
CFFI extensions release the GIL automatically whenever you call C code.
I wonder if that will matter if you'll mix gevent with threads. Do you see a disadvantage besides the overhead of releasing the GIL in that behavior? Can a race condition occur for example?

**Comment by jamadden** [comment]
Each native thread has its own hub and loop, which means it also has its own resolver. So the resolver objects should all be local to their own thread, meaning no race conditions (unless the underlying ares library is not properly reentrant, which it should be.)

**Comment by jamadden** [comment]
Unless there's anything more actionable here, can you go ahead and close this please?

**Comment by thedrow** [comment]
Yeh, closing for now.
