### ISSUE TITLE
gevent doesn`t switch while doing ssl connect

### ISSUE THREAD

**Issue by BingoZ** [gevent/gevent#785]
Hi, I find gevet fails to switch while doing ssl connect with python 2.7.10 and the newest release of gevent , no matter whether I use `from gevent import ssl` or `monkey.patch_all(); import ssl`, causing most of the spawns spending Incredibly long time, more than the timeout I set,  to finish the connection.

**Comment by jamadden** [comment]
Do you have a short example that demonstrates the problem?

**Comment by BingoZ** [comment]
Mn...I will try to simplify my code and paste it here, please wait.

**Comment by BingoZ** [comment]
I wrote a test program to test it, codes are blew:

```
import gevent
from gevent import monkey
monkey.patch_socket()
monkey.patch_ssl()
import time
import socket
import ssl

port = 443
timeout = 5
try_ssl = True
thread_num = 1000
# a file in which contains 10000 ips with port 443 opened line by line.
# I use zmap to generate it. zmap -p 443 -N 10000 -o ip_list
fp = open('ip_list','r') 



def connect(ip, port, timeout=5, try_ssl=False):
    if try_ssl:
        try:
            raw_socket = socket.socket(
                socket.AF_INET, socket.SOCK_STREAM)
            raw_socket.settimeout(timeout)
            sock = ssl.wrap_socket(
                raw_socket,
                ssl_version=ssl.PROTOCOL_SSLv23,
                cert_reqs=ssl.CERT_NONE
            )
            sock.connect((ip, port))
            return sock
        except:
            return False
    else:
        try:
            sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
            sock.settimeout(timeout)
            sock.connect((ip, port))
            return sock
        except:
            return False

def get_resp(ip, port, timeout=5, try_ssl=False):
    sock = connect(ip, port, timeout, try_ssl)
    response = str()
    if sock:
        try:
            while 1:
                recv = sock.recv(1500)
                if not recv:
                    break
                response += recv
        except:
            pass

    return response

def gevent_fun(id, fp, port, timeout, try_ssl):
    print 'thread %d started' % id
    while 1:
        line = fp.readline()
        if not line:
            break

        ip = line.strip()

        t0 = time.time()
        get_resp(ip, port, timeout, try_ssl)
        print '%s time used' % ip, int(round(time.time() - t0))
    print 'thread %d stopped' % id


# little test
# t0 = time.time()
# get_resp('133.31.55.11', port, timeout, try_ssl)
# print int(round(time.time() -  t0))


runner_list = list()
for i in range(thread_num):
    runner_list.append(gevent.spawn(gevent_fun, i, fp, port, timeout, try_ssl))
gevent.joinall(runner_list)

```

**Comment by BingoZ** [comment]
The phenomenon I found are:
1. If set `try_ssl=True`, time used are mostly bigger than False. If `try_ssl=False`, time_used printed are no more than 10, but it will rise to even 40 if `try_ssl=True`.
2. I find the cpu is almost free while doing ssl connect.
Maybe it is hasty to say it is related to gevent. I just do not know haw to make ssl connection as effective as tcp connection.Could you please help me?

**Comment by jamadden** [comment]
I think there are a number of things going on here, but I don't think any of them indicate an actual problem with gevent.

First, we can verify that switches are occurring when the call to `sock.connect` is made with a couple different mechanisms. We can use `greenlet.settrace` to monitor all switches and we can also use a context manager to check that a certain block of code does yield. (Both of these techniques are demnstrated [here](http://www.rfk.id.au/blog/entry/detect-gevent-blocking-with-greenlet-settrace/), among other places). In this code, it looks like this (note that I've also simplified it further to be certain we're making SSL connections):
```python
# The maximum amount of time that the eventloop can be blocked
# without causing an error to be logged, in seconds.
MAX_BLOCKING_TIME = 0.1

# A global variable for tracking the time of the last greenlet switch.
_last_switch_time = None

# A trace function that gets executed on every greenlet switch.
# It checks how much time has elapsed and logs an error if it was excessive.
# The Hub gets an exemption, because it's allowed to block on I/O.
def switch_time_tracer(what, (origin, target)):
    global _last_switch_time
    then = _last_switch_time
    now = _last_switch_time = time.time()
    if then is not None:
        blocking_time = now - then
        if origin is not gevent.hub.get_hub():
            if blocking_time > MAX_BLOCKING_TIME:
                msg = "Greenlet blocked the eventloop for %.4f seconds\n"
                msg = msg % (blocking_time, )
                print >> sys.stderr, msg
                traceback.print_stack()
        print "Switched from ", origin, "to ", target, "; blocked", blocking_time

greenlet.settrace(switch_time_tracer)

import contextlib

@contextlib.contextmanager
def check_for_gevent_blocking():
    # Remember the time of last switch before entering the context.
    old_switch_time = _last_switch_time
    print("Preparing to switch")
    yield None
    # If the time of last switch has not changed when exiting the context,
    # then we obviously didn't yield back to the event loop.
    if old_switch_time is not None:
        if old_switch_time == _last_switch_time:
            raise RuntimeError("Code did not yield to gevent")

def connect(ip, port, timeout=5, try_ssl=True):
    assert try_ssl
    raw_socket = socket.socket(
        socket.AF_INET, socket.SOCK_STREAM)
    raw_socket.settimeout(timeout)
    sock = ssl.wrap_socket(
        raw_socket,
        ssl_version=ssl.PROTOCOL_SSLv23,
        cert_reqs=ssl.CERT_NONE
    )
    with check_for_gevent_blocking():
        sock.connect((ip, port))
    return sock
```

Running this on a collection of google and amazon SSL IPs shows me that Python 2.7.11 *is* in fact switching when the SSL handshake needs to read data.

Next, the method of accounting for "time used", the total elapsed time, does not accurately reflect the activity of any one particular greenlet. Because these are non-preemptive tasks, measuring the difference between `t0` and `time.time()` is going to include *all* the time for *all* the other greenlets that got switched to and ran, which could easily be all of them. There's no guarantee about first-come, first-serve or any sort of ordering among competing greenlets.

Note that the more greenlets you spawn concurrently, the more "overhead" is involved in scheduling. It doesn't help that each greenlet is doing *blocking* file I/O (`fp.readline()`). Instead of doing the I/O in each greenlet and manually trying to limit the number of greenlets, I would use a gevent Pool, and make each greenlet do a single task:
```
def gevent_fun(id, ip, port, timeout, try_ssl):
    ip = ip.strip()
    t0 = time.time()
    print 'thread %d started' % id, 'at ', t0
    get_resp(ip, port, timeout, try_ssl)
    print '%s time used' % ip, int(round(time.time() - t0))
    print 'thread %d stopped' % id

from gevent.pool import Pool
pool = Pool(1000)
ips = open('ip_list','r').readlines()
cnt = 0
for ip in ips:
    cnt += 1
    pool.spawn(gevent_fun, cnt, ip, port, timeout, try_ssl)

pool.join()
```

I don't know what kind of services you're trying to scan, but port 443 is typically used for HTTPS. An HTTP server waits for the *client* to send data first before it sends anything in response. If you don't send anything, you'll be at the mercy of the local socket timeout or the remote server timeout and find yourself "blocking" in `sock.recv`. In order to be able to actually make progress on my IPs, I needed to send a request:
```
def get_resp(ip, port, timeout=5, try_ssl=True):
    sock = connect(ip, port, timeout, try_ssl)
    response = str()
    if sock:
        sock.sendall(b'GET / HTTP/1.0\r\n\r\n')
        while 1:
            recv = sock.recv(1500)
            if not recv:
                break
            response += recv

    return response
```

Finally, SSL *does* have overhead during the handshake phase. It requires several extra round-trips on the network to establish the channel. If your network connection to the target has high latency, this can add up to a noticeable amount of time, during which the local CPU has very little load.

**Comment by BingoZ** [comment]
Do you need me to send you the ip_list file?

**Comment by jamadden** [comment]
No, I can't see what that would add.

On Apr 5, 2016, at 23:14, BingoZ <notifications@github.com> wrote:

Do you need me to send you the ip_list file?

—
You are receiving this because you commented.
Reply to this email directly or view it on GitHub
<https://github.com/gevent/gevent/issues/785#issuecomment-206111397>

**Comment by jamadden** [comment]
Do you have any other suspicions of actual problems in gevent, or can you close this issue? I'm not sure that a bug tracker is the right place for any further general discussion, perhaps the mailing list would work better.

**Comment by BingoZ** [comment]
I am very grateful of your specific reply, and I use the method you taught me to check and find gevent seems works well, I also understand what you said about the total elapsed time and thank you for your good advice.
But what confused me is, sometimes  the total elapsed time used for handling some IP while using gevent  is incredibly more  than handle it without gevent( Choose the IP of which the elapsed time is more than 20s, do the same task alone without gevent, you can find it use less time, almost equal to the `timeout` set before), in which case I guess it is because gevent is busy switching and that greenlet may get little cpu resource and wastes much time waiting, then the cpu utilization rate should very high. But in fact cpu utilization rate is not that.
So what is the problem with what I thought?

**Comment by BingoZ** [comment]
Oh, I am sorry to bother you, I will close it after your next comment.

**Comment by jamadden** [comment]
It seems to me you now have the tools to investigate on your own. This issue tracker is for genuine issues, not help requests (though we do assist as we can)

**Comment by BingoZ** [comment]
Ok, thank you for your help.

**Comment by Ivoz** [comment]
@BingoZ its a small chance you might be helped out by using the c-ares resolver, it might be related to DNS.

**Comment by BingoZ** [comment]
@Ivoz Thank you for your follow,  the test code just do simple task of SSL concetion of the given IPs and port 443, and I also capture the packets to verify that it has nothing to do with DNS. In one word, the problem I met is, the multiple SSL connection of IPs and port 443, which should be done very quickly, is being finished using more time with greenlet. I even changed the number of greenlet from 1000 to 500,300 and 100, and find the problem still happens. I am still checking it with the method @jamadden taught me.
