### ISSUE TITLE
Mock object is duplicated inside greenlets

### ISSUE THREAD

**Issue by polosatyi** [gevent/gevent#788]
Hi guys! I use mock for testing my application. Can anybody tell me how can I use mock inside _greenlet_?

```
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from gevent import spawn
from mock import patch


class A(object):

    def process(self):
        pass

    def go_process(self):
        self.process()

    def go_process_inside_greenlet(self):
        spawn(self.process)

a = A()


with patch.object(a, 'process') as mock_object:
    print mock_object.call_count
    a.go_process()
    print mock_object.call_count
    a.go_process_inside_greenlet()
    print mock_object.call_count
```

My results:
```
$ python testapp.py
0
1
1
```

You can see that mock_object was not called inside greenlet.

**Comment by jamadden** [comment]
If you want to see the call count updated, you'll have to yield to gevents run loop so that the new free let gets a chance to run. Try adding a `gevent.sleep` call, or `join` the spawned greenlet (of course you have to return it!)

**Comment by polosatyi** [comment]
Hm... What if I can not wait results of the spawned greenlet in my real application? For example, I can not use `join`, because I need to return web response at once?

**Comment by jamadden** [comment]
How would you test the same thing with threads? More generally, how would you test anything that you invoke only for its side effects? (That's what this must be, because the background greenlet can't do anything with the web response directly; once the main handler returns, the sockets are closed.)

The answer probably has to do with more mocking (for example, you might mock `gevent.spawn` to just run the function immediately in the same greenlet, or you might make it use a pool of greenlets for each request and you wait on that whole pool to finish after you invoke the request and then check the side effects.)

This seems to be a general testing/application design question and doesn't have anything to do with gevent itself.

**Comment by polosatyi** [comment]
Thank you very much. I will mock `gevent.spawn`. I like this way.
