### ISSUE TITLE
Mac OS X Illegal instruction: 4

### ISSUE THREAD

**Issue by dablak** [gevent/gevent#791]
I'm trying to use Gevent in Mac OS X 10.11.3 and I get this error:

```
>>> import gevent
Illegal instruction: 4
```

Python version is 2.7.11

It works fine if I install gevent with the pip option `--no-use-wheel`.

**Comment by jamadden** [comment]
I'm assuming this is gevent 1.1.1?

What hardware are you using? I compiled the wheels on a 2011 Macbook Pro, but I used fairly aggressive optimization settings, so it's possible that if your hardware is different (older?) they might conflict.

**Comment by dablak** [comment]
Yes, gevent 1.1.1

The laptop that I'm using is a MacBook from 2008-2009 I think.

**Comment by jamadden** [comment]
I apologize for this problem. I've given it some thought and decided *not* to pull the wheel off PyPy; instead we'll take more care going forward to make sure more compatible compilation flags are used. I'll leave this bug report open as both a pointer to the workaround and a reminder to automate the flag checking.

The reason I decided not to pull the wheel is that it's by far the most popular binary distribution we publish to PyPI (at least up through 1.1rc3; I can't get more recent statistics than that because the PyPI API is broken), going back all the way to 1.0.2, and every 1.1 release and pre-release. I'm quite sure that most or all of them were also compiled to work only on 2011 or newer hardware. But because this is the first report it indicates that older hardware is less popular, or the workaround is easy enough not to be a problem.

Again I apologize and thank you for bringing this to our attention.

**Comment by dablak** [comment]
Hi, no worries. Actually I've got myself a new Mac (from 2012) and now Gevent works fine when installing normally from pip.

**Comment by kirpit** [comment]
Hi folks,

I am having the same exact issue on a macbook pro Mid 2010. 2.4 GHz Intel Core i5. MacOSX Yosemite 10.10.5 (14F27).

`--no-use-wheel` (actually `--no-binary :all:`) did solve the problem.

**Comment by kezabelle** [comment]
Chiming in as an additional data point of older hardware. I too got ```Illegal instruction: 4``` when using pip to install gevent on a box. As with the others, ```--no-use-wheel``` got it set up OK.

Should it prove useful for future release compilation flag changes, here's a bunch of info from the box.

Hardware reference point:
```
Model Name: Mac Pro
Model Identifier: MacPro5,1
Processor Name: 6-Core Intel Xeon
Processor Speed: 2.66 GHz
Number of Processors: 2
Total Number of Cores: 12
L2 Cache (per Core): 256 KB
L3 Cache (per Processor): 12 MB
```

Python reference point:
```
Python 2.7.11
pip==8.0.3
gevent==1.1.1
```

Operating system:
```
OSX 10.11.3
Darwin 15.3.0 Darwin Kernel Version 15.3.0 x86_64
```

**Comment by anirbanroydas** [comment]
Same problem.
I am using : 
```
Macbook White Mid 2010
Processor : 2.4 GHz Intel Core 2 Duo
Memory : 4 GB 1067 MHz DDR3
OS : OS X El Capitan
```

Problem solved with `--no-use-wheel` or `--no-binary :all: ` (the newer recommended way).

**Comment by ryanchou1991** [comment]
:+1: Cool.! `pip install gevent` with `--no-use-wheel` or `--no-binary :all:` options the issue have been solved.
