### ISSUE TITLE
Allow gevent.signal() to reset the SIGINT handler using SIG_DFL

### ISSUE THREAD

**Issue by renstrom** [gevent/gevent#818]
* gevent version: 1.1.1
* Python version: 2.6.6
* Operating System: OS X

### Description:

I was looking through the [systemd.service(5)](http://man7.org/linux/man-pages/man5/systemd.service.5.html) man page, and refers to [this](https://www.cons.org/cracauer/sigint.html) page for "How to be a proper program". It recommends this when doing cleanup before shutting down when receiving a `SIGINT` signal:

```c
void sigint_handler(int sig)
{
	[do some cleanup]
	signal(SIGINT, SIG_DFL);
	kill(getpid(), SIGINT);
}
```

### What I've run:

This is the stacktrace I'm getting by trying to reset the `SIGINT` handler using this following snippet:

```python
def signal_handler(signum):
    # Do some cleanup
    if signum == signal.SIGINT:
        gevent.signal(signal.SIGINT, signal.SIG_DFL)
        os.kill(os.getpid(), signal.SIGINT)
```

```
Traceback (most recent call last):
  File "/Users/peter/.pyenv/versions/ew/lib/python2.6/site-packages/gevent/hub.py", line 295, in handle
    self.handler(*self.args, **self.kwargs)
TypeError: 'int' object is not callable
Traceback (most recent call last):
  File "test.py", line 33, in <module>
    main()
  File "test.py", line 29, in main
    app.run_forever()
  File "/Users/peter/src/github.com/edgeware/servicelib/python/servicelib/application.py", line 123, in run_forever
    gevent.wait()
  File "/Users/peter/.pyenv/versions/ew/lib/python2.6/site-packages/gevent/hub.py", line 1013, in wait
    return get_hub().join(timeout=timeout)
  File "/Users/peter/.pyenv/versions/ew/lib/python2.6/site-packages/gevent/hub.py", line 694, in join
    waiter.get()
  File "/Users/peter/.pyenv/versions/ew/lib/python2.6/site-packages/gevent/hub.py", line 875, in get
    return self.hub.switch()
  File "/Users/peter/.pyenv/versions/ew/lib/python2.6/site-packages/gevent/hub.py", line 606, in switch
    return greenlet.switch(self)
TypeError: 'int' object is not callable
```

I'm not super sure what to expect, but I kinda feel like it should work kinda of like I hadn't registered the signal handler in the first place...?

**Comment by jamadden** [comment]
`gevent.signal` (which is semi-deprecated---you actually want to use `gevent.hub.signal`) returns an object with a `cancel` method. That is, each call to `gevent.hub.signal` produces a new, independent object, and multiple such objects can be registered for a single signal number; this is very different than how `signal(2)` works or even Python's `signal.signal` function. If you want to stop a registered handler from firing, you need to save the object returned from `gevent.signal` and call `cancel` on it.

Note that this doesn't really make much of a difference as far as "cleanup" goes because libev and/or Python will be handling the *real* signal registrations.

That said, `gevent.hub.signal` can do better type checking of its arguments and raise a TypeError on construction with an invalid handler function.

**Comment by jamadden** [comment]
> Are you saying that what I'm trying to do is more or less redundant for Python applications?

Python applications in general, possibly. gevent applications using `gevent.signal`, probably redundant or even pointless because there can be multiple `SIGINT` signal handlers installed. 

I would just call `sys.exit()` if you want to exit on a `SIGINT`, that's both more reliable and more pythonic (in my opinion).

**Comment by lerks** [comment]
As the OP's link points out, calling `exit` with a (negative) signal code as argument is not equivalent to an exit on a signal. Negative exit statuses are just the shell's way to represent a signal-caused death. The only way to really exit on a signal is to revert catching/ignoring the signal and then fire it.

To convince yourself, you can use the following wrapper:
```
import os
import sys

child_pid = os.fork()

if child_pid == 0:
    os.execvp(sys.argv[1], sys.argv[1:])

child_pid, exit_status = os.waitpid(child_pid, 0)

if os.WIFSIGNALED(exit_status):
    print("Killed by signal %d" % os.WTERMSIG(exit_status)
          + (" (core dumped)" if os.WCOREDUMP(exit_status) else ""))
else:
    assert os.WIFEXITED(exit_status)
    print("Exited with status %d" % os.WEXITSTATUS(exit_status))
```
around the following program:
```
import os
import signal
import sys

#sys.exit(signal.SIGTERM)
#sys.exit(-signal.SIGTERM)
#os._exit(signal.SIGTERM)
#os._exit(-signal.SIGTERM)
os.kill(os.getpid(), signal.SIGTERM)
```
