### ISSUE TITLE
mmap monkey patching

### ISSUE THREAD

**Issue by rom-stratoscale** [gevent/gevent#828]
Our uwsgi service (with gevents) uses mmap python library - apparently we noticed that monkey patching did not work and the task is stuck.
Is there any solution? work around?

Thanks

**Comment by jamadden** [comment]
Can you provide more details on what you're seeing and doing, as requested in the issue template?

**Comment by rom-stratoscale** [comment]
gevent version: 1.0.2
uwsgi version: 2.0.12
python version: 2.7.5
o.s version: centos 7.1

We have a rest server, where one of the handlers perform mmap and and then read data from a stream and write it down into the mapped memory.

The uwsgi confiuration is as following:
uwsgi:
  enable-threads: true
  buffer-size: 65535
  callable: API
  http-timeout: 3600
  http-keepalive: 2
  module: service_api.api
  need-app: true
  procname: service-api
  queue: 100
  queue-blocksize: 20480
  socket-timeout: 60
  gevent: 100
  post-buffering: true

Apparently, that request which calls that flow blocks all other requests from beeing processed and they all stuck in the queue till the first one is completed (which can take approx 40 min).

We did run monkey patching, but apparently, some functions are not patched.

**Comment by jamadden** [comment]
I highly recommend upgrading to gevent 1.1.1, although that should probably be independent of this.

You don't tell me what "read data from a stream" means (is this a socket you opened? A unix pipe? some uwsgi-specific thing?), or what it is that you think is blocking when it shouldn't be, so I have a hard time helping.

I can tell you that a mmap object (assuming you're using the [stdlib class](https://docs.python.org/2/library/mmap.html)) is just a fancy type of mutable string. The kernel handles all disk IO, and gevent is not involved in any way. Note that this is the same as reading or writing a regular file: it may block in the kernel IO, and gevent is not involved in any way. That's the point of `FileObjectThread`, it moves blocking IO out of the main thread and into another, allowing other greenlets to run...unfortunately, there's no trivial way to do that with a mmap object because it's just memory.

**Comment by roeih-stratoscale** [comment]
The task blocks  when we try to write to a block device using the O_SYNC and O_DIRECT flags.
We open a descriptor:
f = os.open(device, os.O_DIRECT | os.O_SYNC | os.O_WRONLY)
and then we write data chunks to it in a loop.
mmap is merely a helper so we can get an aligned buffer and use O_DIRECT.

We noticed that either the os.O_DIRECT flag or os.O_SYNC flag alone is enough for the task to block. Queued requests are not executed between the loop cycles. Calling os.fsync(f) after the loop finishes is also enough for the task to block.

**Comment by jamadden** [comment]
So again, file IO is outside of gevent's purview: there's no opportunity to switch greenlets because the operations are blocking at the kernel level (well, technically, according to POSIX, they're not actually blocking because they tend to have some known upper bound, unlike a network request). If you're using O_DIRECT and/or O_SYNC, then you're asking the kernel to do all the IO directly to disk, skipping buffers and background processing, making the fact that it blocks much more apparent. 

The only thing I can suggest when dealing with true file IO is `FileObjectThread`.

**Comment by jamadden** [comment]
Because this looks like file IO holding up the loop, I'm going to go ahead and close this as cantfix. If there's other information or new information that suggests this is something gevent can and should be dealing with, please feel free to reopen!

**Comment by rom-stratoscale** [comment]
@jamadden thanks a lot for your help - we moved to os.tp_write (from gevent) in order to solve the blocking flow.
