### ISSUE TITLE
When might 1.1.2 be released?

### ISSUE THREAD

**Issue by jakehilton** [gevent/gevent#830]
Question:
Currently running 1.1.1 and and very much looking forward to 1.1.2 (or 1.2.0.. whatever the next version is called) since it would contain a bug fix for a problem that I fight on a daily basis.

Just curious if there is a specific timeline I could look forward to?

Thanks!

**Comment by jamadden** [comment]
Which problem is that?

I ask because there might be a workaround instead. Currently there are only two changes slated for 1.1.2 and they both seemed relatively minor or uncommon to me. Making a gevent release is moderately painful because it takes several hours (builds have to be closely watched and sometimes restarted, etc) so I was waiting for a few more/bigger fixes to go in (which, yeah, is totally subjective).

**Comment by jakehilton** [comment]
It was this one:
https://github.com/gevent/gevent/issues/805

**Comment by jamadden** [comment]
Ah. That hasn't been backported to the 1.1.x branch at this time. It can be patched around at runtime, though:
```python
import gevent
gevent._signal_metaclass.__setattr__ = lambda c, n, v: setattr(gevent._signal_module, n, v)
```

**Comment by jakehilton** [comment]
Ah cool. Ok.. I'll give it a shot.

Thanks

**Comment by jakehilton** [comment]
Any idea when that fix will hit a public version?

**Comment by jamadden** [comment]
Sorry, no idea right now, but aiming for quarterly fix releases seems do-able if there's nothing higher priority to push it up, so maybe august? If you wanted to create a PR containing the commit for #805 plus a change note against the maint/1.1.x branch though, that would help make sure it winds up in that release.

**Comment by jamadden** [comment]
Released.

**Comment by jakehilton** [comment]
I had gotten buried in work and meant to create a PR.. great to see it made it in even though I'm a slacker! 

Thank you for getting this done so quickly.
