### ISSUE TITLE
Should `Timeout` inherit from `Exception` instead of `BaseException`

### ISSUE THREAD

**Issue by dlecocq** [gevent/gevent#838]
* gevent version: 1.1.0, `master`
* Python version: 2.7.11
* Operating System: Ubuntu 14.04

### Description:

We've stubbed our toes on this a number of times now at this point, and I imagine many other have as well. I don't believe it's idiomatic to catch `BaseException` when catching all exceptions, but instead to catch `Exception`. As such, we've often encountered scenarios where we're catching, logging, and re-raising `Excception`s, but find that `Timeout`s don't enter these blocks.

The [Python 2.7 docs](https://docs.python.org/2/library/exceptions.html) say of `Exception`:

> All built-in, non-system-exiting exceptions are derived from this class. All user-defined exceptions should also be derived from this class.

And of `BaseException`:

> The base class for all built-in exceptions. It is not meant to be directly inherited by user-defined classes (for that, use Exception).

Fortunately, of course, there is the workaround of providing a specific exception to be raised when giving an argument to `gevent.Timeout` but it's 1) easy enough to omit that and 2) unpleasant enough to debug that perhaps this deserves some consideration.

BTW, we are huge fans of `gevent` :-)

### What I've run:

```
from gevent import monkey
monkey.patch_all()

import gevent
import time

try:
    with gevent.Timeout(0):
        time.sleep(1)
except Exception as exc:
    print 'Exception: %s' % exc
```

**Comment by jamadden** [comment]
`Timeout` very deliberately *does not* inherit from `Exception`. It inherits from `BaseException` specifically so that it can pass through most generic `catch Exception` blocks and up to the caller that is prepared to deal with a `Timeout` (often gevent itself). If it inherited from `Exception` then it would be caught by too many places and timeouts wouldn't work reliably. 

I don't see this changing, it would be very disruptive to existing code and would substantially change the semantics of timeouts.

**Comment by dlecocq** [comment]
I'll have to take your word for it (re: how disruptive it would be / how likely it would be to be caught unintentionally), though would welcome concrete examples.

So long as it's a 1) conscious design decision and 2) there are ways to get `Exception`-derived exceptions (of course, there are) or to catch the specific class itself.

I figured it bore mentioning because we've found this behavior more unexpected and problematic than I imagine the alternative would be.

**Comment by jamadden** [comment]
One very common concrete example is some sort of job-processing system (queue), where failure of some jobs is allowed. gevent is often used to implement this sort of system for crawling HTTP links. The first several examples I found when searching the web for this type of thing have code very much like this, including the `except Exception` line:
```python
import gevent.monkey; gevent.monkey.patch_all()
def scrape(url):
   try:
      result = requests.get(url)
      return find_links(result)
   except Exception:
      # Oops, we failed, no big deal
      return ()

pool = ...
results = pool.map(scrape, urls)
for result in results:
   if not result:
      # oh well, nothing to see here
      pass
   else: ...
```

So far so good. Now lets make a recursive scraper that spiders the discovered links too:
```python
def recursive_scrape(url):
    for link in scrape(url):
      results.extend(recursive_scrape(link))
```

Notice how each individual URL can fail but the whole task still finishes.

If you, as a consumer of the library providing the `recursive_scrape` function, wanted to place a limit on the total amount of time that each job took, you could easily do so:

```python
def timed_recursive_scrape(url, timeout):
   result = ()
   with Timeout(timeout, False):
       result = recursive_scrape(url)
   return result

pool.map(timed_recursive_scrape,  urls)
```

However, if `Timeout` inherited from `Exception`, you couldn't do this. Instead of percolating up out of `scrape` through `recursive_scrape` and into `timed_recursive_scrape`, they'd (probably) be caught at the lowest level.  Every library author (including libraries that only work with gevent due to monkey-patching) would have to be aware of the Timeout exception and know to handle it specially by letting it be raised---otherwise, timeouts wouldn't be honored; or worse, timeouts would *intermittently* be honored depending on what handlers happened to be active at the time on the call stack.

**Comment by dlecocq** [comment]
As it happens, we both use a job queue and crawl fairly heavily (on the order of hundreds of millions of pages per day).

In the case of the job queue, [qless-py](https://github.com/seomoz/qless-py), we'd like to catch any exception not caught by the job's code and mark the job as failed. It would also like to do the `except Exception as exc` rather than the bare `except` as it would like to inspect the exception. It seems to me that it's not the responsibility of the job queue to know the variety of potentially-non-Exception-inheriting classes that may be thrown by third-party libraries. Instead, it should be the responsibility of the specific job code to know what might be thrown and deal with it accordingly, but that's true whether timeouts inherit from `Exception` or not. The difference is whether they can be caught generally.

I agree that `except Exception` and bare `except`s crop up with some frequency, but they should be used sparingly, carefully, deliberately, and _really_ only when you want to catch all exceptions. Using it carelessly is going to result in all sorts of unexpected behavior at one point or another -- timeouts or no.

And your example can easily be modified to make it work in the case that `Timeout` does inherit from `Exception`:

```python
def scrape(url):
   try:
      result = requests.get(url)
      return find_links(result)
   except Timeout:
      raise
   except Exception:
      # Oops, we failed, no big deal
      return ()
```

It's not that I don't believe that there's a good reason, but I don't believe this stands as a motivating example.

Ultimately what I find problematic about this is that it goes against the prescription of python (that all exceptions should inherit from `Exception`) and forces downstream clients to implicitly be aware of `Timeout` when trying to _really_ catch all exceptions. It's also unintuitive to find that `except Exception` does not actually mean what it is meant to mean.

**Comment by jamadden** [comment]
> And your example can easily be modified to make it work in the case that Timeout does inherit from Exception:

Sure, *if* you happen to have control over that code (and want to introduce a gevent dependency at that level). If it's a third-party, gevent-agnostic library (which I tried to imply), you're out of luck. There are more gevent-agnostic libraries than there are libraries written with it specifically in mind, and one of gevent's strengths is that it tries to be useful with those libraries. Not having timeouts work when using third-party code is as much a  deal breaker as not being able to use sockets would be.

> and forces downstream clients to implicitly be aware of Timeout when trying to really catch all exceptions. 

And vice-versa: They don't have to be aware of Timeout in order for gevent timeouts to still function as intended. Ultimately, the responsibility is on the (single) integrator, not the myriad of third-party libraries.

> It's also unintuitive to find that except Exception does not actually mean what it is meant to mean.

There are other (common) exceptions that aren't caught by `except Exception`, and I think the same rationale applies to Timeout as it does to them. `KeyboardInterrupt` is a near perfect analogy and most of this discussion could simply `s/Timeout/KeyboardInterrupt/g` and still be valid. `SystemExit` is also similar.
