### ISSUE TITLE
Gevent ignores fairly critical build failure, causing perplexing runtime errors.

### ISSUE THREAD

**Issue by PaulFurtado** [gevent/gevent#839]
* gevent version: 1.1.0, 1.1.1, 1.1.2, master
* Python version: 2.7.11, 2.6.6, (probably all versions)
* Operating System: Linux (CentOS 6.6 and 6.7 [gcc 4.4.7 and 5.2.1], and Arch Linux [gcc 6.1.1])  (probably any linux)

### Description:
Background: We had set `CFLAGS=-std=c99` in our build environment to work around a bug in another python project which accidentally used c99 features.

When the build fails due to this, it does not report an error. If you run `CFLAGS=-std=c99 python setup.py build`, it exits with a 0 exit code. If this happens while doing a pip install without verbose output turned on, you never notice the failure.

If you try to start gunicorn with a build like this, it fails with an error that clock_gettime cannot be found, then attempts to compile something with gcc and fails because it can't find libev.h. Additionally, if you uninstall the cffi package from the virtualenv, it throws a few C errrors, but gunicorn does manage to start.

Build log is here: https://gist.github.com/PaulFurtado/c9a0118e2729e42ff7a45849127ba431
gcc shows some syntax errors, choking on a couple of C++ bits.

And here's the run log for the bad build: https://gist.github.com/PaulFurtado/5a4dadcfb6cc9843300b206929a7df9f

So I guess, my first question is: why does gunicorn succeed at starting when you uninstall cffi in this situation? Is there some sort of fallback mode if cffi is not detected?

But anyway, I think the biggest bug here is that the build wasn't vocal enough about this failure. A lot of time could have been saved if this build had failed more loudly.

Additionally, I found it quite surprising that it would attempt to run gcc at runtime. Is that intentional?

A fair response to this bug would probably be "don't give the compiler bad arguments", but not knowing the internals of gevent, I figure there may be something worth fixing here.

Thanks!

**Comment by jamadden** [comment]
`std=c99` shouldn't be a problem for gevent. In fact, setting that compiler flag has been used as a workaround for problems on OS X [several times](https://github.com/gevent/gevent/issues?q=std%20c99).

I may be missing something, but *do not* see any actual problems with the build log. I do see that the c-ares extension doesn't build (because of `hostent`), but that extension is optional and not needed to start and use gevent. I also see that CFFI is *not* installed during the build, because setuptools complains that `cffi_modules` is an unknown keyword. However, the `corecext` module that gevent *prefers* on CPython appears to build successfully.

The run log shows gevent trying to import the CFFI-based module. This indicates that CFFI is now installed (but wasn't at build time); CFFI does have the behaviour of building on-demand, at least in certain versions. If you don't want that, either have CFFI installed at build time, or not installed at all. 

More importantly, though, the `corecext` module couldn't be imported for some reason. If it could have been imported, you wouldn't have this problem and the CFFI module wouldn't be used at all (because the `corecext` module is preferred for CPython). You can force the CFFI module to be ignored when the `corecext` module isn't available and CFFI is installed by setting an (**undocumented**) environment variable (`GEVENT_CORE_CEXT_ONLY`); this can lead to a more  helpful traceback that shows why the expected `corecext` module couldn't be imported.

Note that gevent distributes manylinux1 compatible wheels for Python 2.7 that should be usable on any Linux x86[-64] platform, and these include both the `corecext` extension and the CFFI extension. Using these wheels when possible can save build time and be more repeatable.

I would add that Python 2.6 is *not* supported by master or 1.2, nor is the CFFI module tested on Python 2.6 for any gevent release. Python 2.7 is the most heavily tested platform for gevent 1.1.

**Comment by jamadden** [comment]
Since there's been no updates, I'm going to close this. Please feel free to re-open if there are any updates.
