### ISSUE TITLE
Mask .kill() in greenlet : feature proposal

### ISSUE THREAD

**Issue by sebastien-petitdemange** [gevent/gevent#846]
* gevent version: 1.1
* Python version: 2.7
* Operating System: Linux

### Description:

In some cases, we would like to prevent `.kill()` to interrupt our critical code sections, something similar in spirit to `sigprocmask` but for greenlets.

There is a [question](http://stackoverflow.com/questions/39207303/how-to-mask-kill-on-a-gevent-greenlet-kill-protection) about that on stackoverflow.

### Proposal:

In order to achieve this functionality here is the code we have implemented for now:

```
from gevent import greenlet
import gevent
import gevent.event
from gevent.hub import Waiter
import time

MASKED_GREENLETS = dict()

class KillMask:
    def __init__(self):
        self.__greenlet = gevent.getcurrent()

    def __enter__(self):
        self.__func, self.__exception, self.__waiter = None, None, None
        MASKED_GREENLETS.setdefault(self.__greenlet, set()).add(self)

    def __exit__(self, *args, **kwargs):
        MASKED_GREENLETS[self.__greenlet].remove(self)
        if MASKED_GREENLETS[self.__greenlet]:
            return
        if self.__func:
            self.__greenlet.parent.loop.run_callback(self.__func, 
                                                     self.__greenlet,
                                                     self.__exception, 
                                                     self.__waiter)

    def set_kill(self, func, exception, waiter):
        self.__func = func
        self.__exception = exception
        self.__waiter = waiter
        

saved_kill = greenlet._kill

def _patched_kill(greenlet, exception, waiter) :
    masks = MASKED_GREENLETS.get(greenlet)
    if masks:
        for m in masks:
            m.set_kill(saved_kill, exception, waiter)
    else:        
        saved_kill(greenlet, exception, waiter)

greenlet._kill = _patched_kill
```

Usage:

``` 
def f() :
    with KillMask():
        t0 = time.time()
        gevent.sleep(1)
        with KillMask():
          gevent.sleep(1)
        print time.time()-t0
    gevent.sleep(10)

t = gevent.spawn(f)
gevent.sleep(0.1)
t.kill(ValueError)
```

We can see the code under `KillMask` context manager is not interrupted by `.kill()`, but after it executed the "protected" code.

What do you think of this ?

Any advice to make this better or any work around would be really appreciated. We also need to make it work for `killall` and other possible cases ?

Thanks in advance for your attention !

**Comment by jamadden** [comment]
I'm not especially enthusiastic about such a feature for reasons I can't exactly put my finger on. Perhaps because it makes it easy to inadvertently create greenlets that can't be killed, or perhaps because it makes the already rather nebulous API contract of `.kill` even less reliable and context dependent.

Or perhaps it's because I don't see that this really actually solves the problem of "protecting a critical section." Exceptions like `MemoryError` can still be thrown by seemingly innocuous operations, so there's no guarantees even without the presence of `.kill`.

**Comment by sebastien-petitdemange** [comment]
You've right our proposition just prevent to be killed by an other task and doesn't protect for exception like MemoryError. But it's exactly what we need.
Without the patch, the task raised the exception send by the .kill when it enter in the gevent loop. But sometime it's not a good place to leave the task.
To illustrate here is a simple example:
```
class EchoServer(object):
    def __init__(self):
        self._message_nb = 0
        self._listen = gevent.spawn(self.listen)

    def stop(self):
        self._listen.kill()

    def listen(self):
        tcp = socket.socket(socket.AF_INET,socket.SOCK_STREAM)
        tcp.setsockopt(socket.SOL_SOCKET,socket.SO_REUSEADDR,1)
        tcp.bind(("",30000))
        tcp.listen(16)
        while 1:
            newSocket, addr = tcp.accept()
            gevent.spawn(self.client_read,newSocket)

    def client_read(self,client):
        while 1:
            try:
                raw_message = client.recv(16 * 1024)
            except:
                break
            
            gevent.sleep(0.5)

            if raw_message:
                for message in raw_message.strip().split('\n'):
                    self._message_nb += 1
                    client.sendall('ECHO: %s (%d)\n' % (message,self._message_nb))
            else:
                break
            

class Client(object):
    def __init__(self):
        self._socket = socket.socket(socket.AF_INET,socket.SOCK_STREAM)
        self._socket.connect(('localhost',30000))
        
    def echo(self,message) :
        with KillMask():
            self._socket.sendall(message + '\n')
            return self._socket.recv(16 * 1024)

if __name__ == "__main__":
    s = EchoServer()
    c = Client()
    t1 = gevent.spawn(c.echo,'First message')
    gevent.sleep(0.1)
    t1.kill()
    t2 = gevent.spawn(c.echo,'Second message')
    print t2.get() # This should return "ECHO: Second message (2)
    s.stop()
```
Without the patch, t2.get() will return the first message.
Is there a way to archive the same result with gevent?
Thanks in advance for your attention !

**Comment by jamadden** [comment]
The "kill mask" in this last example seems like a bandaid. The underlying problem is not solved, and other exceptions like the aforementioned MemoryError can still lead to the same results. Indeed, it seems to me that this entire example is basically built on race conditions. 

If there's supposed to be an explicit request/response ordering in a protocol, I suspect the "proper" fix is to explicitly model that at the application level. For a rough example, use only one greenlet to communicate and have it pull its input from a Queue and produce its output into another Queue.

**Comment by sebastien-petitdemange** [comment]
The only think I tried to illustrate with this simple example is that the socket contains the previous message if we .kill the task between the send and the recv command. If you look closer you will see that there is no race condition.
We need to be able to .kill (stop) a task and ensure it's state. In the previous example, be sure that request/response is completed. Is there an other way to do that?

I understand your proposition but actually in our case we can not change the protocol on the server side.

**Comment by jamadden** [comment]
> we can not change the protocol on the server side.

I'm not suggesting changing the protocol, I'm suggesting changing your implementation of it.

> We need to be able to .kill (stop) a task and ensure it's state. In the previous example, be sure that request/response is completed. Is there an other way to do that?

How would you write your code to be robust to a MemoryError? Or a KeyboardInterrupt or any other exception? Do the same thing here. It might involve try/finally, if you can't use a more robust implementation in the first place.

**Comment by mguijarr** [comment]
Hi Jason,

First of all thank you very much for your time considering this proposal. We really appreciate it.

I think the discussion deviated a bit from the original idea behind the 'kill mask' feature and maybe I can explain what we are after with an example to make it more clear. Hopefully you can give us some advice to do it differently if you still think 'kill mask' is a rather bad idea.

We are developing a library to control scientific data acquisition devices, some of them being accessed through serial line. The problem we have is the following: if a library user kills (using `.kill()`) a greenlet that is communicating with a serial line device, a lot of havoc can happen. Imagine the exception happens after sending a command to the serial line device but before reading its answer, there is no reliable way to recover ; doing a "flush" in a `try`...`finally` does not guarantee the answer won't be sent a few milliseconds later by the serial line device (which can be quite slow to answer).

It's a more complicated scenario than with a TCP connection - in the case of TCP, closing the socket is maybe the best option since renewing the connection would work fine in term of communication with the instrument.

So here is why we would like to be able to mask `.kill()`: to have a chance to properly "end" a communication with a serial line device, without being interrupted at a bad moment.

**Comment by jamadden** [comment]
It's not clear to me why that can't be handled the same way *any other exception* would be handled, then:

```python
# Very rough sketch
state = None
try:
  self.thing.send()
  state = 'sent'
  self.thing.read()
  state = 'read'
finally:
  if state == 'sent':
    # we got here because something raised an exception before we 
    # read our response. Try again, let the exception be raised
    # as normal
    self.thing.read()
```

**Comment by mguijarr** [comment]
There is probably something I don't understand regarding `.kill()`, then.

If `self.thing.send()` is in fact calling `.sendall()` on a monkey-patched socket object, the exception from
`.kill()` can be raised within the `.sendall()` method, right ? 
In this case, there is no way to know what has been sent ; it can be incomplete and `.read()` in `finally` won't work... Maybe I am overlooking something ?

I am also worried by the possibility of a second `.kill()` issued while code execution is in the `finally` block: the read or send operation can be interrupted, and it seems to me we are back to the initial problem.

**Comment by jamadden** [comment]
*All* of that holds true for *many* kinds of exceptions, though, not just the exception raised by kill. Kill is not particularly special in this way. Transient IO errors could result in `sendall` raising an exception, as could memory errors, or the user hitting Ctrl-C, etc.

**Comment by sebastien-petitdemange** [comment]
We are facing the same problem that is described in the oracle documentation. And I know by experience that it's very difficult to kill/stop a thread in a safe way if it mixed with other "real" exception.
The oracle documentation suggest to replace kill/stop operation with a variable which stop the thread. To manage this, we have to define a "safe_stop" method for all tasks in our project. This is doable but a little bit heavy. Our proposition with the KillMask use only the gevent task interface (.kill) and define safe kill point. To me, we do the same thing as oracle suggest with a different approach. Am I wrong?

**Comment by jamadden** [comment]
The point I see in the Java documentation is that you must *design* code to be safe. The task itself should be safe as should the ways of interacting with it. If you're going to allow it to be killed, then design it to handle that in the same way you would handle any exception. Otherwise, provide an alternate task-specific interface if you can't be safe in the first place. 

The equivalent of the `kill` method is Java is deprecated because people weren't designing code to be safe, and the Java culture doesn't have the "consenting adults" philosophy that the Python culture does.

This discussion seems to be going in circles.

**Comment by sebastien-petitdemange** [comment]
On 09/06/2016 10:57 AM, Jason Madden wrote:
> The equivalent of the `kill` method is Java is deprecated because people weren't designing code to be safe, and the Java culture doesn't have the "consenting adults" philosophy that the Python culture does.
> 
To me they deprecate the usage because it's difficult to get it right.

> This discussion seems to be going in circles. 
I'm fully agree. You stay focus on exception and code safe. An we try to
talk about a safe kill zone. How can we understand each other?

Even if .kill send at the end an exception, do we have to manage it the
same way as a MemoryError? I would say no.

If you mask the kill method, you have *only* to manage the tricky part
when you get a *real* exception like MemoryError.

**Comment by jamadden** [comment]
> If you mask the kill method, you have *only* to manage the tricky part
> when you get a *real* exception like MemoryError.

The main point that I keep trying to make is that if your code is unsafe, *it's unsafe*. If it can't handle being killed, it can't handle a MemoryError or other exception. Stopping it from being killed in this way is not a solution, it's only a band-aid.

This doesn't seem to be a productive discussion anymore. It's probably best to end it before tempers begin to fray :)

**Comment by sebastien-petitdemange** [comment]
Your are right but we can mix
```
with KilMask:
    try:
        #do stuff
    except:
        # manage the real exception
        raise
```
Obviously your are not familiar with *sigprocmask* and *pthread_kill* ;)
I'm really sorry to bother you but it miss some tools around the *kill* method.

You are right again, you can close the issue.
Thanks again for your attention.

**Comment by jamadden** [comment]
> Obviously your are not familiar with sigprocmask and pthread_kill ;)

I am, actually: `sigprocmask` can't block all signals, so you still have to deal with `SIGKILL` and `SIGSTOP` :)

Thanks for this discussion, it's been interesting (and civil!).
