### ISSUE TITLE
Socket hang under Windows 10 / Linux subsystem

### ISSUE THREAD

**Issue by HelloZeroNet** [gevent/gevent#847]
* gevent version: 1.1.2
* Python version: 2.7.12
* Operating System: Windows 10 / Linux Subsystem

### Description:

I was experimenting with Windows 10 new Linux subsystem and I was impressed by ~50% the speed boost vs native Windows Python (pystone 260k vs 180k), but unfortunately for some reasons gevent seems not working well there.

### What I've run:

```python
import gevent
import gevent.monkey

gevent.monkey.patch_all()

import urllib2
import time

def request(url):
	try:
		print "Get", url
		res = urllib2.urlopen(url).read()
		print "Result to", url, len(res)
		return res
	except Exception, err:
		print "Error requesting", url, err

def checker():
	while 1:
		s = time.time()
		time.sleep(0.05)
		if time.time() - s > 0.06:
			print "Gevent block detected: %.3fs" % (time.time() - s)

gevent.spawn(checker)
s = time.time()
threads = []
for url in ["http://zeronet.io", "http://1.2.3.4", "http://google.com"]:
	threads.append(gevent.spawn(request, url))

gevent.joinall(threads, 2)
print "Taken: %.3fs" % (time.time()-s)
```

Output:

```
$ python test_gevent.py
Get http://zeronet.io
Get http://1.2.3.4
Get http://google.com
Gevent block detected: 21.012s
Taken: 21.013s
$
```

**Comment by jamadden** [comment]
Thanks for bringing this up. WSL is an interesting technology. 

A difference in Pystone values is quite surprising, because Pystone does no IO and doesn't interact with the operating system itself (other than the way in which Python normally would interact for memory management purposes and of course the usual process scheduling). I would tend to guess this is more a difference of how the Python binaries were compiled (e.g., 64 vs 32 bit, and the compiler and compiler options used).

That said, I don't find the apparent "blocking" to be all that surprising. We know that many of gevent's test cases require substantial extra amounts of time on Windows due to the way timers and IO events work there, and we experience much more variability there then we do on a native POSIX platform. Adding a layer on top of the Windows kernel to emulate linux syscalls seems unlikely to make that any better (as I understand it, linux syscalls are mostly just transformed into their native Windows equivalents).

Like I said, WSL is a neat technology, but given that WSL is [very definitely a beta, and intended for developers---not production](https://msdn.microsoft.com/en-gb/commandline/wsl/faq) I'm personally not interested in spending time debugging it or optimizing its performance. 

Unless we can test it on Appveyor, I'm also sorry to say that I don't see gevent accepting any PRs specifically for this platform.
