### ISSUE TITLE
After upgrade to gevent 1.1.2, appears lots of timeout

### ISSUE THREAD

**Issue by MrKiven** [gevent/gevent#853]
* gevent version: 1.1.2
* Python version: 2.7.x
* Operating System: Linux version 3.10.0-229.el7.x86_64 (builder@kbuilder.dev.centos.org)

### Description:
we use gunicorn 19.3.0. After we upgrade gevent to 1.1.2, there appears lots of timeout.

here's traceback:
```
File "/srv/ves/biz.keeper/.venv/lib/python2.7/site-packages/thriftpy/transport/socket.py", line 108, in read#012
    buff = self.sock.recv(sz)#012  
File "/srv/ves/biz.keeper/.venv/lib/python2.7/site-packages/gevent/_socket2.py", line 280, in recv#012
    self._wait(self._read_event)#012  
File "/srv/ves/biz.keeper/.venv/lib/python2.7/site-packages/gevent/_socket2.py", line 179, in _wait#012
    self.hub.wait(watcher)#012  
File "/srv/ves/biz.keeper/.venv/lib/python2.7/site-packages/gevent/hub.py", line 630, in wait#012
    result = waiter.get()#012  
File "/srv/ves/biz.keeper/.venv/lib/python2.7/site-packages/gevent/hub.py", line 878, in get#012
    return self.hub.switch()#012  
File "/srv/ves/biz.keeper/.venv/lib/python2.7/site-packages/gevent/hub.py", line 609, in switch#012
    return greenlet.switch(self)#012timeout: timed out
```

we use gevent 1.0.2 before, but won't raise so many timeout error.

I see changelog about 1.1.2:

```
Python 2: sendall on a non-blocking socket could spuriously fail with a timeout.
```

I don't know if connected to this?

**Comment by MrKiven** [comment]
@jamadden

**Comment by jamadden** [comment]
I'm afraid "using a third-party network library inside a gunicorn process" doesn't give me a lot to go on; there's a lot of places that could be setting/adjusting timeouts there. Can you simplify to produce a [short example](http://sscce.org) that demonstrates a change between gunicorn 1.0 and 1.1?

It is entirely possible that due to improvements/changes in gevent's internals, certain operations which were just at the *edge* of timing out before are now exceeding that value. So if you're in control of the read timeout for this socket, you might try increasing it.

FWIW, this isn't really ringing any other bells for me. I don't think the (fixed) issue with `sendall` applies here since the stack trace is on a `recv` call.

**Comment by jamadden** [comment]
Closing in triage for 1.2a1 and since there has been no new information in two months. Feel free to reopen if there is more info.
