### ISSUE TITLE
Implementation for threading.Condition?

### ISSUE THREAD

**Issue by coleifer** [gevent/gevent#859]
* gevent version: 1.x
* Python version: 2.7
* Operating System: Linucks

### Description:

I was wondering if there were any reason that the `threading.Condition` object from the standard library's `threading` module were excluded from gevent's API? I understand that such a class is "high level" and could be implemented using the existing gevent primitives, but to a regular end-user such as myself, I was surprised to find this class missing.

The idea behind `Condition` objects is to synchronize access to shared state, such that one group of threads might be interested when the state of some object changes. Those threads would be the "waiters". Another thread or threads might change the state in some way, then notify one or all of the waiters using `notify()` or `notifyAll()`. Producer/Consumer is one workflow typically used in examples, but there are some cases where a `Condition` maps really nicely to what you're trying to accomplish.

### My use-case

So in my application I'm serializing queries to the database. There's a dedicated thread (or greenlet) which is pulling work from a queue, executing it, and then informing the caller that the results are now ready.

The caller can access this data in one of two ways. It can block, in which case I use a simple `Event` to indicate when the query is done. Alternatively, the caller can attach a callback and then continue on its merry way. In the callback scenario, the callback function would be a "waiter" on the state of the query results. The query executor would then "notify" the "waiter" using a `Condition`.

### What I've run:

Not really applicable as this is more of a feature request or open-ended question.

**Comment by jamadden** [comment]
`threading.Condition` is based on `RLock`. `RLock` is monkey-patched by gevent, so `Condition` is too and everything just works.

**Comment by coleifer** [comment]
Right, I just wondered if the gevent implementation would be different in certain ways. For instance, the Event object is implemented in gevent though it also exists in threading. Furthermore, it may not be desirable to always monkeypatch threading.

**Comment by jamadden** [comment]
One or the other of them is a primitive (stdlib Event is implemented by stdlib Condition), so they're not both necessary. Event is implemented by gevent because it's the primitive that makes the most sense for gevent (and its used internally).

From what I can tell, the primary use of gevent is via-monkeypatching.

**Comment by jamadden** [comment]
A counter example to this is #872, where `subprocess.run` was implemented natively in gevent, despite working correctly when monkey-patched. There were a couple of reasons for this.

First, it makes this API available to previous versions of Python.
This paves the way towards using it to simplify the nightmarish tangle of code that is `gevent.subprocess` (see #748).

Second, in order to do that, it did need some specific implementation tweaks to work with the slightly different semantics of timeouts in Py2 vs Py3.

It's not clear to me that reasons like that would apply here.

Thanks for this discussion. I'm going to go ahead and close this issue since there's been no discussion in over a month in triage for 1.2a1.
