### ISSUE TITLE
gevent.os.waitpid is not cooperative

### ISSUE THREAD

**Issue by sublee** [gevent/gevent#878]
* gevent version: 1.1.2
* Python version: 2.7.11
* Operating System: Ubuntu 16.04

### Description:

The documentation tells me that `gevent.os.waitpid` can work cooperatively for pids which forked by `gevent.os.fork_and_watch`.  But it doesn't.

I think this function should call `Hub.wait` to wait the child watcher without thread blocking.  However it calls just the original `os.waitpid`.  Of course, it is not cooperative.

Am I right?  Then I will make a patch for you guys.

### What I've run:

I used `ticks` to detect the main thread blocking.  If we can't the ticks, there's blocking.

Ticks will be paused at `gevent.os.waitpid`:

```python
import gevent
import gevent.os

@gevent.spawn
def ticks():
    while True:
        gevent.sleep(0.1)
        print('.')

# You can see ticks.
gevent.sleep(1)

pid = gevent.os.fork_and_watch()
if pid:
    # The main thread is blocking.  You can't see ticks.
    print(gevent.os.waitpid(pid, 0))
else:
    gevent.get_hub().destroy(destroy_loop=True)
    gevent.sleep(3)
```

When I call `Hub.wait` instead of `gevent.os.waitpid`, it works well:

```python
if pid:
    watcher = gevent.os._watched_children[pid]
    gevent.get_hub().wait(watcher)
```

**Comment by jamadden** [comment]
You are quite correct in that the documentation is very misleading: it is only cooperative in the WNOHANG case (which was by far the common case we were trying to solve).

Simply having the hub `wait` on the existing watcher won't work, because the watcher is already started in order to call `_on_child`; asking the hub to wait on it destroys this. The calling of `_on_child` is critically important because of the `callback` that can be provided to `fork_and_watch`. That callback is how the `gevent.subprocess` module is implemented, so forgetting to call it breaks `Popen` and the other `subprocess` APIs.

Now, we could call `_on_child` ourself, of course, after waiting, making sure to provide the callback, captured *before* we waited:
```
   cb = watcher.callback
   args = watcher.args
   get_hub().wait(watcher)
   cb(*args)
```

It's a little ugly, but it works. *Mostly*. There are edge conditions that have to be handled. For example, what if `wait` raises a timeout error or some other exception? Then we have to restart the watcher (if the child is still around) or otherwise cleanly determine that it's not and still call the callback. It's a little racy, which is a bad thing. Any change would have to avoid races like that.

I also seem to recall that there were issues in the stdlib unit tests if we didn't call `waitpid`; again, due to races, I think. I can't remember for sure, I'd have to re-run them.

**Comment by sublee** [comment]
So now we can use `waitpid` cooperatively although we don't set `WNOHANG`.  That's cool!  Thank you.
