### ISSUE TITLE
Despite having gevent installed, Python returns that it isn't

### ISSUE THREAD

**Issue by binhash** [gevent/gevent#899]
* gevent version: gevent 1.1.2
* Python version: Python 3.5.2
* Operating System: Mac OSX Yosemite 10.10.5

### Description: I have gevent and greenlet installed, but when I try importing them, Python returns that I don't have it. 

```
I'm just trying to get this error resolved, and so far, I've uninstalled gevent, reinstalled it, and checked if it was installed, to which it was. 
```

### What I've run: import gevent, simple

```
Mac-406c8f24db65:src declan$ pip install gevent
Collecting gevent
  Using cached gevent-1.1.2-cp35-cp35m-macosx_10_6_intel.whl
Requirement already satisfied: greenlet>=0.4.9 in /Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages (from gevent)
Installing collected packages: gevent
Successfully installed gevent-1.1.2
Mac-406c8f24db65:src declan$ pip install greenlet
Requirement already satisfied: greenlet in /Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages
Mac-406c8f24db65:src declan$ python grabber.py 
Traceback (most recent call last):
  File "grabber.py", line 23, in <module>
    import gevent
ImportError: No module named gevent
```

**Comment by jamadden** [comment]
Since OS X doesn't ship with Python 3.5, I'm assuming you're using the python.org installers to install python in /usr/local/? (The macports installation uses a different sys.path, and presumably homebrew does as well, but that's just a guess.)

I suppose it's possible that there's something wrong with the posted wheel, but I can't reproduce a problem. So this seems more likely to be a generic python path type issue.
```
$ /usr/local/bin/python3.5 -m venv /tmp/gtest
$ cd /tmp/gtest
/tmp/gtest
$ bin/pip install gevent
Collecting gevent
  Downloading gevent-1.1.2-cp35-cp35m-macosx_10_6_intel.whl (764kB)
    100% |████████████████████████████████| 765kB 659kB/s
Collecting greenlet>=0.4.9 (from gevent)
Installing collected packages: greenlet, gevent
Successfully installed gevent-1.1.2 greenlet-0.4.10
$ bin/python -c 'import gevent; print(gevent)'
<module 'gevent' from '/private/tmp/gtest/lib/python3.5/site-packages/gevent/__init__.py'>
```

- Are you sure that the "pip" and "python" commands point to the same installation? AFAICS, the "python" command installed by the python.org installer is just called python3.5 or python3:
```
$ pkgutil --bom python-3.5.2-macosx10.6.pkg
/tmp/python-3.5.2-macosx10.6.pkg.boms.Khcvbg/Python_Framework.pkg/Bom
/tmp/python-3.5.2-macosx10.6.pkg.boms.Khcvbg/Python_Applications.pkg/Bom
/tmp/python-3.5.2-macosx10.6.pkg.boms.Khcvbg/Python_Command_Line_Tools.pkg/Bom
/tmp/python-3.5.2-macosx10.6.pkg.boms.Khcvbg/Python_Documentation.pkg/Bom
$ lsbom -p f /tmp/python-3.5.2-macosx10.6.pkg.boms.Khcvbg/Python_Command_Line_Tools.pkg/Bom | grep python
./python3
./python3-32
./python3-config
./python3.5
./python3.5-32
./python3.5-config
./python3.5m
./python3.5m-config
```
- Do you get the same results using a fresh virtual environment?

**Comment by binhash** [comment]
Does 
`
Mac-406c8f24db65:~ declan$ pkgutil --bom /Users/declan/Downloads/python-3.5.2-macosx10.6.pkg 
/tmp/python-3.5.2-macosx10.6.pkg.boms.so7eUE/Python_Framework.pkg/Bom
/tmp/python-3.5.2-macosx10.6.pkg.boms.so7eUE/Python_Applications.pkg/Bom
/tmp/python-3.5.2-macosx10.6.pkg.boms.so7eUE/Python_Command_Line_Tools.pkg/Bom
/tmp/python-3.5.2-macosx10.6.pkg.boms.so7eUE/Python_Documentation.pkg/Bom
Mac-406c8f24db65:~ declan$ lsbom -p f /tmp/python-3.5.2-macosx10.6.pkg.boms.so7eUE/Python_Command_Line_Tools.pkg/Bom
.
./2to3
./2to3-3.5
./idle3
./idle3.5
./pydoc3
./pydoc3.5
./python3
./python3-32
./python3-config
./python3.5
./python3.5-32
./python3.5-config
./python3.5m
./python3.5m-config
./pyvenv
./pyvenv-3.5
` count?

**Comment by jamadden** [comment]
I don't understand what you're trying to tell me by listing the BOM. That's just the contents of the installer.

**Comment by binhash** [comment]
I... I'll be blunt here. I have no idea what I'm doing, I'm new to Python, I thought it'd be something simple. I'm not sure what you mean by a virtual environment.

**Comment by jamadden** [comment]
That's OK 😄 This isn't really the place for an introduction to python environments and installing Python packages; you might try the [python-list mailing list](https://mail.python.org/mailman/listinfo/python-list) for more help.

I can give a quick summary, though. A virtual environment is an isolated python system, almost like a completely separate install. It has its own `python` command and its own `pip` command. It's highly recommended to use separate virtual environments for each of your projects---even scratch projects and "just playing"---(and *not* installing packages into the system python) so that they don't conflict and it's easier to keep track of exactly what's installed and uninstall everything for a project all at once (by deleting the virtual environment).

The steps I showed [above](https://github.com/gevent/gevent/issues/899#issuecomment-264700136) are enough to get started:


1. Create a directory to hold the virtual env
```
$ mkdir /path/to/venv
```
2. Make that a virtual environment
```
$ python3.5 -m venv /path/to/venv
```
3. That directory now has a `pip` command to install packages, and a `python` command to use them
```
$ /path/to/venv/bin/pip install ...
$ /path/to/venv/bin/python 
```

In your specific case, I suspect that the `pip` and `python` you're using are not connected. I would *guess* that the `python` you're getting is the system python, `/usr/bin/python` and not the one you expect. `which pip` and `which python` will probably give you very different paths. You can probably make things work by using fully-qualified paths, e.g., `/usr/local/bin/pip3` and `/usr/local/bin/python3`...but the virtual environment approach is definitely the way to go.

**Comment by binhash** [comment]
Ah, makes sense! So, then, from here, try installing `gevent` by `pip` in that environment?

**Comment by jamadden** [comment]
Yes, like in the full example I posted above.

**Comment by jamadden** [comment]
If there's nothing else here can you close this?

**Comment by binhash** [comment]
Oh, right, got it. 
Thanks for the help!
