### ISSUE TITLE
Constantly growing number of active threads when using logging

### ISSUE THREAD

**Issue by frozenoctobeer** [gevent/gevent#918]
* gevent version: 1.2.0 
* Python version: 2.7.12
* Operating System: macOS 10.12

### Description:

I'm working on webapp with backend using gevent. I noticed that number of threads returned by `threading.active_count()` is constantly growing. It looks like some kind of threads leak for me.

### What I've run:

I tried to investigate this problem and here is code that shows similar behaviour. Logging module seems to be key part of the problem. 
```python
from gevent import monkey
monkey.patch_all()

import gevent
import threading
import logging
import sys

logger = logging.getLogger()
logger.setLevel(logging.DEBUG)

handler = logging.StreamHandler(sys.stdout)
handler.setLevel(logging.DEBUG)
formatter = logging.Formatter('%(levelname)s - %(message)s')
handler.setFormatter(formatter)
logger.addHandler(handler)


def work(time):
    gevent.sleep(float(time))
    return str(time)


def callback(greenlet):
    logger.debug('Result: %s', greenlet.value)
    logger.debug('Threading count is %d', threading.active_count())


def main():
    grns = []
    for i in xrange(10):
        grn = gevent.spawn(work, 1)
        grn.link_value(callback)
        grns.append(grn)
    for grn in grns:
        grn.join()


def spawn_main():
    grn = gevent.spawn(main)
    grn.join()
    print 'Threading count is %d' % threading.active_count()
    print 'Threads: %s' % threading.enumerate()

if __name__ == '__main__':
    grn = gevent.spawn(spawn_main)
    grn.join()
```
Output:
```
DEBUG - Result: 1
DEBUG - Threading count is 2
DEBUG - Result: 1
DEBUG - Threading count is 3
DEBUG - Result: 1
DEBUG - Threading count is 4
DEBUG - Result: 1
DEBUG - Threading count is 5
DEBUG - Result: 1
DEBUG - Threading count is 6
DEBUG - Result: 1
DEBUG - Threading count is 7
DEBUG - Result: 1
DEBUG - Threading count is 8
DEBUG - Result: 1
DEBUG - Threading count is 9
DEBUG - Result: 1
DEBUG - Threading count is 10
DEBUG - Result: 1
DEBUG - Threading count is 11
Threading count is 11
Threads: [<_MainThread(MainThread, started 4479347280)>, <_DummyThread(DummyThread-1, started daemon 4486088336)>, ...]  # + 10 others dummy threads
```

**Comment by jamadden** [comment]
This is a consequence of using `logging` (or anything else that accesses `threading.current_thread()`)  from code run by `Greenlet.link_value` (or indeed, any link method: `Greenlet.rawlink`, `Greenlet.link`, `Greenlet.link_exception`).

The link methods are all documented to run in a new `greenlet`---note the lower case 'g', this is the grenelet provided by the `greenlet` library. These are cheaper to create and use than the `gevent.Greenlet` subclass that `gevent.spawn` creates. But as a consequence, they don't support the extra effort that `gevent.Greenlet` goes through to make sure that the `_DummyThread` instances that get created by `current_thread` get cleaned up. 

Normally, [_DummyThread doesn't ever go away](https://github.com/python/cpython/blob/3.4/Lib/threading.py#L1194), but because they're common in gevent, gevent's Greenlet goes out of its way to make sure they get cleaned up. That doesn't work when raw `greenlet` is used.

If this is a problem for you, one option is to spawn a new `gevent.Greenlet` from your link callback before doing any logging.
