### ISSUE TITLE
pywsgi doesn't use 'X-Forwarded-For' header for logging

### ISSUE THREAD

**Issue by robertaistleitner** [gevent/gevent#920]
* gevent version: 1.1.2
* Python version: 2.7.12
* Operating System: Ubuntu 16.04

### Description:

We're using [gevent-websocket](https://bitbucket.org/noppo/gevent-websocket) with gunicorn behind nginx used as a reverse-proxy. Nginx sets the "X-Forwarded-For" header to get the correct remote address of the originator of the request. Unfortunately, gevent.pywsgi doesn't utilize this information and just uses the client address when logging the request: https://github.com/gevent/gevent/blob/master/src/gevent/pywsgi.py#L881

Is this by design or a bug or is there a way to customize this logging behaviour?

**Comment by jamadden** [comment]
That's very much by design. `gevent.pywsgi` is not a full-strength, fully-configurable, production-ready server that can handle all cases. For that there's, well gunicorn. Notably in this case, `gevent.pywsgi` doesn't support any of the security configurations (like limiting incoming IPs) that can make supporting `X-Forwarded-For` safer.

If you are using gunicorn with the supplied gevent worker, gunicorn takes over request logging and gevent never logs the request, IIRC, so it could be a configuration issue with gunicorn. Alternately, perhaps gevent-websocket is bypassing gunicorn somehow (I know our own homegrown websocket support for gunicorn and gevent doesn't have that problem, but I don't know about the package you're using).

**Comment by robertaistleitner** [comment]
Thanks for the fast reply. Actually everything you wrote is true.. I'm just reviewing what is getting logged where and we're using pywsgi only in production, I need to review our production configuration using gunicorn separately.

We are using a modified version of [flask-sockets](https://github.com/kennethreitz/flask-sockets) which does some overrides for logging. Anyways, many thanks!
