### ISSUE TITLE
WSGIServer regression

### ISSUE THREAD

**Issue by marcelotduarte** [gevent/gevent#929]
* gevent version: 1.2.0 and 1.2.1
* Python version: 3.5 and 3.6
* Operating System: Win10

### Description:

```
In version 1.1.2 I had a wsgi app that runs. With newer versions it is static, nothing happens.
I used the example at gevent/examples/wsgiserver.py to test and it do the same.
```

### What I've run:

```
If I replace the last line in the example gevent/examples/wsgiserver.py:
WSGIServer(('', 8088), application).serve_forever()
to:
WSGIServer(('0.0.0.0', 8088), application).serve_forever()
It runs.
```
The original example runs in gevent 1.1.2, the modified runs at 1.1.2, 1.2.0 and 1.2.1

**Comment by jamadden** [comment]
If, when you say "nothing happens," you mean that your client can't connect to the address you expect, then you need to check what address you're listening on and what address you're connecting to and make sure they match. I suspect that you're listening on IPv6 but trying to connect to '127.0.0.1'. Since Windows doesn't support dual mode sockets that won't work.

**Comment by marcelotduarte** [comment]
Using a gevent example does'nt connect without modification. This isn't a gevent issue?
My IPv6 is disabled.
The example runs at gevent 1.1.2 and not in 1.2.0 or 1.2.1.
For me, I adapted my code (like in the example) to run, but the example needs to be corrected or a information in the docs.

**Comment by jamadden** [comment]
The example runs [just fine in our windows CI environment](https://ci.appveyor.com/project/denik/gevent/build/1.0.873/job/xt8vdpoj5vsxn46b#L2843) so long as the client and server addresses match ('' on server, 'localhost' on client). It also runs on OS X, Linux and OpenBSD (which also doesn't support dual stack sockets).

Knowing that the client and server addresses have to match in order to connect is a basic part of socket programming. It's not gevent specific. If windows makes that harder, it's still not gevent specific.

If there is a simple, elegant, and non-confusing place in the documentation to insert a pointer to additional information, I would consider a pull request, but I don't want to be a source of truth for it (since again, it's basic socket programming).

**Comment by marcelotduarte** [comment]
I think my English must be very bad, I can not explain. I'm going to use the translator.
In previous versions it works by putting the string empty, and using numeric address, regardless of whether it is basic socket programming. Perhaps they had done some interpretation of this string, which now in the newer versions must have been discarded.
As I said, I've found that, in my case, I'd just have to change the host string. And I did not think about sockets, even because I do not need to think about it very much in my programs.
But I opened this question also because I saw that it was not behaving like before, and in the changelog is said to be compatible with version 1.1.x.
I had been thinking of a pull request for the example quoted, but I see now that is not the case.
I think GEVENT is formidable, I'm still doing usage tests with the Flask application, but I see that it's fantastic.
Thanks for your attention.

**Comment by jamadden** [comment]
The meaning of `''` in a socket address was changed from `AF_INET` to `AF_INET6` (this is [documented in the release notes](http://www.gevent.org/changelog.html#servers)). On the vast majority of systems, this should make no difference so long as the client is connecting with 'localhost'; if the client is hardcoding an IPv4 address like (127.0.0.1) it might have problems on windows where dual-stack sockets aren't supported. (windows users are a very slim minority of gevent users AFAICS.)

The socket must be listening on *something* or you would be getting an exception. Try this to see exactly where a socket would be listening:
```
>>> import socket
>>> sock = socket.socket(sock.AF_INET6, socket.SOCK_STREAM)
>>> sock.bind(('', 8080))
>>> sock.getsockname()
('::', 8080, 0L, 0L)
```

That last line tells us that the socket is bound to `::`, the IPV6 equivalent of 0.0.0.0.

If instead we use 'localhost':
```
>>> sock.bind(('localhost', 8080))
None
>>> sock.getsockname()
('::1', 8080, 0L, 0L)
```

We get `::1`, which is the IPv6 equivalent of `127.0.0.1`.

Hopefully you can use all this information to figure out where your server is actually listening.

**Comment by marcelotduarte** [comment]
Reading the documentation (and I think I had not seen the change made, the patch #495) and your explanation, I understood that this change was necessary to default to ipv6. That is, it was a bugfix and not a regression.
