### ISSUE TITLE
Question: Greenlet/Hub persistence 

### ISSUE THREAD

**Issue by arcivanov** [gevent/gevent#946]
I'm currently exploring the following idea:

1. Running function in a Hub.
2. Persist Hub's current state and kill Hub.
3. Terminate Python process.
4. Start new Python process.
5. Unpickle Hub from saved data.
6. Resume function code execution where left off in [2].

Hub has (gr_frame) that contains all the globals, builtins, locals, co_code, frame, stack etc. 

Assuming a special controlled case (no globals or locals are truly non-persistable transients (e.g. network connections), no other greenlets running, "safe state" is achieved etc), is it even theoretically possible to restore Hub/greenlet in a new process and restart it from a saved state from the data contained in the greenlet?

Would like to hear your thoughts on the matter if possible.

**Comment by jamadden** [comment]
I don't believe it's possible. The C stack of the greenlet will have position-dependent values that we can't guarantee will be in the same place in a new process.

If you want to investigate that, the greenlet library will be the place to start.

(I once wrote a large system in Java based around that principle. It required writing our own interpreter because the native values couldn't be restored.)
