### ISSUE TITLE
Gevent-patched os.waitpid() with WNOHANG flag does not synchronously check child's status

### ISSUE THREAD

**Issue by asterite3** [gevent/gevent#966]
This is more a question than a bug report. When `WNOHANG` is specified, `gevent`'s replacement for `os.waitpid()` would not make any syscall. Instead it will just check it's data structure, where info on child statuses acquired by handling `SIGCHLD` is accumulated. Arriving signals are queued in event loop, so that data structure is not updated until a running greenlet blocks yields control back to an event loop. This way, if an application checks `waitpid(..., WNOHANG)` in a synchronous loop, it will never get the result.

So, if gevent-patched application imports gevent-unaware code like this:

```python
# gevent-bases app
from gevent import monkey
monkey.patch_all()
#...

# imported gevent-unaware code
import os
import time
import signal

pid = os.fork()
if not pid:
    time.sleep(1000)
    exit(0)
os.kill(pid, signal.SIGKILL)
while True:
    p, status = os.waitpid(pid, os.WNOHANG)
    if (p, status) == (0, 0): # child is still running
        # do something synchronously, for example:
        print 'Wtf child did not die from SIGKILL! Disk sleep or something?'
        continue
    # handle return status somehow here
    break
```
The imported code will break.

Clearly, this is a known issue and was mentioned here https://github.com/gevent/gevent/issues/600#issuecomment-120158061, and `waitpid` is also discussed in several other issues like https://github.com/gevent/gevent/issues/622.

The question is: is there a way to check if there are events caused by `SIGCHLD` in an event loop in `WNOHANG`-branch of `waitpid`, and, if there are any, selectively pull them from event loop, and process them (calling real `waitpid` to reap a child and updating the data structure `_watched_children`) before returning? This would fix a code like the one above.

**Comment by jamadden** [comment]
> is there a way to check if there are events caused by SIGCHLD in an event loop in WNOHANG-branch of waitpid, and, if there are any, selectively pull them from event loop, and process them 

No, I don't think so. libev doesn't expose that sort of information. It's internal state hidden from the user.

The only way to accomplish that is to yield to the event loop; *someone* has to do that.

This was [briefly mentioned before](https://github.com/gevent/gevent/issues/914#issuecomment-267686233), but `gevent.os.waitpid` currently doesn't itself yield to the event loop because that would introduce an arbitrary delay, which seems like bad behaviour on the part of a library (we don't know the context of the call, an arbitrary delay may not be acceptable at that point).

It can be argued that code like in the example that polls in a tight loop is broken already, even in the non-gevent case. It's busy burning CPU (preventing other threads/processes from running) for a potentially indefinite period of time in the case of unexpected conditions and it should either use a blocking `waitpid` or introduce its own `time.sleep` or otherwise slow its poll.

**Comment by WGH-** [comment]
I wonder if it's possible to run one iteration of the event loop, and return back to the same greenlet, not some arbitrary one.

**Comment by jamadden** [comment]
Not directly. Active watchers that are ready will have their callbacks called directly by libev. Very often that means that a switch occurs. In addition, callbacks at the Python level for things like locks are *also* scheduled with libev to run on the next iteration of the event loop automatically. We could possibly delay the callbacks with some effort, but delaying the functions registered directly with libev would be...non-trivial at least.

**Comment by WGH-** [comment]
I think it would be fine to let these callbacks run, as long as *greenlet switch* doesn't occur. They're supposed to be non-blocking and take some bound time. Correct me if I'm messing something up regarding gevent internals.

**Comment by jamadden** [comment]
A huge percent of the callbacks is something like `getcurrent().switch`, in order to resume execution where the greenlet left off. So they switch.

gevent doesn't have any sort of scheduler, it's all implicit based on these callbacks. Even if it wasn't, there's no way to know what any given callback is going to do.

**Comment by asterite3** [comment]
Thanks for the answer and explanations about libev!

> It can be argued that code like in the example that polls in a tight loop is broken already, even in the non-gevent case. It's busy burning CPU (preventing other threads/processes from running) for a potentially indefinite period of time in the case of unexpected conditions

You are right, i totally agree with that, it's just that such a code exists (a dev might have expected the loop to finish after a few iterations in normal case).

I guess it's time to close this.
