### ISSUE TITLE
"This operation would block forever" when  queue size is <1

### ISSUE THREAD

**Issue by SUP3RIA** [gevent/gevent#989]
Gevent version: 1.2.1
Python 2.7.12
Ubuntu 16.04

In my program am sending results from working coroutines via a queue to a single coroutine which writes to a file.
I need to terminate gracefully at some point so I am using an event for that to break out of a while loop. 
Since its not defined how long the working coroutines need to finish their task I can not use the timeout parameter to wait until all results are written to disk, so I am going to break the first while loop with the event and the second with a timeout.

It works just fine when the queue size is >0 but when the queue is <1 I get an error and the second while loop is not executed.
(uncomment the sleep to get queue size >0 and press Ctrl-C to break out of loop)

Error:
`gevent.hub.LoopExit: ('This operation would block forever', <Hub at 0x7f5bdcc8f050 epoll default pending=0 ref=0 fileno=3>)
`
Is this a issue with Gevent or I am just not thinking right here?

Thanks!
### What I've run:
```python

import signal
import random

import gevent
from gevent.queue import *
from gevent.event import Event

def handler(signum, frame):
    evt.set()
    print "[INFO]Shutting down gracefully."

def produce():
	for i in range(5000):
		gevent.sleep(random.uniform(0.80,0.5))
		if evt.is_set():
			break
		print "Produce:", i
		q.put(i, block=True)
	if not evt.is_set():
		evt.set()

def writer():
    try:
        with open("log.txt", "a") as myfile:
            while not evt.is_set():
                t = q.get(block=True)
                #gevent.sleep(random.uniform(1.80,1.5))#works when sleeping
                print "Writing1:", t, evt.is_set(), q.qsize()
                myfile.write(str(t)+"\n")
            while True:
                t = q.get(block=True, timeout=0.5)
                print "Writing2:", t, evt.is_set(), q.qsize()
                myfile.write(str(t)+"\n")       
    except:
        pass


evt = Event()
signal.signal(signal.SIGINT, handler)
q = gevent.queue.Queue()

threads = []
threads.append(gevent.spawn(produce))
threads.append(gevent.spawn(writer))
gevent.joinall(threads)
```

**Comment by jamadden** [comment]
You get that error when you ask gevent to block one greenlet (`writer`), but there is no possibility that anyone will wake it up again---because there is no other greenlet set to be run (all the `produce` greenlets are dead and the main greenlet is also blocked). So you need to avoid making a blocking call in `writer` (`q.get(block=True)`) once you've killed off your other greenlets.

If you have only one `produce` greenlet, the solution is simple: just have it put `StopIteration` into the queue when it's done, and simplify `writer` to just iterate the queue.

If you have multiple producers, you may be able to use that same pattern if you can use multiple writers and queues too (one-to-one). An individual write to a file wouldn't be interrupted, but the contents of the multiple queues could be interleaved; this may or may not matter to your application.

If you need to stick to a single queue but have multiple producers, then you'll need to set up a protocol for each of the producers to notify the writer when they are finished so that it stops getting the contents of the queue. One easy way is to have them post sentinel values:
```python
def writer(producer_count):
   while producer_count:
      v = q.get()
      if v is SENTINEL:
         producer_count -= 1
         continue
      else:
          ...normal processing...
```

But you can imagine other ways, even if the number of producers is dynamic.

I think this has been discussed in this tracker before so you can probably search all issues for different perspectives.

(Code and answers untested and not guaranteed; it's early in my timezone 😄 )

**Comment by SUP3RIA** [comment]
I solved my problem now by using a pseudo infinite timeout which will be changed to 2 seconds when the event is set. I feel there should be a more elegant solution though.

Thanks for helping :-)

`def writer():
    try:
        with open("log.txt", "a") as myfile:
            time_out = 99999999999 #pseudo infinity
            while True:
                if evt.is_set():
                    time_out = 2
                t = q.get(block=True, timeout=time_out)
                print "Writing:", t, evt.is_set(), q.qsize()
                myfile.write(str(t)+"\n")       
    except:
        pass`

**Comment by jamadden** [comment]
I feel that all three of the solutions I proposed are elegant and simple patterns (and as such could be consider "inbuilt"). Moreover, they do not have race conditions like the "pseudo infinite timeout" does.
